-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Muttea
-- Enclavamiento: MUT
-- Puntos de control:
-- Muttea: MUT T03, T06B, T09
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


-- - Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'MUT','MUT','Muttea',1,NULL,'A',NULL,NULL,NULL,'S',1);

-- -----------------------
-- PUNTO DE CONTROL: MUT
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MUT','MUT_VT03','1',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MUT','MUT_VT06B','2',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MUT','MUT_VT09','3',1);	

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'MUT_VT03','MUT',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MUT_VT06B','MUT',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MUT_VT09','MUT',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MUT_VT03','MUT_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MUT_VT06B','MUT_VT06B',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MUT_VT09','MUT_VT09',NULL);

-- -------------------------------------------------------
-- Tramos de trayecto en sentido PAR:  TIN <-- MUT <-- SUT
-- -------------------------------------------------------

--SUT --> MUT, NO FORMA PARTE DEL PROYECTO

-- Tabla GRP_TRAMOS
-- INSERT INTO GRP_TRAMOS VALUES (1,'SUT_MUT_VC2','SUT',NULL,NULL,NULL,NULL,'E',NULL,'MUT','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA 
-- Este CV lo dice ENR 
-- INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SUT_MUT_VC2','MUT_VTA704B',NULL); 

--MUT --> TIN

-- Tramos de RESET de salida

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'MUT_TIN_VT02A','MUT',NULL,NULL,NULL,NULL,'E',NULL,'TIN','2','PAR'); 

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MUT_TIN_VT02A','MUT_VT02A',NULL); 


-- Tramos de trayecto en sentido IMPAR:  TIN --> MUT --> SUT
-- ---------------------------------
--TIN --> MUT de entrada

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'TIN_MUT_VC1','TIN',NULL,NULL,NULL,NULL,'E',NULL,'MUT','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA 
-- Este CV lo dice ENR 
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TIN_MUT_VC1','MUT_VTA633B',NULL); 


--MUT --> SUT, NO FORMA PARTE DEL PROYECTO

-- Tramos de RESET de salida

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'MUT_SUT_VT07A','MUT',NULL,NULL,NULL,NULL,'E',NULL,'SUT','2','IMPAR'); 

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MUT_SUT_VT07A','MUT_VT07A',NULL);


-- -- -----------------------------------------------------------------------------------------------------------------------------------------


-- Parejas de tramos en sentido par:   TIN <-- MUT <-- SUT
-- --------------------------------
-- Entradas a MUT desde SUT

-- Tabla GRP_PAREJAS_TRAMOS
--INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SUT_MUT_VC2','MUT_VT06B','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
--INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SUT_MUT_VC2','MUT_VT06B','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SUT_MUT_VC2','MUT_VT06B','C','I,MUT_U8,MUT_U4',80,NULL,NULL,'1',NULL,NULL,NULL);

-- Contraflow

-- MUT_SUT_VC1 --> MUT_VT03
--INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_SUT_VC1','MUT_VT03','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_SUT_VC1','MUT_VT03','C',NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_SUT_VC1','MUT_VT03','C','I,MUT_D7CF,MUT_D3CF',80,NULL,NULL,'1',NULL,NULL,NULL);

-- MUT_SUT_VC1 --> MUT_VT09
--INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_SUT_VC1','MUT_VT09','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_SUT_VC1','MUT_VT09','C',NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_SUT_VC1','MUT_VT09','C','I,MUT_D7CF,MUT_D5CF',80,NULL,NULL,'1',NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_SUT_VC1','MUT_VT09','C','I,MUT_D5CF,MUT_D9CF',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde MUT hacia TIN 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_VT06B','MUT_TIN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_VT06B','MUT_TIN_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT06B','MUT_TIN_VC2','C','I,MUT_U4,MUT_TIG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

-- Contraflow

-- MUT_VT03 --> TIN_MUT_VC1
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_VT03','TIN_MUT_VC1','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_VT03','TIN_MUT_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT03','TIN_MUT_VC1','C','I,MUT_D3CF,MUT_TIG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);

-- MUT_VT03 --> MUT_TIN_VC2
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_VT03','MUT_TIN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_VT03','MUT_TIN_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT03','MUT_TIN_VC2','C','I,MUT_D3CF,MUT_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT03','MUT_TIN_VC2','C','I,MUT_U2,MUT_TIG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

-- MUT_VT09 --> TIN_MUT_VC1
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_VT09','TIN_MUT_VC1','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_VT09','TIN_MUT_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','TIN_MUT_VC1','C','I,MUT_D9CF,MUT_D1CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','TIN_MUT_VC1','C','I,MUT_D1CF,MUT_TIG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);

-- MUT_VT09 --> MUT_TIN_VC2
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_VT09','MUT_TIN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_VT09','MUT_TIN_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','MUT_TIN_VC2','C','I,MUT_D9CF,MUT_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','MUT_TIN_VC2','C','I,MUT_U2,MUT_TIG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar:   TIN --> MUT --> SUT
-- --------------------------------
-- Entradas a MUT desde TIN 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TIN_MUT_VC1','MUT_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TIN_MUT_VC1','MUT_VT09','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TIN_MUT_VC1','MUT_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TIN_MUT_VC1','MUT_VT09','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIN_MUT_VC1','MUT_VT03','C','I,MUT_D1,MUT_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIN_MUT_VC1','MUT_VT09','C','I,MUT_D1,MUT_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIN_MUT_VC1','MUT_VT09','C','I,MUT_D3,MUT_D9',80,NULL,NULL,'1',NULL,NULL,NULL);

-- Contraflow

-- MUT_TIN_VC2 --> MUT_VT03
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_TIN_VC2','MUT_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_TIN_VC2','MUT_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','MUT_VT03','C','I,MUT_U2CF,MUT_U4CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','MUT_VT03','C','I,MUT_U4CF,MUT_D5',80,NULL,NULL,'1',NULL,NULL,NULL);

-- MUT_TIN_VC2 --> MUT_VT06b
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_TIN_VC2','MUT_VT06B','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_TIN_VC2','MUT_VT06B','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','MUT_VT06B','C','I,MUT_U2CF,MUT_U6CF',80,NULL,NULL,'1',NULL,NULL,NULL);

-- MUT_TIN_VC2 --> MUT_VT09
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_TIN_VC2','MUT_VT09','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_TIN_VC2','MUT_VT09','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','MUT_VT09','C','I,MUT_U2CF,MUT_U4CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','MUT_VT09','C','I,MUT_U4CF,MUT_D9',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde MUT hacia SUT 

-- Tabla GRP_PAREJAS_TRAMOS
--INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_VT03','MUT_SUT_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_VT09','MUT_SUT_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
--INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_VT03','MUT_SUT_VC1','C',NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_VT09','MUT_SUT_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT03','MUT_SUT_VC1','C','I,MUT_D5,MUT_SUT_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','MUT_SUT_VC1','C','I,MUT_D9,MUT_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','MUT_SUT_VC1','C','I,MUT_D7,MUT_SUT_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);

-- Contraflow

-- MUT_VT03 --> SUT_MUT_VC2
--INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_VT03','SUT_MUT_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_VT03','SUT_MUT_VC2','C',NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT03','SUT_MUT_VC2','C','I,MUT_D5,MUT_U8CF',80,NULL,NULL,'1',NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT03','SUT_MUT_VC2','C','I,MUT_U8CF,MUT_SUT_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

-- MUT_VT06B --> SUT_MUT_VC2
--INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_VT06B','SUT_MUT_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_VT06B','SUT_MUT_VC2','C',NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT06B','SUT_MUT_VC2','C','I,MUT_U6CF,MUT_SUT_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

-- MUT_VT09 --> SUT_MUT_VC2
--INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_VT09','SUT_MUT_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_VT09','SUT_MUT_VC2','C',NULL,NULL,NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','SUT_MUT_VC2','C','I,MUT_D9,MUT_U8CF',80,NULL,NULL,'1',NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','SUT_MUT_VC2','C','I,MUT_U8CF,MUT_SUT_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------


-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).


--MUT

-- Parejas de tramos en sentido par:   TIN <-- MUT <-- SUT
-- --------------------------------
-- Entradas a MUT desde SUT, NO FORMA PARTE DEL PROYECTO


-- Salidas desde MUT hacia TIN 

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT06B','MUT_TIN_VC2','C','I,MUT_U4,MUT_TIG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4,MUT_TIG_UP', 'MUT_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4,MUT_TIG_UP', 'MUT_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4,MUT_TIG_UP', 'MUT_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4,MUT_TIG_UP', 'MUT_VT04A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4,MUT_TIG_UP', 'MUT_VT04B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4,MUT_TIG_UP', 'MUT_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- Contraflow

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT03','TIN_MUT_VC1','C','I,MUT_D3CF,MUT_TIG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_TIG_DOWN', 'MUT_D3CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_TIG_DOWN', 'MUT_D3CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_TIG_DOWN', 'MUT_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_TIG_DOWN', 'MUT_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_TIG_DOWN', 'MUT_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_TIG_DOWN', 'MUT_VT01A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT03','MUT_TIN_VC2','C','I,MUT_D3CF,MUT_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_U2', 'MUT_D3CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_U2', 'MUT_D3CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_U2', 'MUT_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_U2', 'MUT_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_U2', 'MUT_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_U2', 'MUT_VT04A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3CF,MUT_U2', 'MUT_VT04B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','TIN_MUT_VC1','C','I,MUT_D9CF,MUT_D1CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_D1CF', 'MUT_D9CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_D1CF', 'MUT_D9CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_D1CF', 'MUT_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_D1CF', 'MUT_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_D1CF', 'MUT_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_D1CF', 'MUT_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','TIN_MUT_VC1','C','I,MUT_D1CF,MUT_TIG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1CF,MUT_TIG_DOWN', 'MUT_D1CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1CF,MUT_TIG_DOWN', 'MUT_D1CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1CF,MUT_TIG_DOWN', 'MUT_VT01A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','MUT_TIN_VC2','C','I,MUT_D9CF,MUT_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_U2', 'MUT_D9CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_U2', 'MUT_D9CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_U2', 'MUT_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_U2', 'MUT_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_U2', 'MUT_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_U2', 'MUT_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_U2', 'MUT_VT04A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D9CF,MUT_U2', 'MUT_VT04B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT03','MUT_TIN_VC2','C','I,MUT_U2,MUT_TIG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_VT09','MUT_TIN_VC2','C','I,MUT_U2,MUT_TIG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2,MUT_TIG_UP', 'MUT_U2', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2,MUT_TIG_UP', 'MUT_U2', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2,MUT_TIG_UP', 'MUT_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2,MUT_TIG_UP', 'MUT_VT02B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Parejas de tramos en sentido impar:   TIN --> MUT --> SUT
-- --------------------------------
-- Entradas a MUT desde TIN 


--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIN_MUT_VC1','MUT_VT03','C','I,MUT_D1,MUT_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D5', 'MUT_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D5', 'MUT_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D5', 'MUT_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D5', 'MUT_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D5', 'MUT_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D5', 'MUT_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIN_MUT_VC1','MUT_VT09','C','I,MUT_D1,MUT_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D3', 'MUT_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D3', 'MUT_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D3', 'MUT_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D3', 'MUT_P04A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D3', 'MUT_P03B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D3', 'MUT_P03A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D1,MUT_D3', 'MUT_VT09', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIN_MUT_VC1','MUT_VT09','C','I,MUT_D3,MUT_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3,MUT_D9', 'MUT_D3', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3,MUT_D9', 'MUT_D3', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3,MUT_D9', 'MUT_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3,MUT_D9', 'MUT_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3,MUT_D9', 'MUT_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_D3,MUT_D9', 'MUT_VT09', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- Contraflow

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','MUT_VT03','C','I,MUT_U4CF,MUT_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D5', 'MUT_U4CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D5', 'MUT_U4CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D5', 'MUT_VT04A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D5', 'MUT_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D5', 'MUT_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D5', 'MUT_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D5', 'MUT_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','MUT_VT06B','C','I,MUT_U2CF,MUT_U6CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U6CF', 'MUT_U2CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U6CF', 'MUT_U2CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U6CF', 'MUT_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U6CF', 'MUT_VT04B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U6CF', 'MUT_VT04A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U6CF', 'MUT_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U6CF', 'MUT_VT06B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','MUT_VT03','C','I,MUT_U2CF,MUT_U4CF',80,NULL,NULL,'1',NULL,NULL,NULL);
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','MUT_VT09','C','I,MUT_U2CF,MUT_U4CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U4CF', 'MUT_U2CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U4CF', 'MUT_U2CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U4CF', 'MUT_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U2CF,MUT_U4CF', 'MUT_VT04B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','MUT_VT09','C','I,MUT_U4CF,MUT_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D9', 'MUT_U4CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D9', 'MUT_U4CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D9', 'MUT_VT04A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D9', 'MUT_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D9', 'MUT_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D9', 'MUT_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D9', 'MUT_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MUT_U4CF,MUT_D9', 'MUT_VT09', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Salidas desde MUT hacia SUT, NO FORMA PARTE DEL PROYECTO






