-- Datos de la linea ASYUT NAGH HAMMADI
-- Enclavamiento: BALSAFURA (BLS)

-- 1. Creamos una nueva version */
--INSERT INTO GRP_VERSIONES VALUES (1, 'BLS.1st', 'GRP de BLS', to_date('2025-02-28 11:00:00','yyyy-mm-dd hh24:mi:ss'), to_date('2025-02-28 11:00:00','yyyy-mm-dd hh24:mi:ss'));  

-- Puntos de control: 
-- BSN: Balsafura-North		T07, T10B, T16 	
-- BLS: Balsafura			T05, T08 
-- BSS: Balsafura-South		T03, T06, T15

-- Colaterales
-- SGH: Sohag
-- MON: Al Monsha


-- Tabla GRP_PUNTOS_CONTROL:
-- GRP_PUNTOS_CONTROL(ID_VERSION, ID_PUNTO_CONTROL, CODIGO_ENCLAVAMIENTO, PC_NOMBRE_MALLAS, PC_TIPO, MNEMONICO, AUTOMATICO, CAMBIO_TREN, COD_RENFE, FECHA_ULTIMO_CAMBIO_AUTOMATICO, PERMITE_CAMBIO_AUTOMATICO)
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'BSN','BLS','Balsafura-North',1,NULL,'A',NULL,NULL,NULL,'S',16);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'BLS','BLS','Balsafura',1,NULL,'A',NULL,NULL,NULL,'S',17);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'BSS','BLS','Balsafura-South',1,NULL,'A',NULL,NULL,NULL,'S',18);


-- ELEMENTOS de los puntos de contol
-- GRP_ELEMENTOS_PUNTOS_CONTROL(PUNTO_CONTROL, CODIGO_ELEMENTO, VIA, ID_VERSION)
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BSN','BLS_VT07','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BSN','BLS_VT10B','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BSN','BLS_VT16','4',1);

INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BLS','BLS_VT05','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BLS','BLS_VT08','2',1);

INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BSS','BLS_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BSS','BLS_VT06','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BSS','BLS_VT15','3',1);


---------------------------------------------------------------------
-- Tablas GRP_TRAMOS y GRP_REL_TRAMOS_CIRCUITOS_VIA
---------------------------------------------------------------------
-- Tabla GRP_TRAMOS de estacionamiento
-- INSERT INTO GRP_TRAMOS VALUES (1,ID_TRAMO,ID_PUNTO_CONTROL,NULL,NULL,NULL,NULL,E_S,NULL,NULL,VIA,SENTIDO);
INSERT INTO GRP_TRAMOS VALUES (1,'BSN_VT07','BSN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BSN_VT10B','BSN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BSN_VT16','BSN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');

INSERT INTO GRP_TRAMOS VALUES (1,'BLS_VT05','BLS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BLS_VT08','BLS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');

INSERT INTO GRP_TRAMOS VALUES (1,'BSS_VT03','BSS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BSS_VT06','BSS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BSS_VT15','BSS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');


-- INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,ID_TRAMO,COD_CV,NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BSN_VT07', 'BLS_VT07',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BSN_VT10B','BLS_VT10B',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BSN_VT16', 'BLS_VT16',NULL);

INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BLS_VT05','BLS_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BLS_VT08','BLS_VT08',NULL);

INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BSS_VT03','BLS_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BSS_VT06','BLS_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BSS_VT15','BLS_VT15',NULL);


---------------------------------------------------------------------
-- Tramos de Trayecto 
-- INSERT INTO GRP_TRAMOS VALUES (1,ID_TRAMO,ID_PUNTO_CONTROL,NULL,NULL,NULL,NULL,E_S,NULL,PC_SIGUIENTE,VIA,SENTIDO);
---------------------------------------------------------------------
-- Entrada desde SHG en sentido PAR
--INSERT INTO GRP_TRAMOS VALUES (1,'SHG_BSN_VC2','SHG',NULL,NULL,NULL,NULL,'E',NULL,'BSN','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA (Bloqueo)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHG_BSN_VC2','BLS_VTA766B',NULL);


-- Entrada desde MON en sentido IMPAR
--INSERT INTO GRP_TRAMOS VALUES (1,'MON_BSS_VC1','MON',NULL,NULL,NULL,NULL,'E',NULL,'BSS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA (Bloqueo)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MON_BSS_VC1','BLS_VTA775B',NULL);


---------------------------------------------------------------------
-- Tramos de reset
---------------------------------------------------------------------
-- Salida de BSS a MON en sentido PAR  Via 2
--INSERT INTO GRP_TRAMOS VALUES (1,'BSS_MON_VT02A','BSS',NULL,NULL,NULL,NULL,'E',NULL,'MON','2','PAR');

--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BSS_MON_VT02A','BLS_VT02A',NULL);

-- Salida de BSN a SHG en sentido IMPAR  Via 1
--INSERT INTO GRP_TRAMOS VALUES (1,'BSN_SHG_VT11A','BSN',NULL,NULL,NULL,NULL,'E',NULL,'SHG','1','IMPAR');

--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BSN_SHG_VT11A','BLS_VT11A',NULL);


--------------------------------------------------------------
-- Parejas de tramos e Itinerarios en sentido PAR	- VIA 2
-- INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,SENTIDO,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--------------------------------------------------------------
-- Entradas de SHG a BSN  via 2
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHG_BSN_VC2','BSN_VT10B','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHG_BSN_VC2','BSN_VT16', 'PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHG_BSN_VC2','BSN_VT10B','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHG_BSN_VC2','BSN_VT16', 'C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,'C',CODIGO_MANDO,80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_BSN_VC2','BSN_VT10B','C','I,BLS_U12,BLS_U8', 80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_BSN_VC2','BSN_VT16', 'C','I,BLS_U10,BLS_U14',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_BSN_VC2','BSN_VT16', 'C','I,BLS_U12,BLS_U10',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas de BSN a BLS   via 2
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BSN_VT10B','BLS_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BSN_VT16', 'BLS_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BSN_VT10B','BLS_VT08','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BSN_VT16', 'BLS_VT08','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,'C',CODIGO_MANDO,80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BSN_VT10B','BLS_VT08','C','I,BLS_U8,BLS_U6', 80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BSN_VT16', 'BLS_VT08','C','I,BLS_U14,BLS_U6', 80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas de BLS a BSS   via 2
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BLS_VT08','BSS_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BLS_VT08','BSS_VT06','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,'C',CODIGO_MANDO,80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BLS_VT08','BSS_VT06','C','I,BLS_U6,BLS_U4', 80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salida de BSS a MON   via 2
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BSS_VT06','BSS_MON_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BSS_VT06','BSS_MON_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BSS_VT06','BSS_MON_VC2','C','I,BLS_U4,BLS_MON_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


------------------------------------------------------------
-- Parejas de tramos e Itinerarios en sentido IMPAR	- VIA 1 
------------------------------------------------------------
-- Entradas de MON a BSS
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MON_BSS_VC1','BSS_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MON_BSS_VC1','BSS_VT15','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MON_BSS_VC1','BSS_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MON_BSS_VC1','BSS_VT15','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MON_BSS_VC1','BSS_VT03','C','I,BLS_D1,BLS_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MON_BSS_VC1','BSS_VT15','C','I,BLS_D3,BLS_D13',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MON_BSS_VC1','BSS_VT15','C','I,BLS_D1,BLS_D3',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas de BSS a BLS
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BSS_VT03','BLS_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BSS_VT15','BLS_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BSS_VT03','BLS_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BSS_VT15','BLS_VT05','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BSS_VT03','BLS_VT05','C','I,BLS_D5,BLS_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BSS_VT15','BLS_VT05','C','I,BLS_D13,BLS_D7',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas de BLS a BSN
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BLS_VT05','BSN_VT07','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BLS_VT05','BSN_VT07','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BLS_VT05','BSN_VT07','C','I,BLS_D7,BLS_D9',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salida de BSN a SHG
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BSN_VT07','BSN_SHG_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BSN_VT07','BSN_SHG_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BSN_VT07','BSN_SHG_VC1','C','I,BLS_D9,BLS_SHG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);



------------------------------------------------------------------------------------
-- Tabla GRP_COMPROBACIONES_MANDOS en sentido PAR  Via 2
------------------------------------------------------------------------------------
-- GRP_COMPROBACIONES_MANDOS
-- (ID_VERSION, CODIGO_MANDO, CODIGO_ELEMENTO, ASPECTO, CONDICION, OPERACION_LOGICA)
------------------------------------------------------------------------------------
-- Entradas de SHG a BSN   
--------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U8','BLS_U12','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U8','BLS_U12','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U8','BLS_P01A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U8','BLS_P02B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U8','BLS_VT12A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U8','BLS_VT10A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U8','BLS_VT10B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U10,BLS_U14','BLS_U10','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U10,BLS_U14','BLS_U10','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U10,BLS_U14','BLS_P01A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U10,BLS_U14','BLS_P02B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U10,BLS_U14','BLS_P02A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U10,BLS_U14','BLS_VT10A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U10,BLS_U14','BLS_VT16','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U10,BLS_U14','BLS_P03B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U10','BLS_U12','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U10','BLS_U12','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U10','BLS_P01A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U10','BLS_P02B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U10','BLS_P02A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');

--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U10','BLS_VT12A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U12,BLS_U10','BLS_VT12B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Entradas de BSN a BLS   via 2
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U8,BLS_U6','BLS_U8','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U8,BLS_U6','BLS_U8','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U8,BLS_U6','BLS_P03A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U8,BLS_U6','BLS_VT08','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U14,BLS_U6','BLS_U14','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U14,BLS_U6','BLS_U14','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U14,BLS_U6','BLS_P03B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U14,BLS_U6','BLS_P03A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U14,BLS_U6','BLS_VT08A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U14,BLS_U6','BLS_VT08','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Entradas de BLS a BSS   via 2
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U6,BLS_U4','BLS_U6','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U6,BLS_U4','BLS_U6','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U6,BLS_U4','BLS_P04A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U6,BLS_U4','BLS_VT08_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U6,BLS_U4','BLS_VT06','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Salida de BSS a MON   via 2
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U4,BLS_MON_UP','BLS_U4','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U4,BLS_MON_UP','BLS_U4','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U4,BLS_MON_UP','BLS_P07B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U4,BLS_MON_UP','BLS_VT04','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_U4,BLS_MON_UP','BLS_VT02A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


------------------------------------------------------------------------------------
-- Tabla GRP_COMPROBACIONES_MANDOS en sentido IMPAR  Via 1
------------------------------------------------------------------------------------
-- GRP_COMPROBACIONES_MANDOS
-- (ID_VERSION, CODIGO_MANDO, CODIGO_ELEMENTO, ASPECTO, CONDICION, OPERACION_LOGICA)
------------------------------------------------------------------------------------
-- Entradas de MON a BSS
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D5','BLS_D1','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D5','BLS_D1','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D5','BLS_P07A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D5','BLS_P06B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D5','BLS_VT01A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D5','BLS_VT01B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D5','BLS_VT03','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D3,BLS_D13','BLS_D3','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D3,BLS_D13','BLS_D3','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D3,BLS_D13','BLS_P07A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D3,BLS_D13','BLS_P06B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D3,BLS_D13','BLS_P06A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D3,BLS_D13','BLS_VT01A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D3,BLS_D13','BLS_VT01B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D3,BLS_D13','BLS_VT15','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D3,BLS_D13','BLS_P05B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D3','BLS_D1','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D3','BLS_D1','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D3','BLS_P07A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D3','BLS_P06B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D3','BLS_P06A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D3','BLS_VT01A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D1,BLS_D3','BLS_VT01B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Entradas de BSS a BLS  via 1
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D5,BLS_D7','BLS_D5','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D5,BLS_D7','BLS_D5','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D5,BLS_D7','BLS_P05A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D5,BLS_D7','BLS_P04B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D5,BLS_D7','BLS_VT05_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D5,BLS_D7','BLS_VT05','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D13,BLS_D7','BLS_D13','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D13,BLS_D7','BLS_D13','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D13,BLS_D7','BLS_P05B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D13,BLS_D7','BLS_P05A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D13,BLS_D7','BLS_P04B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D13,BLS_D7','BLS_VT05_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D13,BLS_D7','BLS_VT05','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Entradas de BLS a BSN  via 1
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D7,BLS_D9','BLS_D7','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D7,BLS_D9','BLS_D7','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D7,BLS_D9','BLS_VT07','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Salida de BSN a SHG  via 1
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D9,BLS_SHG_DOWN ','BLS_D9','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D9,BLS_SHG_DOWN ','BLS_D9','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D9,BLS_SHG_DOWN ','BLS_P01B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D9,BLS_SHG_DOWN ','BLS_VT09_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D9,BLS_SHG_DOWN ','BLS_VT09','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,BLS_D9,BLS_SHG_DOWN ','BLS_VT11A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


---------------------------------------------------------------------------------------------------


