-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Al Monsha
-- Enclavamiento: MON
-- Puntos de control:
-- Monsha: 		 MON T05, T08 y T17
-- Monsha-South: MON T03, T06 y T11 
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


-- - Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'MON','MON','Monsha',1,NULL,'A',NULL,NULL,NULL,'S',19);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'MON','MON','Monsha-South',1,NULL,'A',NULL,NULL,NULL,'S',20);


-- -----------------------
-- PUNTO DE CONTROL: MON
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MON','MON_VT05','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MON','MON_VT08','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MON','MON_VT17','3',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'MON_VT05','MON',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MON_VT08','MON',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MON_VT17','MON',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MON_VT05','MON_VT05',NULL); 
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MON_VT08','MON_VT08',NULL); 
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MON_VT17','MON_VT17',NULL);

-- -------------------------


-- Tramos de trayecto en sentido par    MOS <-- MON <-- BSS
-- ---------------------------------
-- BSS --> MON

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'BSS_MON_VC2','BSS',NULL,NULL,NULL,NULL,'E',NULL,'MON','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA (CV de disparo) (En este caso se encuentra en Balsafura)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BSS_MON_VC2','BLS_VTA782B',NULL);


-- Tramos de trayecto en sentido impar    MOS --> MON --> BSS
-- ---------------------------------

-- MON --> BSS

-- Tabla GRP_TRAMOS
-- CV de reset para la salida
--INSERT INTO GRP_TRAMOS VALUES (1,'MON_BSS_VT09A','MON',NULL,NULL,NULL,NULL,'E',NULL,'BSS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MON_BSS_VT09A','MON_VT09A',NULL);


-- -----------------------
-- PUNTO DE CONTROL: MOS
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MOS','MON_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MOS','MON_VT06','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MOS','MON_VT11','3',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'MOS_VT03','MON',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MOS_VT06','MON',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MOS_VT11','MON',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MOS_VT03','MON_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MOS_VT06','MON_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MOS_VT11','MON_VT11',NULL);

-- -------------------------

-- Tramos de trayecto en sentido par   OSN  <-- MOS <-- MON
-- ---------------------------------

-- MOS --> OSN

-- Tramos de reset 
-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'MOS_OSN_VT02A','MOS',NULL,NULL,NULL,NULL,'E',NULL,'OSN','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MOS_OSN_VT02A','MON_VT02A',NULL);


-- Tramos de trayecto en sentido impar    OSN --> MOS --> MON
-- ---------------------------------

-- OSN --> MOS

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'OSN_MOS_VC1','OSN',NULL,NULL,NULL,NULL,'E',NULL,'MOS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'OSN_MOS_VC1','OSY_VTA787B',NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------

-- -----------------------
-- PUNTO DE CONTROL: MON
-- -----------------------


-- Parejas de tramos en sentido par   MOS <-- MON <-- BSS
-- --------------------------------
-- Entradas a MON desde BSS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BSS_MON_VC2','MON_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BSS_MON_VC2','MON_VT08','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BSS_MON_VC2','MON_VT08','C','I,MON_U10,MON_U6',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde MON hacia MOS (P.C. a P.C.)

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MON_VT08','MOS_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MON_VT08','MOS_VT06','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MON_VT08','MOS_VT06','C','I,MON_U6,MON_U4',80,NULL,NULL,'1',NULL,NULL,NULL);



-- Parejas de tramos en sentido impar  MOS --> MON --> BSS
-- --------------------------------
-- Entradas a MON desde MOS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MOS_VT03','MON_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MOS_VT11','MON_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MOS_VT03','MON_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MOS_VT11','MON_VT05','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MOS_VT03','MON_VT05','C','I,MON_D5,MON_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MOS_VT11','MON_VT05','C','I,MON_D11,MON_D7',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde MON hacia BSS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MON_VT05','MON_BSS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MON_VT17','MON_BSS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MON_VT05','MON_BSS_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MON_VT17','MON_BSS_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MON_VT05','MON_BSS_VC1','C','I,MON_D7,MON_BLS_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MON_VT17','MON_BSS_VC1','C','I,MON_D13,MON_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MON_VT17','MON_BSS_VC1','C','I,MON_D9,MON_BLS_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------

-- -----------------------
-- PUNTO DE CONTROL: MOS
-- -----------------------

-- Parejas de tramos en sentido par
-- --------------------------------
-- Entradas a MOS desde MON 
-- Definidas en MON (U6-U4)

-- Salidas desde MOS hacia OSN

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MOS_VT06','MOS_OSN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MOS_VT06','MOS_OSN_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MOS_VT06','MOS_OSN_VC2','C','I,MON_U4,MON_OSY_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar  OSN --> MOS --> MON
-- --------------------------------
-- Entradas a MOS desde OSN 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'OSN_MOS_VC1','MOS_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'OSN_MOS_VC1','MOS_VT11','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'OSN_MOS_VC1','MOS_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'OSN_MOS_VC1','MOS_VT11','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSN_MOS_VC1','MOS_VT03','C','I,MON_D1,MON_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSN_MOS_VC1','MOS_VT11','C','I,MON_D1,MON_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSN_MOS_VC1','MOS_VT11','C','I,MON_D3,MON_D11',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde MOS hacia MON 

-- Definidas en las salidas de MON (D5-D7, D11-D7)

-- -----------------------------------------------------------------------------------------------------------------------------------------

-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).

-- Sentido PAR
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U10,MON_U6', 'MON_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U10,MON_U6', 'MON_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U10,MON_U6', 'MON_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U10,MON_U6', 'MON_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U10,MON_U6', 'MON_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U10,MON_U6', 'MON_VT10_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U10,MON_U6', 'MON_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U6,MON_U4', 'MON_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U6,MON_U4', 'MON_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U6,MON_U4', 'MON_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U6,MON_U4', 'MON_VT06_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U6,MON_U4', 'MON_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U4,MON_OSY_UP', 'MON_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U4,MON_OSY_UP', 'MON_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U4,MON_OSY_UP', 'MON_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U4,MON_OSY_UP', 'MON_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U4,MON_OSY_UP', 'MON_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_U4,MON_OSY_UP', 'MON_VT02_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Sentido IMPAR
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D5', 'MON_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D5', 'MON_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D5', 'MON_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D5', 'MON_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D5', 'MON_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D5', 'MON_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D3', 'MON_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D3', 'MON_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D3', 'MON_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D3', 'MON_P10A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D3', 'MON_P09B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D3', 'MON_P09A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D1,MON_D3', 'MON_VT11', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D3,MON_D11', 'MON_D3', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D3,MON_D11', 'MON_D3', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D3,MON_D11', 'MON_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D3,MON_D11', 'MON_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D3,MON_D11', 'MON_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D3,MON_D11', 'MON_VT11', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D3,MON_D11', 'MON_P08B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D5,MON_D7', 'MON_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D5,MON_D7', 'MON_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D5,MON_D7', 'MON_P08A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D5,MON_D7', 'MON_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D5,MON_D7', 'MON_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D5,MON_D7', 'MON_VT03_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D5,MON_D7', 'MON_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D11,MON_D7', 'MON_D11', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D11,MON_D7', 'MON_D11', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D11,MON_D7', 'MON_P08B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D11,MON_D7', 'MON_P08A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D11,MON_D7', 'MON_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D11,MON_D7', 'MON_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D11,MON_D7', 'MON_VT03_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D11,MON_D7', 'MON_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D7,MON_BLS_DOWN', 'MON_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D7,MON_BLS_DOWN', 'MON_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D7,MON_BLS_DOWN', 'MON_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D7,MON_BLS_DOWN', 'MON_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D7,MON_BLS_DOWN', 'MON_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D7,MON_BLS_DOWN', 'MON_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D7,MON_BLS_DOWN', 'MON_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D7,MON_BLS_DOWN', 'MON_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D13,MON_D9', 'MON_D13', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D13,MON_D9', 'MON_D13', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D13,MON_D9', 'MON_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D13,MON_D9', 'MON_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D13,MON_D9', 'MON_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D13,MON_D9', 'MON_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D13,MON_D9', 'MON_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D9,MON_BLS_DOWN', 'MON_D9', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D9,MON_BLS_DOWN', 'MON_D9', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,MON_D9,MON_BLS_DOWN', 'MON_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

