-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Al Ousayrat
-- Enclavamiento: OSY
-- Puntos de control:
-- Ousayrat: 	   OSY T03, T06, T11
-- Ousayrat-North: OSN T05, T08, T12
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


-- - Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'OSN','OSY','Ousayrat-North',1,NULL,'A',NULL,NULL,NULL,'S',21);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'OSY','OSY','Ousayrat',1,NULL,'A',NULL,NULL,NULL,'S',22);

-- -----------------------
-- PUNTO DE CONTROL: OSY
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('OSY','OSY_VT03','1',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('OSY','OSY_VT06','2',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('OSY','OSY_VT11','3',1);	


-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'OSY_VT03','OSY',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'OSY_VT06','OSY',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'OSY_VT11','OSY',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');


-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'OSY_VT03','OSY_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'OSY_VT06','OSY_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'OSY_VT11','OSY_VT11',NULL);

-- -------------------------------------------------------
-- Tramos de trayecto en sentido PAR:  GRN <-- OSY <-- OSN
-- -------------------------------------------------------

--OSY --> GRN

-- Tramos de RESET de salida

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'OSY_GRN_VT02A','OSY',NULL,NULL,NULL,NULL,'E',NULL,'GRN','2','PAR'); 

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'OSY_GRN_VT02A','OSY_VT02A',NULL); 


-- Tramos de trayecto en sentido IMPAR:  GRN --> OSY --> OSN
-- ---------------------------------
--GRN --> OSY de entrada

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'GRN_OSY_VC1','GRN',NULL,NULL,NULL,NULL,'E',NULL,'OSY','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA 
-- Este CV lo dice ENR 
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRN_OSY_VC1','OSY_VTA799B',NULL); 


-- -- -----------------------------------------------------------------------------------------------------------------------------------------

-- -----------------------
-- PUNTO DE CONTROL: OSN
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('OSN','OSY_VT05','1',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('OSN','OSY_VT08','2',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('OSN','OSY_VT12','4',1);	

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'OSN_VT05','OSN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'OSN_VT08','OSN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'OSN_VT12','OSN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'OSN_VT05','OSY_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'OSN_VT08','OSY_VT08',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'OSN_VT12','OSY_VT12',NULL);


-- Tramos de trayecto en sentido PAR:  OSY <-- OSN <-- MOS
-- ---------------------------------

-- MOS --> OSN

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'MOS_OSN_VC2','MOS',NULL,NULL,NULL,NULL,'E',NULL,'OSN','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--Este CV lo dice ENR (Es como ADIF de Egipto) 
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MOS_OSN_VC2','OSY_VTA796B',NULL);


-- Tramos de trayecto en sentido IMPAR:  OSY --> OSN --> MOS
-- ---------------------------------

-- OSN --> MOS, de salida

-- Tramos de RESET

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada)
--INSERT INTO GRP_TRAMOS VALUES (1,'OSN_MOS_VT09A','OSN',NULL,NULL,NULL,NULL,'E',NULL,'MOS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'OSN_MOS_VT09A','OSY_VT09A',NULL);


-- -- -----------------------------------------------------------------------------------------------------------------------------------------


-- -----------------------
-- PUNTO DE CONTROL: OSY
-- -----------------------

-- Parejas de tramos en sentido par:   GRN <-- OSY <-- OSN
-- --------------------------------
-- Entradas a OSY desde OSN (P.C a P.C)

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'OSN_VT08','OSY_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'OSN_VT12','OSY_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'OSN_VT08','OSY_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'OSN_VT12','OSY_VT06','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSN_VT08','OSY_VT06','C','I,OSY_U6,OSY_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSN_VT12','OSY_VT06','C','I,OSY_U12,OSY_U4',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde OSY hacia GRN 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'OSY_VT06','OSY_GRN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'OSY_VT06','OSY_GRN_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSY_VT06','OSY_GRN_VC2','C','I,OSY_U4,OSY_GRN_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSY_VT06','OSY_GRN_VC2','C','I,OSY_U4,OSY_GRG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);



-- Parejas de tramos en sentido impar:   GRN --> OSY --> OSN
-- --------------------------------
-- Entradas a OSY desde GRN 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRN_OSY_VC1','OSY_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRN_OSY_VC1','OSY_VT11','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRN_OSY_VC1','OSY_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRN_OSY_VC1','OSY_VT11','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_OSY_VC1','OSY_VT03','C','I,OSY_D1,OSY_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_OSY_VC1','OSY_VT11','C','I,OSY_D1,OSY_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_OSY_VC1','OSY_VT11','C','I,OSY_D3,OSY_D11',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde OSY hacia OSN (P.C a P.C)

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'OSY_VT03','OSN_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'OSY_VT11','OSN_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'OSY_VT03','OSN_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'OSY_VT11','OSN_VT05','C',NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSY_VT03','OSN_VT05','C','I,OSY_D5,OSY_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSY_VT11','OSN_VT05','C','I,OSY_D11,OSY_D7',80,NULL,NULL,'1',NULL,NULL,NULL); 


-- -----------------------------------------------------------------------------------------------------------------------------------------


-- -----------------------
-- PUNTO DE CONTROL: OSN
-- -----------------------

-- Parejas de tramos en sentido par:   OSY <-- OSN <-- MOS
-- --------------------------------
-- Entradas a OSN desde MOS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MOS_OSN_VC2','OSN_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MOS_OSN_VC2','OSN_VT12','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MOS_OSN_VC2','OSN_VT08','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MOS_OSN_VC2','OSN_VT12','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MOS_OSN_VC2','OSN_VT08','C','I,OSY_U10,OSY_U6',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MOS_OSN_VC2','OSN_VT12','C','I,OSY_U10,OSY_U8',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MOS_OSN_VC2','OSN_VT12','C','I,OSY_U8,OSY_U12',80,NULL,NULL,'1',NULL,NULL,NULL); 

-- Salidas desde OSN hacia OSY -> Definidas en el sentido PAR de OSY

-- Tabla GRP_PAREJAS_TRAMOS
-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
-- Tabla GRP_PAREJAS_TRAMOS_MANDOS (U6-U4 y U12-U4)


-- Parejas de tramos en sentido impar:   OSY --> OSN --> MOS
-- --------------------------------
-- Entradas a OSN desde OSY -> Definidas en el sentido IMPAR de OSY

-- Tabla GRP_PAREJAS_TRAMOS
-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
-- Tabla GRP_PAREJAS_TRAMOS_MANDOS (D5-D7 Y D11-D7)


-- Salidas desde OSN hacia MOS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'OSN_VT05','OSN_MOS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'OSN_VT05','OSN_MOS_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSN_VT05','OSN_MOS_VC1','C','I,OSY_D7,OSY_MOS_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSN_VT05','OSN_MOS_VC1','C','I,OSY_D7,OSY_MON_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------


-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).


--OSY

-- Parejas de tramos en sentido par:   GRN <-- OSY <-- OSN
-- --------------------------------
-- Entradas a OSY desde OSN

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSN_VT08','OSY_VT06','C','I,OSY_U6,OSY_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U6,OSY_U4', 'OSY_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U6,OSY_U4', 'OSY_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U6,OSY_U4', 'OSY_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U6,OSY_U4', 'OSY_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U6,OSY_U4', 'OSY_VT06_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U6,OSY_U4', 'OSY_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSN_VT12','OSY_VT06','C','I,OSY_U12,OSY_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U12,OSY_U4', 'OSY_U12', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U12,OSY_U4', 'OSY_U12', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U12,OSY_U4', 'OSY_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U12,OSY_U4', 'OSY_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U12,OSY_U4', 'OSY_VT06_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U12,OSY_U4', 'OSY_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');



-- Salidas desde OSY hacia GRN 

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSY_VT06','OSY_GRN_VC2','C','I,OSY_U4,OSY_GRN_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRN_UP', 'OSY_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRN_UP', 'OSY_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRN_UP', 'OSY_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRN_UP', 'OSY_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRN_UP', 'OSY_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRN_UP', 'OSY_VT02_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRN_UP', 'OSY_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRG_UP', 'OSY_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRG_UP', 'OSY_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRG_UP', 'OSY_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U4,OSY_GRG_UP', 'OSY_VT02_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Parejas de tramos en sentido impar:   GRN --> OSY --> OSN
-- --------------------------------
-- Entradas a OSY desde GRN 

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_OSY_VC1','OSY_VT03','C','I,OSY_D1,OSY_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D5', 'OSY_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D5', 'OSY_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D5', 'OSY_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D5', 'OSY_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D5', 'OSY_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D5', 'OSY_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D5', 'OSY_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_OSY_VC1','OSY_VT11','C','I,OSY_D1,OSY_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D3', 'OSY_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D3', 'OSY_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D3', 'OSY_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D3', 'OSY_P09A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D3', 'OSY_P07B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D3', 'OSY_P07A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D1,OSY_D3', 'OSY_VT11', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');	

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_OSY_VC1','OSY_VT11','C','I,OSY_D3,OSY_D11',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D3,OSY_D11', 'OSY_D3', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D3,OSY_D11', 'OSY_D3', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D3,OSY_D11', 'OSY_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D3,OSY_D11', 'OSY_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D3,OSY_D11', 'OSY_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D3,OSY_D11', 'OSY_VT11', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D3,OSY_D11', 'OSY_P05A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');



-- Salidas desde OSY hacia OSN

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSY_VT03','OSN_VT05','C','I,OSY_D5,OSY_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D5,OSY_D7', 'OSY_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D5,OSY_D7', 'OSY_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D5,OSY_D7', 'OSY_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D5,OSY_D7', 'OSY_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D5,OSY_D7', 'OSY_VT05_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D5,OSY_D7', 'OSY_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSY_VT11','OSN_VT05','C','I,OSY_D11,OSY_D7',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D11,OSY_D7', 'OSY_D11', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D11,OSY_D7', 'OSY_D11', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D11,OSY_D7', 'OSY_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D11,OSY_D7', 'OSY_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D11,OSY_D7', 'OSY_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D11,OSY_D7', 'OSY_VT11_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D11,OSY_D7', 'OSY_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


--OSN

-- Parejas de tramos en sentido par:   OSY <-- OSN <-- MOS
-- --------------------------------
-- Entradas a OSN desde MOS

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MOS_OSN_VC2','OSN_VT08','C','I,OSY_U10,OSY_U6',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U6', 'OSY_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U6', 'OSY_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U6', 'OSY_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U6', 'OSY_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U6', 'OSY_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U6', 'OSY_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MOS_OSN_VC2','OSN_VT12','C','I,OSY_U10,OSY_U8',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U8', 'OSY_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U8', 'OSY_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U8', 'OSY_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U8', 'OSY_P01A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 

--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U8', 'OSY_P02B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U8', 'OSY_P02A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U10,OSY_U8', 'OSY_VT12', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');	

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MOS_OSN_VC2','OSN_VT12','C','I,OSY_U8,OSY_U12',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U8,OSY_U12', 'OSY_U8', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U8,OSY_U12', 'OSY_U8', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U8,OSY_U12', 'OSY_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U8,OSY_U12', 'OSY_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U8,OSY_U12', 'OSY_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U8,OSY_U12', 'OSY_VT12', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_U8,OSY_U12', 'OSY_P04B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 



-- Salidas desde OSN hacia OSY (Declaradas como entradas en OSY)


-- Parejas de tramos en sentido impar:   OSY --> OSN --> MOS
-- --------------------------------
-- Entradas a OSN desde OSY (Declaradas como salidas en OSY)


-- Salidas desde OSN hacia MOS

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSN_VT05','OSN_MOS_VC1','C','I,OSY_D7,OSY_MOS_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D7,OSY_MOS_DOWN', 'OSY_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D7,OSY_MOS_DOWN', 'OSY_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D7,OSY_MOS_DOWN', 'OSY_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D7,OSY_MOS_DOWN', 'OSY_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D7,OSY_MOS_DOWN', 'OSY_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D7,OSY_MON_DOWN', 'OSY_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D7,OSY_MON_DOWN', 'OSY_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,OSY_D7,OSY_MON_DOWN', 'OSY_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

