-- Datos de la linea ASYUT NAGH HAMMADI
-- Enclavamiento: GIRGA (GRG)

-- 1. Creamos una nueva version */
-- INSERT INTO GRP_VERSIONES VALUES (1, 'GRG.1st', 'GRP de GRG', to_date('2025-02-28 11:00:00','yyyy-mm-dd hh24:mi:ss'), to_date('2025-02-28 11:00:00','yyyy-mm-dd hh24:mi:ss'));  

-- Puntos de control: 
-- GRS: Girga-North		T07, T10, T14, T17	
-- GRG: Girga			T05, T08, 						T15 deleted
-- GRN: Girga-South		T03, T06, T13 



-- Colaterales
-- OSY: Al Ousayrat
-- BRN: Bardis-North

-- Tabla GRP_PUNTOS_CONTROL:
-- GRP_PUNTOS_CONTROL(ID_VERSION, ID_PUNTO_CONTROL, CODIGO_ENCLAVAMIENTO, PC_NOMBRE_MALLAS, PC_TIPO, MNEMONICO, AUTOMATICO, CAMBIO_TREN, COD_RENFE, FECHA_ULTIMO_CAMBIO_AUTOMATICO, PERMITE_CAMBIO_AUTOMATICO)
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'GRS','GRG','Girga-North',1,NULL,'A',NULL,NULL,NULL,'S',23);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'GRG','GRG','Girga',1,NULL,'A',NULL,NULL,NULL,'S',24);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'GRN','GRG','Girga-South',1,NULL,'A',NULL,NULL,NULL,'S',25);


-- ELEMENTOS de los puntos de contol
-- GRP_ELEMENTOS_PUNTOS_CONTROL(PUNTO_CONTROL, CODIGO_ELEMENTO, VIA, ID_VERSION)
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GRN','GRG_VT07','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GRN','GRG_VT10','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GRN','GRG_VT17','3',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GRN','GRG_VT14','4',1);

INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GRG','GRG_VT05','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GRG','GRG_VT08','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GRG','GRG_VT15','3',1);

INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GRS','GRG_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GRS','GRG_VT06','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GRS','GRG_VT13','3',1);

---------------------------------------------------------------------
-- Tablas GRP_TRAMOS y GRP_REL_TRAMOS_CIRCUITOS_VIA
---------------------------------------------------------------------
-- Tabla GRP_TRAMOS de estacionamiento
-- INSERT INTO GRP_TRAMOS VALUES (1,ID_TRAMO,ID_PUNTO_CONTROL,NULL,NULL,NULL,NULL,E_S,NULL,NULL,VIA,SENTIDO);
INSERT INTO GRP_TRAMOS VALUES (1,'GRN_VT07','GRN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GRN_VT10','GRN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GRN_VT17','GRN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GRN_VT14','GRN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');

INSERT INTO GRP_TRAMOS VALUES (1,'GRG_VT05','GRG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GRG_VT08','GRG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GRG_VT15','GRG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

INSERT INTO GRP_TRAMOS VALUES (1,'GRS_VT03','GRS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GRS_VT06','GRS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GRS_VT13','GRS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
-- INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,ID_TRAMO,COD_CV,NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRN_VT07','GRG_VT07',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRN_VT10','GRG_VT10',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRN_VT17','GRG_VT17',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRN_VT14','GRG_VT14',NULL);

INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRG_VT05','GRG_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRG_VT08','GRG_VT08',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRG_VT15','GRG_VT15',NULL);

INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRS_VT03','GRG_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRS_VT06','GRG_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRS_VT13','GRG_VT13',NULL);


---------------------------------------------------------------------
-- Tramos de Trayecto 
-- INSERT INTO GRP_TRAMOS VALUES (1,ID_TRAMO,ID_PUNTO_CONTROL,NULL,NULL,NULL,NULL,E_S,NULL,NULL,VIA,SENTIDO);
---------------------------------------------------------------------
---- Entrada (desde OSY) en sentido PAR
--INSERT INTO GRP_TRAMOS VALUES (1,'OSY_GRN_VC2','OSY',NULL,NULL,NULL,NULL,'E',NULL,'GRN','2','PAR');
--
---- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA (Bloqueo)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'OSY_GRN_VC2','GRG_VTA808B',NULL);
--
--
---- Entrada (desde BRN) en sentido IMPAR
--INSERT INTO GRP_TRAMOS VALUES (1,'BRN_GRS_VC1','BRN',NULL,NULL,NULL,NULL,'E',NULL,'GRS','1','IMPAR');
--
---- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA (Bloqueo)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRN_GRS_VC1','GRG_VTA813B',NULL);
--
--
-----------------------------------------------------------------------
---- Tramos de reset
-----------------------------------------------------------------------
---- Salida de GRN a BRN en sentido PAR
--INSERT INTO GRP_TRAMOS VALUES (1,'GRS_BRN_VT02A','GRS',NULL,NULL,NULL,NULL,'E',NULL,'BRN','2','PAR');
--
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRS_BRN_VT02A','GRG_VT02A',NULL);
--
---- Salida de GRN a OSY en sentido PAR
--INSERT INTO GRP_TRAMOS VALUES (1,'GRN_OSY_VT11_I','GRN',NULL,NULL,NULL,NULL,'E',NULL,'OSY','1','IMPAR');
--
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRN_OSY_VT11_I','GRG_VT11_I',NULL);
--

--------------------------------------------------------------
-- Parejas de tramos e Itinerarios en sentido PAR	- VIA 2
-- INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,SENTIDO,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--------------------------------------------------------------
-- Entradas de OSY a GRN
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'OSY_GRN_VC2','GRN_VT10','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'OSY_GRN_VC2','GRN_VT14','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'OSY_GRN_VC2','GRN_VT10','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'OSY_GRN_VC2','GRN_VT14','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,'C',CODIGO_MANDO,80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSY_GRN_VC2','GRN_VT10','C','I,GRG_U12,GRG_U8',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSY_GRN_VC2','GRN_VT14','C','I,GRG_U10,GRG_U14',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'OSY_GRN_VC2','GRN_VT14','C','I,GRG_U12,GRG_U10',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas de GRN a GRG
-------------------------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRN_VT10','GRG_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRN_VT14','GRG_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRN_VT10','GRG_VT08','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRN_VT14','GRG_VT08','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_VT10','GRG_VT08','C','I,GRG_U8,GRG_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_VT14','GRG_VT08','C','I,GRG_U14,GRG_U6',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas de GRG a GRS
-------------------------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRG_VT08','GRS_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRG_VT08','GRS_VT06','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRG_VT08','GRS_VT06','C','I,GRG_U6,GRG_U4',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas de GRS a BRN
-------------------------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRS_VT06','GRS_BRN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRS_VT06','GRS_BRN_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRS_VT06','GRS_BRN_VC2','C','I,GRG_U4, GRG_BRN_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRS_VT06','GRS_BRN_VC2','C','I,GRG_U4,GRG_BRD_UP',80,NULL,NULL,'1',NULL,NULL,NULL);



------------------------------------------------------------
-- Parejas de tramos e Itinerarios en sentido IMPAR	- VIA 1 
------------------------------------------------------------
-- Entradas de BRN a GRS
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRN_GRS_VC1','GRS_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRN_GRS_VC1','GRS_VT13','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRN_GRS_VC1','GRS_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRN_GRS_VC1','GRS_VT13','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRN_GRS_VC1','GRS_VT03','C','I,GRG_D1,GRG_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRN_GRS_VC1','GRS_VT13','C','I,GRG_D3,GRG_D13',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRN_GRS_VC1','GRS_VT13','C','I,GRG_D1,GRG_D3',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas de GRS a GRG
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRS_VT03','GRG_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRS_VT13','GRG_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRS_VT03','GRG_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRS_VT13','GRG_VT05','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRS_VT03','GRG_VT05','C','I,GRG_D5,GRG_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRS_VT13','GRG_VT05','C','I,GRG_D13,GRG_D7',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas de GRG a GRN
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRG_VT05','GRN_VT07','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRG_VT05','GRN_VT07','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRG_VT05','GRN_VT07','C','I,GRG_D7,GRG_D9',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas de GRN a OSY
-------------------------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRN_VT07','GRN_OSY_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRN_VT17','GRN_OSY_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRN_VT07','GRN_OSY_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRN_VT17','GRN_OSY_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_VT07','GRN_OSY_VC1','C','I,GRG_D9,GRG_OSY_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_VT17','GRN_OSY_VC1','C','I,GRG_D15,GRG_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRN_VT17','GRN_OSY_VC1','C','I,GRG_D9,GRG_OSY_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);


------------------------------------------------------------------------------------
-- Tabla GRP_COMPROBACIONES_MANDOS en sentido PAR  Via 2
------------------------------------------------------------------------------------
-- GRP_COMPROBACIONES_MANDOS
-- (ID_VERSION, CODIGO_MANDO, CODIGO_ELEMENTO, ASPECTO, CONDICION, OPERACION_LOGICA)
------------------------------------------------------------------------------------

-- Entradas de OSY a GRN 
--------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U8','GRG_U12','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U8','GRG_U12','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U8','GRG_P01A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U8','GRG_P02B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U8','GRG_P04B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U8','GRG_VT12B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U8','GRG_VT10', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U10,GRG_U14','GRG_U10','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U10,GRG_U14','GRG_U10','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U10,GRG_U14','GRG_P01A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U10,GRG_U14','GRG_P02B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U10,GRG_U14','GRG_P04B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U10,GRG_U14','GRG_P04A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U10,GRG_U14','GRG_VT14','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U10,GRG_U14','GRG_P07B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U10','GRG_U12','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U10','GRG_U12','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U10','GRG_P01A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U10','GRG_P02B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U10','GRG_P04B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U10','GRG_P04A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U10','GRG_VT12B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U12,GRG_U10','GRG_VT14', 'CV.NOR.ITG.ITI','E','LIBRERIA_AND');


-- Entradas de GRN a GRG
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U8,GRG_U6','GRG_U8','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U8,GRG_U6','GRG_U8','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MGRG_D9ANDOS VALUES (1,'I,GRG_U8,GRG_U6','GRG_P07A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U8,GRG_U6','GRG_VT08','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U14,GRG_U6','GRG_U14','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U14,GRG_U6','GRG_U14','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U14,GRG_U6','GRG_P07B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U14,GRG_U6','GRG_P07A', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U14,GRG_U6','GRG_VT08', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Entradas de GRG a GRS
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U6,GRG_U4','GRG_U6','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U6,GRG_U4','GRG_U6','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U6,GRG_U4','GRG_P12B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U6,GRG_U4','GRG_P13A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U6,GRG_U4','GRG_VT08_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U6,GRG_U4','GRG_VT06_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U6,GRG_U4','GRG_VT06','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Salidas de GRS a BRN por V2
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U4,GRG_BRD_UP','GRG_U4','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U4,GRG_BRD_UP','GRG_U4','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U4,GRG_BRD_UP','GRG_P16B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U4,GRG_BRD_UP','GRG_VT08_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U4,GRG_BRD_UP','GRG_VT04', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_U4,GRG_BRD_UP','GRG_VT02A', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


---------------------------------------
-- Tabla GRP_COMPROBACIONES_MANDOS en sentido IMPAR por Via 1
-- Entradas de BRN a GRS 
---------------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D5','GRG_D1','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D5','GRG_D1','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D5','GRG_P16A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D5','GRG_P15B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D5','GRG_VT01B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D5','GRG_VT03', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D3,GRG_D13','GRG_D3','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D3,GRG_D13','GRG_D3','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D3,GRG_D13','GRG_P16A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D3,GRG_D13','GRG_P15B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D3,GRG_D13','GRG_P15A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D3,GRG_D13','GRG_VT13','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D3,GRG_D13','GRG_P14B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D3','GRG_D1','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D3','GRG_D1','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D3','GRG_P16A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D3','GRG_P15B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D3','GRG_P15A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D1,GRG_D3','GRG_VT01B', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Entradas de GRS a GRG 
---------------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D5,GRG_D7','GRG_D5','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D5,GRG_D7','GRG_D5','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D5,GRG_D7','GRG_P14A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D5,GRG_D7','GRG_P13B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D5,GRG_D7','GRG_P12A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D5,GRG_D7','GRG_P11B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D5,GRG_D7','GRG_VT03_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D5,GRG_D7','GRG_VT05_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D5,GRG_D7','GRG_VT05',  'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D13,GRG_D7','GRG_D13','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D13,GRG_D7','GRG_D13','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D13,GRG_D7','GRG_P14B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D13,GRG_D7','GRG_P14A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D13,GRG_D7','GRG_P13B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D13,GRG_D7','GRG_P12A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D13,GRG_D7','GRG_P11B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D13,GRG_D7','GRG_VT03_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D13,GRG_D7','GRG_VT05_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D13,GRG_D7','GRG_VT05',  'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');



-- Entradas de GRG a GRN 
---------------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D7,GRG_D9','GRG_D7','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D7,GRG_D9','GRG_D7','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D7,GRG_D9','GRG_P05B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Salida de GRN a OSY
---------------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D15,GRG_D9','GRG_D15','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D15,GRG_D9','GRG_D15','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D15,GRG_D9','GRG_P05A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D15,GRG_D9','GRG_P05B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D9,GRG_OSY_DOWN','GRG_D9','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D9,GRG_OSY_DOWN','GRG_D9','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D9,GRG_OSY_DOWN','GRG_P02A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D9,GRG_OSY_DOWN','GRG_P01B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D9,GRG_OSY_DOWN','GRG_VT09','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D9,GRG_OSY_DOWN','GRG_VT011_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,GRG_D9,GRG_OSY_DOWN','GRG_VT11_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


