-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Bardis
-- Enclavamiento: BRN
-- Puntos de control:
-- Bardis-North: BRN (T05 y T08B)
-- Bardis:	 	 BRD (T03, T06, T09, T10, T12 y T14)
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

-- - Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'BRN','BRD','Bardis-North',1,NULL,'A',NULL,NULL,NULL,'S', 26);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'BRD','BRD','Bardis',1,NULL,'A',NULL,NULL,NULL,'S', 27);

-- -----------------------
-- PUNTO DE CONTROL: BRN
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL:
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BRN','BRD_VT05','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BRN','BRD_VT08B','2',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'BRN_VT05','BRN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BRN_VT08B','BRN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRN_VT05','BRD_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRN_VT08B','BRD_VT08B',NULL);

-- -------------------------


-- Tramos de trayecto en sentido par  BRD <-- BRN <-- GRS
-- ---------------------------------
-- GRS -> BRN 

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'GRS_BRN_VC2','GRS',NULL,NULL,NULL,NULL,'E',NULL,'BRN','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GRS_BRN_VC2','BRD_VTA822B',NULL);


-- Tramos de trayecto en sentido impar  BRD -> BRN -> GRS
-- ---------------------------------
-- BRN -> GRS

-- Tramos de reset

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'BRN_GRS_VT07_I','BRN',NULL,NULL,NULL,NULL,'E',NULL,'GRS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRN_GRS_VT07_I','BRD_VT07_I',NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------


-- -----------------------
-- PUNTO DE CONTROL: BRD
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL:
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BRD','BRD_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BRD','BRD_VT06','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BRD','BRD_VT09','3',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BRD','BRD_VT10','4',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BRD','BRD_VT12','6',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BRD','BRD_VT14','8',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'BRD_VT03','BRD',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BRD_VT06','BRD',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BRD_VT09','BRD',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BRD_VT10','BRD',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BRD_VT12','BRD',NULL,NULL,NULL,NULL,'S',NULL,NULL,'6','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BRD_VT14','BRD',NULL,NULL,NULL,NULL,'S',NULL,NULL,'8','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRD_VT03','BRD_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRD_VT06','BRD_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRD_VT09','BRD_VT09',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRD_VT10','BRD_VT10',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRD_VT12','BRD_VT12',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRD_VT14','BRD_VT14',NULL);

-- -------------------------


-- Tramos de trayecto en sentido par  BLY <-- BRD <-- BRN
-- ---------------------------------
-- BRD -> BLY

-- Tramos de reset

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'BRD_BLY_VT02A','BRD',NULL,NULL,NULL,NULL,'E',NULL,'BLY','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRD_BLY_VT02A','BRD_VT02A',NULL);


-- Tramos de trayecto en sentido impar  BLY -> BRD -> BRN
-- ---------------------------------
-- BLY -> BRD

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'BLY_BRD_VC1','BLY',NULL,NULL,NULL,NULL,'E',NULL,'BRD','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BLY_BRD_VC1','BLY_VTA829B',NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------

-- -----------------------
-- PUNTO DE CONTROL: BRN
-- -----------------------

-- Parejas de tramos en sentido par
-- --------------------------------
-- Entradas a BRN desde GRS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GRS_BRN_VC2','BRN_VT08B','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GRS_BRN_VC2','BRN_VT08B','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GRS_BRN_VC2','BRN_VT08B','C','I,BRD_U8,BRD_U6',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde BRN hacia BRD
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRN_VT08B','BRD_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRN_VT08B','BRD_VT10','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRN_VT08B','BRD_VT12','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRN_VT08B','BRD_VT14','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRN_VT08B','BRD_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRN_VT08B','BRD_VT10','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRN_VT08B','BRD_VT12','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRN_VT08B','BRD_VT14','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRN_VT08B','BRD_VT06','C','I,BRD_U6,BRD_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRN_VT08B','BRD_VT10','C','I,BRD_U6,BRD_U10',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRN_VT08B','BRD_VT12','C','I,BRD_U6,BRD_U12',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRN_VT08B','BRD_VT14','C','I,BRD_U6,BRD_U14',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar
-- --------------------------------
-- Entradas a BRN desde BRD

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRD_VT03','BRN_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRD_VT09','BRN_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRD_VT03','BRN_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRD_VT09','BRN_VT05','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_VT03','BRN_VT05','C','I,BRD_D5,BRD_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_VT09','BRN_VT05','C','I,BRD_D9,BRD_D7',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde BRN hacia GRS
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRN_VT05','BRN_GRS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRN_VT05','BRN_GRS_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRN_VT05','BRN_GRS_VC1','C','I,BRD_D7,BRD_GRG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);



-- -----------------------
-- PUNTO DE CONTROL: BRD
-- -----------------------

-- Parejas de tramos en sentido par
-- --------------------------------
-- Entradas a BRD desde BRN
-- Definidas en BRN

-- Salidas desde BRD hacia BLY
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRD_VT06','BRD_BLY_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRD_VT10','BRD_BLY_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRD_VT12','BRD_BLY_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRD_VT14','BRD_BLY_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRD_VT06','BRD_BLY_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRD_VT10','BRD_BLY_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRD_VT12','BRD_BLY_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRD_VT14','BRD_BLY_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_VT06','BRD_BLY_VC2','C','I,BRD_U4,BRD_BLY_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_VT10','BRD_BLY_VC2','C','I,BRD_U10,BRD_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_VT10','BRD_BLY_VC2','C','I,BRD_U2,BRD_BLY_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_VT12','BRD_BLY_VC2','C','I,BRD_U12,BRD_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_VT12','BRD_BLY_VC2','C','I,BRD_U2,BRD_BLY_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_VT14','BRD_BLY_VC2','C','I,BRD_U14,BRD_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_VT14','BRD_BLY_VC2','C','I,BRD_U2,BRD_BLY_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar
-- --------------------------------
-- Entradas a BRD desde BLY

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BLY_BRD_VC1','BRD_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BLY_BRD_VC1','BRD_VT09','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BLY_BRD_VC1','BRD_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BLY_BRD_VC1','BRD_VT09','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BLY_BRD_VC1','BRD_VT03','C','I,BRD_D1,BRD_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BLY_BRD_VC1','BRD_VT09','C','I,BRD_D1,BRD_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BLY_BRD_VC1','BRD_VT09','C','I,BRD_D3,BRD_D9',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde BRD hacia BRN
-- Definidas en BRN

-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).

-- Entradas sentido par a BRN
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U8,BRD_U6', 'BRD_U8', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U8,BRD_U6', 'BRD_U8', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U8,BRD_U6', 'BRD_VT08B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U8,BRD_U6', 'BRD_P01B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');


-- Salidas sentido par a BRD
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U4', 'BRD_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U4', 'BRD_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U4', 'BRD_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U4', 'BRD_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U4', 'BRD_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U10', 'BRD_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U10', 'BRD_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U10', 'BRD_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U10', 'BRD_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U10', 'BRD_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U10', 'BRD_P04', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U10', 'BRD_VT10', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U12', 'BRD_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U12', 'BRD_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U12', 'BRD_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U12', 'BRD_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U12', 'BRD_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U12', 'BRD_P04', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U12', 'BRD_P05', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U12', 'BRD_VT12', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U14', 'BRD_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U14', 'BRD_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U14', 'BRD_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U14', 'BRD_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U14', 'BRD_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U14', 'BRD_P04', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U14', 'BRD_P05', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U6,BRD_U14', 'BRD_VT14', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- Entradas sentido impar a BRN
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D5,BRD_D7', 'BRD_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D5,BRD_D7', 'BRD_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D5,BRD_D7', 'BRD_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D5,BRD_D7', 'BRD_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D5,BRD_D7', 'BRD_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D9,BRD_D7', 'BRD_D9', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D9,BRD_D7', 'BRD_D9', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D9,BRD_D7', 'BRD_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D9,BRD_D7', 'BRD_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D9,BRD_D7', 'BRD_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D9,BRD_D7', 'BRD_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- Salidas sentido impar a GRG
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D7,BRD_GRG_DOWN', 'BRD_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D7,BRD_GRG_DOWN', 'BRD_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D7,BRD_GRG_DOWN', 'BRD_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D7,BRD_GRG_DOWN', 'BRD_VT07A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D7,BRD_GRG_DOWN', 'BRD_VT07B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Salidas sentido par a BLY
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U4,BRD_BLY_UP', 'BRD_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U4,BRD_BLY_UP', 'BRD_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U4,BRD_BLY_UP', 'BRD_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U4,BRD_BLY_UP', 'BRD_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U4,BRD_BLY_UP', 'BRD_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U4,BRD_BLY_UP', 'BRD_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U4,BRD_BLY_UP', 'BRD_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U10,BRD_U2', 'BRD_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U10,BRD_U2', 'BRD_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U10,BRD_U2', 'BRD_P08', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U10,BRD_U2', 'BRD_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U10,BRD_U2', 'BRD_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U10,BRD_U2', 'BRD_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U10,BRD_U2', 'BRD_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U10,BRD_U2', 'BRD_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U2,BRD_BLY_UP', 'BRD_U2', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U2,BRD_BLY_UP', 'BRD_U2', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U2,BRD_BLY_UP', 'BRD_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U12,BRD_U2', 'BRD_U12', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U12,BRD_U2', 'BRD_U12', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U12,BRD_U2', 'BRD_P06', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U12,BRD_U2', 'BRD_P08', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U12,BRD_U2', 'BRD_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U12,BRD_U2', 'BRD_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U12,BRD_U2', 'BRD_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U12,BRD_U2', 'BRD_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U12,BRD_U2', 'BRD_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U14,BRD_U2', 'BRD_U14', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U14,BRD_U2', 'BRD_U14', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U14,BRD_U2', 'BRD_P06', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U14,BRD_U2', 'BRD_P08', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U14,BRD_U2', 'BRD_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U14,BRD_U2', 'BRD_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U14,BRD_U2', 'BRD_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U14,BRD_U2', 'BRD_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_U14,BRD_U2', 'BRD_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- Entradas sentido impar a BRD
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D5', 'BRD_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D5', 'BRD_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D5', 'BRD_P11B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D5', 'BRD_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D5', 'BRD_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D5', 'BRD_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D5', 'BRD_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D3', 'BRD_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D3', 'BRD_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D3', 'BRD_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D3', 'BRD_P11B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D3', 'BRD_P10A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D3', 'BRD_P07B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D3', 'BRD_P07A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D1,BRD_D3', 'BRD_VT09', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D3,BRD_D9', 'BRD_D3', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D3,BRD_D9', 'BRD_D3', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D3,BRD_D9', 'BRD_P11B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D3,BRD_D9', 'BRD_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D3,BRD_D9', 'BRD_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D3,BRD_D9', 'BRD_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D3,BRD_D9', 'BRD_VT09', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BRD_D3,BRD_D9', 'BRD_P02A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');


