-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- AL BALYANA
-- Enclavamiento: BLY
-- Puntos de control:
-- Balyana		: BLY T05, T08
-- Balyana South: BYS T03, T06, T11, T12A
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


-- - Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'BLY','BLY','Balyana'	   ,1,NULL,'A',NULL,NULL,NULL,'S',28);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'BYS','BLY','Balyana-South',1,NULL,'A',NULL,NULL,NULL,'S',29);

-- -----------------------
-- PUNTO DE CONTROL: BYS
-- -----------------------
-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BYS','BLY_VT03','1',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BYS','BLY_VT06','2',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BYS','BLY_VT11','3',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BYS','BLY_VT12A','4',1);	


-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'BYS_VT03','BYS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BYS_VT06','BYS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BYS_VT11','BYS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BYS_VT12A','BYS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');


-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BYS_VT03','BLY_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BYS_VT06','BLY_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BYS_VT11','BLY_VT11',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BYS_VT12A','BLY_VT12A',NULL);

-- -------------------------------------------------------
-- Tramos de trayecto en sentido PAR:  SHO <-- BYS <-- BLY
-- -------------------------------------------------------

--BLY --> BYS, no se hace porque va de P.C. a P.C.

--BYS --> SHO

-- Tramos de RESET de salida

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'BYS_SHO_VT02A','BYS',NULL,NULL,NULL,NULL,'E',NULL,'SHO','2','PAR'); 

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BYS_SHO_VT02A','BLY_VT02A',NULL); 


-- Tramos de trayecto en sentido IMPAR:  SHO --> BYS --> BLY
-- ---------------------------------
--SHO --> BYS de entrada

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'SHO_BYS_VC1','SHO',NULL,NULL,NULL,NULL,'E',NULL,'BYS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA 
-- Este CV lo dice ENR 
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHO_BYS_VC1','SHO_VTA843B',NULL); 


--BYS --> BLY, no se hace porque va de P.C. a P.C.


-- -----------------------------------------------------------------------------------------------------------------------------------------


-- -----------------------
-- PUNTO DE CONTROL: BLY
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BLY','BLY_VT05','1',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('BLY','BLY_VT08','2',1);	


-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'BLY_VT05','BLY',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'BLY_VT08','BLY',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');


-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BLY_VT05','BLY_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BLY_VT08','BLY_VT08',NULL);


-- Tramos de trayecto en sentido PAR:  BYS <-- BLY <-- BRD
-- ---------------------------------
-- BRD --> BLY

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'BRD_BLY_VC2','BRD',NULL,NULL,NULL,NULL,'E',NULL,'BLY','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--Este CV lo dice ENR (Es como ADIF de Egipto) 
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BRD_BLY_VC2','BRD_VTA834B',NULL);

-- BLY a BYS no se hace porque es de P.C. a P.C.


-- Tramos de trayecto en sentido IMPAR:  BYS --> BLY --> BRD
-- ---------------------------------

-- BYS a BLY no se hace porque es de P.C. a P.C.

-- BLY --> BRD, de salida

-- Tramos de RESET

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada)
--INSERT INTO GRP_TRAMOS VALUES (1,'BLY_BRD_VT09A','BLY',NULL,NULL,NULL,NULL,'E',NULL,'BRD','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BLY_BRD_VT09A','BLY_VT09A',NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------


-- -----------------------
-- PUNTO DE CONTROL: BYS
-- -----------------------

-- Parejas de tramos en sentido par:   SHO <-- BYS <-- BLY
-- --------------------------------
-- Entradas a BYS desde BLY (P.C a P.C)

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BLY_VT08','BYS_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BLY_VT08','BYS_VT06','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BLY_VT08','BYS_VT06','C','I,BLY_U6,BLY_U4',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde BYS hacia SHO 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BYS_VT06','BYS_SHO_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BYS_VT12A','BYS_SHO_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BYS_VT06','BYS_SHO_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BYS_VT12A','BYS_SHO_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_VT06','BYS_SHO_VC2','C','I,BLY_U4,BLY_SHO_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_VT12A','BYS_SHO_VC2','C','I,BLY_U12,BLY_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_VT12A','BYS_SHO_VC2','C','I,BLY_U2,BLY_SHO_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar:   SHO --> BYS --> BLY
-- --------------------------------
-- Entradas a BYS desde SHO 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_BYS_VC1','BYS_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_BYS_VC1','BYS_VT11','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_BYS_VC1','BYS_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_BYS_VC1','BYS_VT11','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_BYS_VC1','BYS_VT03','C','I,BLY_D1,BLY_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_BYS_VC1','BYS_VT11','C','I,BLY_D1,BLY_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_BYS_VC1','BYS_VT11','C','I,BLY_D3,BLY_D11',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde BYS hacia BLY (P.C a P.C)

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BYS_VT03','BLY_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BYS_VT11','BLY_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BYS_VT03','BLY_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BYS_VT11','BLY_VT05','C',NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_VT03','BLY_VT05','C','I,BLY_D5,BLY_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_VT11','BLY_VT05','C','I,BLY_D11,BLY_D7',80,NULL,NULL,'1',NULL,NULL,NULL); 


-- -----------------------
-- PUNTO DE CONTROL: BLY
-- -----------------------


-- Parejas de tramos en sentido par:   BYS <-- BLY <-- BRD
-- --------------------------------
-- Entradas a BLY desde BRD

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BRD_BLY_VC2','BLY_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BRD_BLY_VC2','BLY_VT08','C',NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_BLY_VC2','BLY_VT08','C','I,BLY_U10,BLY_U6',80,NULL,NULL,'1',NULL,NULL,NULL); 


-- Salidas desde BLY hacia BYS -> Definidas en el sentido PAR de BYS

-- Tabla GRP_PAREJAS_TRAMOS
-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
-- Tabla GRP_PAREJAS_TRAMOS_MANDOS (U6-U4)


-- Parejas de tramos en sentido impar:   BYS --> BLY --> BRD
-- --------------------------------
-- Entradas a BLY desde BYS -> Definidas en el sentido IMPAR de BYS

-- Tabla GRP_PAREJAS_TRAMOS
-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
-- Tabla GRP_PAREJAS_TRAMOS_MANDOS (D5-D7 Y D11-D7)


-- Salidas desde BLY hacia BRD

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BLY_VT05','BLY_BRD_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BLY_VT05','BLY_BRD_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BLY_VT05','BLY_BRD_VC1','C','I,BLY_D7,BLY_BRD_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);

-- -----------------------------------------------------------------------------------------------------------------------------------------


-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).


--BYS

-- Parejas de tramos en sentido par:   SHO <-- BYS <-- BLY
-- --------------------------------
-- Entradas a BYS desde BLY

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BLY_VT08','BYS_VT06','C','I,BLY_U6,BLY_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U6,BLY_U4', 'BLY_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U6,BLY_U4', 'BLY_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U6,BLY_U4', 'BLY_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U6,BLY_U4', 'BLY_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U6,BLY_U4', 'BLY_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	

-- Salidas desde BYS hacia SHO 

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_VT06','BYS_SHO_VC2','C','I,BLY_U4,BLY_SHO_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U4,BLY_SHO_UP', 'BLY_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U4,BLY_SHO_UP', 'BLY_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U4,BLY_SHO_UP', 'BLY_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U4,BLY_SHO_UP', 'BLY_P11B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U4,BLY_SHO_UP', 'BLY_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U4,BLY_SHO_UP', 'BLY_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_VT12A','BYS_SHO_VC2','C','I,BLY_U12,BLY_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U12,BLY_U2', 'BLY_U12', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U12,BLY_U2', 'BLY_U12', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U12,BLY_U2', 'BLY_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U12,BLY_U2', 'BLY_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U12,BLY_U2', 'BLY_P11B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U12,BLY_U2', 'BLY_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_VT12A','BYS_SHO_VC2','C','I,BLY_U2,BLY_SHO_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U2,BLY_SHO_UP', 'BLY_U2', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U2,BLY_SHO_UP', 'BLY_U2', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U2,BLY_SHO_UP', 'BLY_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	

-- Parejas de tramos en sentido impar:   SHO --> BYS --> BLY
-- --------------------------------
-- Entradas a BYS desde SHO 

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_BYS_VC1','BYS_VT03','C','I,BLY_D1,BLY_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D5', 'BLY_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D5', 'BLY_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D5', 'BLY_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D5', 'BLY_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D5', 'BLY_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D5', 'BLY_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_BYS_VC1','BYS_VT11','C','I,BLY_D1,BLY_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D3', 'BLY_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D3', 'BLY_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D3', 'BLY_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D3', 'BLY_P11A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D3', 'BLY_P10B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D3', 'BLY_P10A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D1,BLY_D3', 'BLY_VT11', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');	

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_BYS_VC1','BYS_VT11','C','I,BLY_D3,BLY_D11',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D3,BLY_D11', 'BLY_D3', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D3,BLY_D11', 'BLY_D3', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D3,BLY_D11', 'BLY_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D3,BLY_D11', 'BLY_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D3,BLY_D11', 'BLY_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D3,BLY_D11', 'BLY_VT11', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


-- Salidas desde BYS hacia BLY

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_VT03','BLY_VT05','C','I,BLY_D5,BLY_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D5,BLY_D7', 'BLY_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D5,BLY_D7', 'BLY_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D5,BLY_D7', 'BLY_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D5,BLY_D7', 'BLY_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D5,BLY_D7', 'BLY_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_VT11','BLY_VT05','C','I,BLY_D11,BLY_D7',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D11,BLY_D7', 'BLY_D11', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D11,BLY_D7', 'BLY_D11', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D11,BLY_D7', 'BLY_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D11,BLY_D7', 'BLY_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D11,BLY_D7', 'BLY_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D11,BLY_D7', 'BLY_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


--BLY

-- Parejas de tramos en sentido par:   BYS <-- BLY <-- BRD
-- --------------------------------
-- Entradas a BLY desde BRD

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BRD_BLY_VC2','BLY_VT08','C','I,BLY_U10,BLY_U6',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U10,BLY_U6', 'BLY_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U10,BLY_U6', 'BLY_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U10,BLY_U6', 'BLY_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U10,BLY_U6', 'BLY_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_U10,BLY_U6', 'BLY_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- Salidas desde BLY hacia BYS (Declaradas como entradas en BYS, U6-U4)


-- Parejas de tramos en sentido impar:   BYS --> BLY --> BRD
-- --------------------------------
-- Entradas a BLY desde BYS (Declaradas como salidas en BYS, D5-D7 y D11-D7)


-- Salidas desde BLY hacia BRD

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BLY_VT05','BLY_BRD_VC1','C','I,BLY_D7,BLY_BRD_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D7,BLY_BRD_DOWN', 'BLY_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D7,BLY_BRD_DOWN', 'BLY_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D7,BLY_BRD_DOWN', 'BLY_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D7,BLY_BRD_DOWN', 'BLY_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,BLY_D7,BLY_BRD_DOWN', 'BLY_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

