-- Datos de la linea ASYUT NAGH HAMMADI 
-- Enclavamiento: ABOU_SHOUSHA (SHO) 

-- Colaterales
-- TSH: Abou Tisht (enclavamiento TSH: TSH + TSN)
-- BYS: Al Balyana (enclavamiento BLY: BYS + BLY)


-- 1. Creamos una nueva version */
-- INSERT INTO GRP_VERSIONES VALUES (1, 'SHO.2nd', 'GRP de SHO', to_date('2025-02-28 11:00:00','yyyy-mm-dd hh24:mi:ss'), to_date('2026-02-28 11:00:00','yyyy-mm-dd hh24:mi:ss'));  


-- Puntos de control: 
-- SHO: Abou Shousha

-- Tabla GRP_PUNTOS_CONTROL:
-- GRP_PUNTOS_CONTROL(ID_VERSION, ID_PUNTO_CONTROL, CODIGO_ENCLAVAMIENTO, PC_NOMBRE_MALLAS, PC_TIPO, MNEMONICO, AUTOMATICO, CAMBIO_TREN, COD_RENFE, FECHA_ULTIMO_CAMBIO_AUTOMATICO, PERMITE_CAMBIO_AUTOMATICO)
--INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'SHO','SHO','Abou Shousha',1,NULL,'A',NULL,NULL,NULL,'S',30);

-- ELEMENTOS del punto de contol
-- GRP_ELEMENTOS_PUNTOS_CONTROL(PUNTO_CONTROL, CODIGO_ELEMENTO, VIA, ID_VERSION)
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SHO','SHO_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SHO','SHO_VT06','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SHO','SHO_VT10','4',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SHO','SHO_VT12','6',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SHO','SHO_VT14','8',1);


---------------------------------------------------------------------
-- Tablas GRP_TRAMOS y GRP_REL_TRAMOS_CIRCUITOS_VIA
---------------------------------------------------------------------
-- Tramos de Estacionamiento
-- INSERT INTO GRP_TRAMOS VALUES (1,ID_TRAMO,ID_PUNTO_CONTROL,NULL,NULL,NULL,NULL,E_S,NULL,NULL,VIA,SENTIDO);
INSERT INTO GRP_TRAMOS VALUES (1,'SHO_VT03','SHO',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SHO_VT06','SHO',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SHO_VT10','SHO',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SHO_VT12','SHO',NULL,NULL,NULL,NULL,'S',NULL,NULL,'6','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SHO_VT14','SHO',NULL,NULL,NULL,NULL,'S',NULL,NULL,'8','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
-- INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,ID_TRAMO,COD_CV,NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHO_VT03','SHO_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHO_VT06','SHO_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHO_VT10','SHO_VT10',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHO_VT12','SHO_VT12',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHO_VT14','SHO_VT14',NULL);


-- Tramos de Trayecto 
-- INSERT INTO GRP_TRAMOS VALUES (1,ID_TRAMO,ID_PUNTO_CONTROL,NULL,NULL,NULL,NULL,E_S,NULL,PC_SIGUIENTE,VIA,SENTIDO);
---------------------------------------------------------------------
-- Entrada (desde BYS) en sentido PAR  via 2
--INSERT INTO GRP_TRAMOS VALUES (1,'BYS_SHO_VC2','BYS',NULL,NULL,NULL,NULL,'E',NULL,'SHO','2','PAR');

-- Entrada (desde TSH) en sentido IMPAR  via 1
--INSERT INTO GRP_TRAMOS VALUES (1,'TSH_SHO_VC1','TSH',NULL,NULL,NULL,NULL,'E',NULL,'SHO','1','IMPAR');


-- Tramos de Trayecto - CIRCUITOS_VIA 
-- INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,ID_TRAMO,COD_CV,NULL);
---------------------------------------------------------------------
-- Entrada (desde BYS) en sentido PAR
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BYS_SHO_VC2','SHO_VTA850A',NULL);

-- Entrada (desde TSH) en sentido IMPAR
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSH_SHO_VC1','SHO_VTA857A',NULL);


---------------------------------------------------------------------
-- Tramos de reset (rutas de salida)
---------------------------------------------------------------------
-- Salidas sentido PAR
-- En estos casos es el CV de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'SHO_TSH_VT02A','SHO',NULL,NULL,NULL,NULL,'E',NULL,'TSH','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHO_TSH_VT02A','SHO_VT02A',NULL);


-- Salidas sentido IMPAR
--INSERT INTO GRP_TRAMOS VALUES (1,'SHO_BYS_VT07A','SHO',NULL,NULL,NULL,NULL,'E',NULL,'BYS','1','IMPAR');

 -- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHO_BYS_VT07A','SHO_VT07A',NULL);


---------------------------------------------------------------------
-- Tablas GRP_PAREJAS_TRAMOS y GRP_PAREJAS_TRAMOS_OPERADOR
---------------------------------------------------------------------
-- Sentido PAR
-- Entradas de BYS a SHO por V2. 
-- INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,SENTIDO,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BYS_SHO_VC2','SHO_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BYS_SHO_VC2','SHO_VT10','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BYS_SHO_VC2','SHO_VT12','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BYS_SHO_VC2','SHO_VT14','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BYS_SHO_VC2','SHO_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BYS_SHO_VC2','SHO_VT10','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BYS_SHO_VC2','SHO_VT12','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BYS_SHO_VC2','SHO_VT14','C',NULL,NULL,NULL,NULL,NULL);

-- Salidas de SHO a TSH por V2. 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_VT06','SHO_TSH_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_VT10','SHO_TSH_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_VT12','SHO_TSH_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_VT14','SHO_TSH_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_VT06','SHO_TSH_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_VT10','SHO_TSH_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_VT12','SHO_TSH_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_VT14','SHO_TSH_VC2','C',NULL,NULL,NULL,NULL,NULL);


-- Sentido IMPAR
-- Entradas de TSH a SHO por V1. 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_SHO_VC1','SHO_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_SHO_VC1','SHO_VT03','C',NULL,NULL,NULL,NULL,NULL);


-- Salidas de SHO a BYS por V1. 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_VT03','SHO_BYS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_VT03','SHO_BYS_VC1','C',NULL,NULL,NULL,NULL,NULL);


---------------------------------------
-- Parejas de TRAMOS_MANDOS 
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,'C',CODIGO_MANDO,80,NULL,NULL,'1',NULL,NULL,NULL);
---------------------------------------
-- Sentido PAR 
-- Entradas de BYS a SHO por V2
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_SHO_VC2','SHO_VT06','C','I,SHO_U8,SHO_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_SHO_VC2','SHO_VT10','C','I,SHO_U6,SHO_U10',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_SHO_VC2','SHO_VT10','C','I,SHO_U8,SHO_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_SHO_VC2','SHO_VT12','C','I,SHO_U6,SHO_U12',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_SHO_VC2','SHO_VT12','C','I,SHO_U8,SHO_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_SHO_VC2','SHO_VT14','C','I,SHO_U6,SHO_U14',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BYS_SHO_VC2','SHO_VT14','C','I,SHO_U8,SHO_U6',80,NULL,NULL,'1',NULL,NULL,NULL);

-- Salida de SHO a TSH por V2
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_VT06','SHO_TSH_VC2','C','I,SHO_U4,SHO_TSH_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_VT10','SHO_TSH_VC2','C','I,SHO_U2,SHO_TSH_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_VT10','SHO_TSH_VC2','C','I,SHO_U10,SHO_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_VT12','SHO_TSH_VC2','C','I,SHO_U2,SHO_TSH_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_VT12','SHO_TSH_VC2','C','I,SHO_U12,SHO_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_VT14','SHO_TSH_VC2','C','I,SHO_U2,SHO_TSH_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_VT14','SHO_TSH_VC2','C','I,SHO_U14,SHO_U2',80,NULL,NULL,'1',NULL,NULL,NULL);

-- Sentido IMPAR
-- Entradas de TSH a SHO por V1
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_SHO_VC1','SHO_VT03','C','I,SHO_D1,SHO_D5',80,NULL,NULL,'1',NULL,NULL,NULL);

-- Salidas de SHO a BYS por V1. 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_VT03','SHO_BYS_VC1','C','I,SHO_D5,SHO_BLY_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);

------------------------------------------------------------------------------------
-- Comprobaciones asociadas a los mandos (Condiciones de envio)
-- GRP_COMPROBACIONES_MANDOS
-- (ID_VERSION, CODIGO_MANDO, CODIGO_ELEMENTO, ASPECTO, CONDICION, OPERACION_LOGICA)
--------------------------------------------------
-- Tabla GRP_COMPROBACIONES_MANDOS en sentido PAR
--------------------------------------------------
-- Entradas de BYS a SHO por V2
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U4','SHO_U8','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U4','SHO_U8','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U4','SHO_P01B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U4','SHO_P02A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U4','SHO_P03B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U4','SHO_VT08B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U4','SHO_VT06_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U4','SHO_VT06','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U10','SHO_U6', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U10','SHO_U6', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U10','SHO_P01B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U10','SHO_P02A', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U10','SHO_P03B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U10','SHO_P03A', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U10','SHO_P04',  'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U10','SHO_VT06_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U10','SHO_VT10',  'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U12','SHO_U6', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U12','SHO_U6', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U12','SHO_P01B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U12','SHO_P02A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U12','SHO_P03B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U12','SHO_P03A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U12','SHO_P04', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U12','SHO_P05', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U12','SHO_VT06_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U12','SHO_VT12',  'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U14','SHO_U6', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U14','SHO_U6', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U14','SHO_P01B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U14','SHO_P02A', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U14','SHO_P03B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U14','SHO_P03A', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U14','SHO_P04',  'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U14','SHO_P05',  'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U14','SHO_VT06_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U6,SHO_U14','SHO_VT14',  'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U6','SHO_U8', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U6','SHO_U8', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U6','SHO_VT08B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U6','SHO_P01B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U6','SHO_P02A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U6','SHO_P03B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U6','SHO_P03A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U6','SHO_P04', 'AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U8,SHO_U6','SHO_VT06_I','CV.NOR.ITG.ITI','E','LIBRERIA_AND');


-- Salidas de SHO a TSH por V2
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U4,SHO_TSH_UP','SHO_U4', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U4,SHO_TSH_UP','SHO_U4', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U4,SHO_TSH_UP','SHO_P08B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U4,SHO_TSH_UP','SHO_P09A', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U4,SHO_TSH_UP','SHO_VT04', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U4,SHO_TSH_UP','SHO_VT02A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U10,SHO_U2', 'SHO_U10', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U10,SHO_U2', 'SHO_U10', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U10,SHO_U2', 'SHO_P07B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U10,SHO_U2', 'SHO_P08A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U10,SHO_U2', 'SHO_P08B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U10,SHO_U2', 'SHO_P09A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U10,SHO_U2', 'SHO_VT04','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U10,SHO_U2', 'SHO_VT02A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U12,SHO_U2', 'SHO_U12', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U12,SHO_U2', 'SHO_U12', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U12,SHO_U2', 'SHO_P06','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U12,SHO_U2', 'SHO_P07A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U12,SHO_U2', 'SHO_P07B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U12,SHO_U2', 'SHO_P08A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U12,SHO_U2', 'SHO_P08B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U12,SHO_U2', 'SHO_P09A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U12,SHO_U2', 'SHO_VT04','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U12,SHO_U2', 'SHO_VT02A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U14,SHO_U2', 'SHO_U14', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U14,SHO_U2', 'SHO_U14', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U14,SHO_U2', 'SHO_P06','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U14,SHO_U2', 'SHO_P07A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U14,SHO_U2', 'SHO_P07B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U14,SHO_U2', 'SHO_P08A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U14,SHO_U2', 'SHO_P08B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U14,SHO_U2', 'SHO_P09A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U14,SHO_U2', 'SHO_VT04','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U14,SHO_U2', 'SHO_VT02A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U2,SHO_TSH_UP','SHO_U2', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U2,SHO_TSH_UP','SHO_U2', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U2,SHO_TSH_UP','SHO_VT02A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U2,SHO_TSH_UP','SHO_VT04','CV.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U2,SHO_TSH_UP','SHO_P09A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U2,SHO_TSH_UP','SHO_P08B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_U2,SHO_TSH_UP','SHO_P08A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');


--------------------------------------------------
-- Tabla GRP_COMPROBACIONES_MANDOS en sentido IMPAR
--------------------------------------------------
-- Entradas de TSH a SHO por V1
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D1,SHO_D5','SHO_D1', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D1,SHO_D5','SHO_D1', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D1,SHO_D5','SHO_P09B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D1,SHO_D5','SHO_VT01B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D1,SHO_D5','SHO_VT03', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

--------------------------------------------------------------------------------------

-- Salidas de SHO a BYS por V1
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D5,SHO_BLY_DOWN','SHO_D5', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D5,SHO_BLY_DOWN','SHO_D5', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D5,SHO_BLY_DOWN','SHO_P02B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D5,SHO_BLY_DOWN','SHO_P01A', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D5,SHO_BLY_DOWN','SHO_VT05_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D5,SHO_BLY_DOWN','SHO_VT05',	'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,SHO_D5,SHO_BLY_DOWN','SHO_VT07A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

--------------------------------------------------------------------------------------
