--TRAMOS
-- Entrada (desde TSH) en sentido IMPAR  via 1
INSERT INTO GRP_TRAMOS VALUES (1,'TSH_SHO_VC2','TSH',NULL,NULL,NULL,NULL,'E',NULL,'SHO','1','IMPAR');
-- Entrada (desde TSH) en sentido IMPAR
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSH_SHO_VC2','SHO_VTA864B',NULL);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'SHO_TSH_VC1','SHO',NULL,NULL,NULL,NULL,'E',NULL,'TSH','2','PAR');
-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHO_TSH_VC1','TSH_VTA859B',NULL);



-- -----------------------
-- PUNTO DE CONTROL: TSH
-- -----------------------
-- Parejas de tramos en sentido par   TSS <-- TSH <-- SHO
-- --------------------------------
-- Entradas a TSH desde SHO

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_TSH_VC1','TSH_VT15','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_TSH_VC1','TSH_VT13','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_TSH_VC1','TSH_VT05','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_TSH_VC1','TSH_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_TSH_VC1','TSH_VT15','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_TSH_VC1','TSH_VT13','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_TSH_VC1','TSH_VT05','C',NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_TSH_VC1','TSH_VT08','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_TSH_VC1','TSH_VT15','C','I,TSH_D9CF,TSH_D7CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_TSH_VC1','TSH_VT15','C','I,TSH_D7CF,TSH_D15CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_TSH_VC1','TSH_VT13','C','I,TSH_D9CF,TSH_D7CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_TSH_VC1','TSH_VT13','C','I,TSH_D7CF,TSH_D13CF',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_TSH_VC1','TSH_VT05','C','I,TSH_D9CF,TSH_D5CF',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_TSH_VC1','TSH_VT08','C','I,TSH_D9CF,TSH_D7CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_TSH_VC1','TSH_VT08','C','I,TSH_D7CF,TSH_U6',80,NULL,NULL,'1',NULL,NULL,NULL);



-- PUNTO DE CONTROL: TSS
-- -----------------------
-- Parejas de tramos en sentido par   FAR <-- TSS <-- TSH
-- Entradas a TSS desde TSH (P.C.)
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT15','TSS_FAN_VC1','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT15','TSS_FAN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT05','TSS_VT11','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT05','TSS_VT03','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT05','TSS_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT05','TSS_VT12','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT13','TSS_VT11','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT13','TSS_VT03','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT13','TSS_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT13','TSS_VT12','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT15','TSS_FAN_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT15','TSS_FAN_VC2','C',NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT05','TSS_VT11','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT05','TSS_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT05','TSS_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT05','TSS_VT12','C',NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT13','TSS_VT11','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT13','TSS_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT13','TSS_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT13','TSS_VT12','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT15','TSS_FAN_VC1','C','I,TSH_D15CF,TSH_D1CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT15','TSS_FAN_VC1','C','I,TSH_D1CF,TSS_FAN_VC1',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT15','TSS_FAN_VC2','C','I,TSH_D15CF,TSH_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT15','TSS_FAN_VC2','C','I,TSH_U2,TSS_FAN_VC2',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT05','TSS_VT11','C','I,TSH_D5CF,TSH_D11CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT05','TSS_VT03','C','I,TSH_D5CF,TSH_D3CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT05','TSS_VT06','C','I,TSH_D5CF,TSH_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT05','TSS_VT12','C','I,TSH_D5CF,TSH_U12',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT13','TSS_VT11','C','I,TSH_D13CF,TSH_D11CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT13','TSS_VT03','C','I,TSH_D13CF,TSH_D3CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT13','TSS_VT06','C','I,TSH_D13CF,TSH_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT13','TSS_VT12','C','I,TSH_D13CF,TSH_U12',80,NULL,NULL,'1',NULL,NULL,NULL);








-- Salidas desde TSS hacia FAN
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT06','TSS_FAN_VC1','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT12','TSS_FAN_VC1','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT11','TSS_FAN_VC1','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT11','TSS_FAN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT03','TSS_FAN_VC1','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT03','TSS_FAN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT06','TSS_FAN_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT12','TSS_FAN_VC1','C',NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT11','TSS_FAN_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT11','TSS_FAN_VC2','C',NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT03','TSS_FAN_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT03','TSS_FAN_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT06','TSS_FAN_VC1','C','I,TSH_U4,TSH_D1CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT06','TSS_FAN_VC1','C','I,TSH_D1CF,TSH_FAR_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT12','TSS_FAN_VC1','C','I,TSH_U12,TSH_D1CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT12','TSS_FAN_VC1','C','I,TSH_D1CF,TSH_FAR_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT11','TSS_FAN_VC1','C','I,TSH_D11CF,TSH_D1CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT11','TSS_FAN_VC1','C','I,TSH_D1CF,TSH_FAR_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT11','TSS_FAN_VC2','C','I,TSH_D11CF,TSH_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT11','TSS_FAN_VC2','C','I,TSH_U2,TSH_FAR_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT03','TSS_FAN_VC1','C','I,TSH_D3CF,TSH_FAR_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT03','TSS_FAN_VC2','C','I,TSH_D3CF,TSH_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT03','TSS_FAN_VC2','C','I,TSH_U2,TSH_FAR_UP',80,NULL,NULL,'1',NULL,NULL,NULL);






-- Parejas de tramos en sentido impar  FAR --> TSS --> TSH --> SHO  
-- --------------------------------
-- Entradas a TSS desde FAR
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_TSS_VC1','TSS_VT06','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_TSS_VC1','TSS_VT12','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 


INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_TSS_VC2','TSS_VT15','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_TSS_VC2','TSS_VT11','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_TSS_VC2','TSS_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_TSS_VC2','TSS_VT06','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_TSS_VC2','TSS_VT12','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 



-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_TSS_VC1','TSS_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_TSS_VC1','TSS_VT12','C',NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_TSS_VC2','TSS_VT15','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_TSS_VC2','TSS_VT11','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_TSS_VC2','TSS_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_TSS_VC2','TSS_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_TSS_VC2','TSS_VT12','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC1','TSS_VT06','C','I,TSH_D1,TSH_U4CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC1','TSS_VT06','C','I,TSH_U4CF,TSH_U6CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC1','TSS_VT12','C','I,TSH_D1,TSH_U4CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC1','TSS_VT12','C','I,TSH_U4CF,TSH_U12CF',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC2','TSS_VT15','C','I,TSH_U2CF,TSH_U4CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC2','TSS_VT15','C','I,TSH_U4CF,TSH_D15',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC2','TSS_VT11','C','I,TSH_U2CF,TSH_U4CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC2','TSS_VT11','C','I,TSH_U4CF,TSH_D11',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC2','TSS_VT03','C','I,TSH_U2CF,TSH_U4CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC2','TSS_VT03','C','I,TSH_U4CF,TSH_D5',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC2','TSS_VT06','C','I,TSH_U2CF,TSH_U6CF',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC2','TSS_VT12','C','I,TSH_U2CF,TSH_U4CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC2','TSS_VT12','C','I,TSH_U4CF,TSH_U12CF',80,NULL,NULL,'1',NULL,NULL,NULL);






-- Salidas desde TSS hacia TSH
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT06','TSH_VT13','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT06','TSH_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT06','TSH_VT08','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT12','TSH_VT13','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT12','TSH_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT12','TSH_VT08','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT06','TSH_VT13','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT06','TSH_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT06','TSH_VT08','C',NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT12','TSH_VT13','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT12','TSH_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT12','TSH_VT08','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT06','TSH_VT13','C','I,TSH_U6CF,TSH_D13',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT06','TSH_VT05','C','I,TSH_U6CF,TSH_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT06','TSH_VT08','C','I,TSH_U6CF,TSH_U8CF',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT12','TSH_VT13','C','I,TSH_U12CF,TSH_D13',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT12','TSH_VT05','C','I,TSH_U12CF,TSH_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT12','TSH_VT08','C','I,TSH_U12CF,TSH_U8CF',80,NULL,NULL,'1',NULL,NULL,NULL);





-- Parejas de tramos en sentido impar  TSS --> TSH --> SHO
-- --------------------------------
-- Entradas a TSH desde TSS -> Definidas en las salidas de TSS
-- Salidas desde TSH hacia SHO
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT15','TSH_SHO_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT13','TSH_SHO_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT05','TSH_SHO_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT08','TSH_SHO_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT08','TSH_SHO_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT15','TSH_SHO_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT13','TSH_SHO_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT05','TSH_SHO_VC2','C',NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT08','TSH_SHO_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT08','TSH_SHO_VC2','C',NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT15','TSH_SHO_VC2','C','I,TSH_D7,TSH_U10CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT15','TSH_SHO_VC2','C','I,TSH_U10CF,TSH_SHO_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT13','TSH_SHO_VC2','C','I,TSH_D13,TSH_U10CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT13','TSH_SHO_VC2','C','I,TSH_U10CF,TSH_SHO_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT05','TSH_SHO_VC2','C','I,TSH_D7,TSH_U10CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT05','TSH_SHO_VC2','C','I,TSH_U10CF,TSH_SHO_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT08','TSH_SHO_VC1','C','I,TSH_U8CF,TSH_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT08','TSH_SHO_VC1','C','I,TSH_D9,TSH_SHO_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT08','TSH_SHO_VC2','C','I,TSH_U8CF,TSH_SHO_UP',80,NULL,NULL,'1',NULL,NULL,NULL);




-- -----------------------------------------------------------------------------------------------------------------------------------------

-- Tabla GRP_COMPROBACIONES_MANDOS

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D15CF', 'TSH_D7CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D15CF', 'TSH_D7CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D15CF', 'TSH_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D15CF', 'TSH_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D15CF', 'TSH_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D15CF', 'TSH_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D15CF', 'TSH_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D15CF', 'TSH_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D15CF', 'TSH_P0AB', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D15CF', 'TSH_VT15', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D13CF', 'TSH_D7CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D13CF', 'TSH_D7CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D13CF', 'TSH_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D13CF', 'TSH_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D13CF', 'TSH_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D13CF', 'TSH_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D13CF', 'TSH_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D13CF', 'TSH_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_D13CF', 'TSH_VT13', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D5CF', 'TSH_D9CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D5CF', 'TSH_D9CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D5CF', 'TSH_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D5CF', 'TSH_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D5CF', 'TSH_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D5CF', 'TSH_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D5CF', 'TSH_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D5CF', 'TSH_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D7CF', 'TSH_D9CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D7CF', 'TSH_D9CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D7CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9CF,TSH_D7CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_U6', 'TSH_D7CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_U6', 'TSH_D7CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_U6', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7CF,TSH_U6', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15CF,TSH_D1CF', 'TSH_D15CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15CF,TSH_D1CF', 'TSH_D15CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15CF,TSH_D1CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15CF,TSH_D1CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1CF,TSS_FAN_VC1', 'TSH_D1CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1CF,TSS_FAN_VC1', 'TSH_D1CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1CF,TSS_FAN_VC1', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1CF,TSS_FAN_VC1', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15CF,TSH_U2', 'TSH_D15CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15CF,TSH_U2', 'TSH_D15CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15CF,TSH_U2', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15CF,TSH_U2', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSS_FAN_VC2', 'TSH_U2', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSS_FAN_VC2', 'TSH_U2', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSS_FAN_VC2', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSS_FAN_VC2', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_D11CF', 'TSH_D5CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_D11CF', 'TSH_D5CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_D11CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_D11CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_D3CF', 'TSH_D5CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_D3CF', 'TSH_D5CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_D3CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_D3CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_U4', 'TSH_D5CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_U4', 'TSH_D5CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_U4', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_U4', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_U12', 'TSH_D5CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_U12', 'TSH_D5CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_U12', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5CF,TSH_U12', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_D11CF', 'TSH_D13CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_D11CF', 'TSH_D13CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_D11CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_D11CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_D3CF', 'TSH_D13CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_D3CF', 'TSH_D13CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_D3CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_D3CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_U4', 'TSH_D13CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_U4', 'TSH_D13CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_U4', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_U4', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_U12', 'TSH_D13CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_U12', 'TSH_D13CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_U12', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13CF,TSH_U12', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_D1CF', 'TSH_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_D1CF', 'TSH_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_D1CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_D1CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12,TSH_D1CF', 'TSH_U12', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12,TSH_D1CF', 'TSH_U12', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12,TSH_D1CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12,TSH_D1CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11CF,TSH_D1CF', 'TSH_D11CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11CF,TSH_D1CF', 'TSH_D11CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11CF,TSH_D1CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11CF,TSH_D1CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11CF,TSH_U2', 'TSH_D11CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11CF,TSH_U2', 'TSH_D11CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11CF,TSH_U2', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11CF,TSH_U2', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSH_FAR_UP', 'TSH_U2', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSH_FAR_UP', 'TSH_U2', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSH_FAR_UP', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSH_FAR_UP', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3CF,TSH_FAR_DOWN', 'TSH_D3CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3CF,TSH_FAR_DOWN', 'TSH_D3CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3CF,TSH_FAR_DOWN', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3CF,TSH_FAR_DOWN', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3CF,TSH_U2', 'TSH_D3CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3CF,TSH_U2', 'TSH_D3CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3CF,TSH_U2', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3CF,TSH_U2', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_U4CF', 'TSH_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_U4CF', 'TSH_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_U4CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_U4CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_U6CF', 'TSH_U4CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_U6CF', 'TSH_U4CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_U6CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_U6CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_U12CF', 'TSH_U4CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_U12CF', 'TSH_U4CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_U12CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_U12CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D15', 'TSH_U4CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D15', 'TSH_U4CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D15', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D15', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D11', 'TSH_U4CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D11', 'TSH_U4CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D11', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D11', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D5', 'TSH_U4CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D5', 'TSH_U4CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D5', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4CF,TSH_D5', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2CF,TSH_U6CF', 'TSH_U2CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2CF,TSH_U6CF', 'TSH_U2CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2CF,TSH_U6CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2CF,TSH_U6CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2CF,TSH_U4CF', 'TSH_U2CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2CF,TSH_U4CF', 'TSH_U2CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2CF,TSH_U4CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2CF,TSH_U4CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_D13', 'TSH_U6CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_D13', 'TSH_U6CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_D13', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_D13', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_D7', 'TSH_U6CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_D7', 'TSH_U6CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_D7', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_D7', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_U8CF', 'TSH_U6CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_U8CF', 'TSH_U6CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_U8CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6CF,TSH_U8CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_D13', 'TSH_U12CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_D13', 'TSH_U12CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_D13', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_D13', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_D7', 'TSH_U12CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_D7', 'TSH_U12CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_D7', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_D7', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_U8CF', 'TSH_U12CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_U8CF', 'TSH_U12CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_U8CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12CF,TSH_U8CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_U10CF', 'TSH_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_U10CF', 'TSH_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_U10CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_U10CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9,TSH_SHO_UP', 'TSH_D9', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9,TSH_SHO_UP', 'TSH_D9', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9,TSH_SHO_UP', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9,TSH_SHO_UP', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_U10CF', 'TSH_D13', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_U10CF', 'TSH_D13', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_U10CF', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_U10CF', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U8CF,TSH_D9', 'TSH_U8CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U8CF,TSH_D9', 'TSH_U8CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U8CF,TSH_D9', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U8CF,TSH_D9', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U8CF,TSH_SHO_UP', 'TSH_U8CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U8CF,TSH_SHO_UP', 'TSH_U8CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U8CF,TSH_SHO_UP', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U8CF,TSH_SHO_UP', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10CF,TSH_SHO_UP', 'TSH_U10CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10CF,TSH_SHO_UP', 'TSH_U10CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10CF,TSH_SHO_UP', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10CF,TSH_SHO_UP', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

