-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Abou Tisht
-- Enclavamiento: TSH
-- Puntos de control:
-- Abou Tish 	   : TSH	T05, T08 y T13
-- Abou Tisht-South: TSS	T03, T06, T11, T12 Y T15
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


-- - Tabla GRP_PUNTOS_CONTROL:
-- GRP_PUNTOS_CONTROL(ID_VERSION, ID_PUNTO_CONTROL, CODIGO_ENCLAVAMIENTO, PC_NOMBRE_MALLAS, PC_TIPO, MNEMONICO, AUTOMATICO, CAMBIO_TREN, COD_RENFE, FECHA_ULTIMO_CAMBIO_AUTOMATICO, PERMITE_CAMBIO_AUTOMATICO)
--INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'TSH','TSH','Abou Tisht',		1,NULL,'A',NULL,NULL,NULL,'S',31);
--INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'TSS','TSH','Abou Tisht-South',1,NULL,'A',NULL,NULL,NULL,'S',32);


-- -----------------------
-- PUNTO DE CONTROL: TSS
-- -----------------------
-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TSS','TSH_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TSS','TSH_VT06','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TSS','TSH_VT11','3',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TSS','TSH_VT12','4',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TSS','TSH_VT15','5',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'TSS_VT03','TSS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TSS_VT06','TSS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TSS_VT11','TSS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TSS_VT12','TSS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TSS_VT15','TSS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'5','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSS_VT03','TSH_VT03',NULL); 
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSS_VT06','TSH_VT06',NULL); 
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSS_VT11','TSH_VT11',NULL); 
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSS_VT12','TSH_VT12',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSS_VT15','TSH_VT15',NULL);

-- -------------------------


-- Tramos de trayecto en sentido par    FAN <-- TSS <-- TSH	<--	SHO
-- ---------------------------------

-- TSS --> FAN de salida
-- Tramos de reset

-- Tabla GRP_TRAMOS
-- CV de reset para la salida
--INSERT INTO GRP_TRAMOS VALUES (1,'TSS_FAN_VT02_I','TSS',NULL,NULL,NULL,NULL,'E',NULL,'FAN','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSS_FAN_VT02_I','TSH_VT02_I',NULL);


-- Tramos de trayecto en sentido impar    FAN --> TSS --> TSH	-->	SHO 
-- ---------------------------------

-- Tabla GRP_TRAMOS 
--INSERT INTO GRP_TRAMOS VALUES (1,'FAN_TSS_VC1','FAN',NULL,NULL,NULL,NULL,'E',NULL,'TSS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
-- Este CV lo dice ENR (Puede variar)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAN_TSS_VC1','TSH_VTA873B',NULL);


-- TSS a TSH no se hace porque es de P.C. a P.C.


-- -----------------------
-- PUNTO DE CONTROL: TSH
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------
-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TSH','TSH_VT05','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TSH','TSH_VT08','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TSH','TSH_VT13','3',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'TSH_VT05','TSH',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TSH_VT08','TSH',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TSH_VT13','TSH',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSH_VT05','TSH_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSH_VT08','TSH_VT08',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSH_VT13','TSH_VT13',NULL);


-- -------------------------


-- Tramos de trayecto en sentido par    TSS <-- TSH <-- SHO
-- ---------------------------------
-- SHO --> TSH
-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'SHO_TSH_VC2','SHO',NULL,NULL,NULL,NULL,'E',NULL,'TSH','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
-- Este CV lo dice ENR (Puede variar)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHO_TSH_VC2','TSH_VTA866B',NULL);

-- Tramos de reset (Al ser de entrada NO es necesario)
-- TSH a TSS no se hace porque es de P.C. a P.C.


-- Tramos de trayecto en sentido impar    TSS --> TSH --> SHO
-- ---------------------------------
-- TSS a TSH no se hace porque es de P.C. a P.C.
-- TSH --> SHO

-- -- Tramos de reset
-- Tabla GRP_TRAMOS
-- En estos casos es el CV de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'TSH_SHO_VT09A','TSH',NULL,NULL,NULL,NULL,'E',NULL,'SHO','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSH_SHO_VT09A','TSH_VT09A',NULL);

-- -----------------------------------------------------------------------------------------------------------------------------------------

-- -----------------------
-- PUNTO DE CONTROL: TSS
-- -----------------------
-- Parejas de tramos en sentido par   FAR <-- TSS <-- TSH
-- --------------------------------
-- Entradas a TSS desde TSH (P.C.)
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT08','TSS_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT08','TSS_VT12','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT08','TSS_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT08','TSS_VT12','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT08','TSS_VT06','C','I,TSH_U6,TSH_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT08','TSS_VT12','C','I,TSH_U6,TSH_U12',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde TSS hacia FAN
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT06','TSS_FAN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT12','TSS_FAN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT06','TSS_FAN_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT12','TSS_FAN_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT06','TSS_FAN_VC2','C','I,TSH_U4,TSH_FAR_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT12','TSS_FAN_VC2','C','I,TSH_U12,TSH_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT12','TSS_FAN_VC2','C','I,TSH_U2,TSH_FAR_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar  FAR --> TSS --> TSH --> SHO  
-- --------------------------------
-- Entradas a TSS desde FAR
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_TSS_VC1','TSS_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_TSS_VC1','TSS_VT11','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_TSS_VC1','TSS_VT15','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_TSS_VC1','TSS_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_TSS_VC1','TSS_VT11','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_TSS_VC1','TSS_VT15','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC1','TSS_VT03','C','I,TSH_D1,TSH_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC1','TSS_VT11','C','I,TSH_D1,TSH_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC1','TSS_VT11','C','I,TSH_D3,TSH_D11',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC1','TSS_VT15','C','I,TSH_D1,TSH_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_TSS_VC1','TSS_VT15','C','I,TSH_D3,TSH_D15',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde TSS hacia TSH
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT03','TSH_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT03','TSH_VT13','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT11','TSH_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT11','TSH_VT13','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT03','TSH_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT03','TSH_VT13','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT11','TSH_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT11','TSH_VT13','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT03','TSH_VT05','C','I,TSH_D5,TSH_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT03','TSH_VT13','C','I,TSH_D5,TSH_D13',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT11','TSH_VT05','C','I,TSH_D11,TSH_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT11','TSH_VT13','C','I,TSH_D11,TSH_D13',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------

-- -----------------------
-- PUNTO DE CONTROL: TSH
-- -----------------------
-- Parejas de tramos en sentido par   TSS <-- TSH <-- SHO
-- --------------------------------
-- Entradas a TSH desde SHO

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHO_TSH_VC2','TSH_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHO_TSH_VC2','TSH_VT08','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHO_TSH_VC2','TSH_VT08','C','I,TSH_U10,TSH_U6',80,NULL,NULL,'1',NULL,NULL,NULL);

-- Salidas desde TSH hacia TSS -> Definidas en TSS



-- Parejas de tramos en sentido impar  TSS --> TSH --> SHO
-- --------------------------------
-- Entradas a TSH desde TSS -> Definidas en las salidas de TSS


-- Salidas desde TSH hacia SHO
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT05','TSH_SHO_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSH_VT13','TSH_SHO_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
-- Falta meter la parte e TSS que sale de T15, propongo solucion crear el tramo TSH_VT15 vinculado al CV con el mismo nombre
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_VT15','TSH_SHO_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT05','TSH_SHO_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSH_VT13','TSH_SHO_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_VT15','TSH_SHO_VC1','C',NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT05','TSH_SHO_VC1','C','I,TSH_D7,TSH_SHO_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT13','TSH_SHO_VC1','C','I,TSH_D13,TSH_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSH_VT13','TSH_SHO_VC1','C','I,TSH_D9,TSH_SHO_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT15','TSH_SHO_VC1','C','I,TSH_D15,TSH_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_VT15','TSH_SHO_VC1','C','I,TSH_D9,TSH_SHO_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);

-- -----------------------------------------------------------------------------------------------------------------------------------------

-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).

-- Entradas sentido par
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10,TSH_U6', 'TSH_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10,TSH_U6', 'TSH_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10,TSH_U6', 'TSH_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10,TSH_U6', 'TSH_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10,TSH_U6', 'TSH_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10,TSH_U6', 'TSH_VT08_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10,TSH_U6', 'TSH_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U10,TSH_U6', 'TSH_P06B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U12', 'TSH_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U12', 'TSH_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U12', 'TSH_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U12', 'TSH_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U12', 'TSH_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U12', 'TSH_VT12', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U4', 'TSH_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U4', 'TSH_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U4', 'TSH_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U4', 'TSH_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U6,TSH_U4', 'TSH_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Salidas sentido par
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_FAR_UP', 'TSH_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_FAR_UP', 'TSH_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_FAR_UP', 'TSH_P11B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_FAR_UP', 'TSH_P12B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_FAR_UP', 'TSH_P13A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_FAR_UP', 'TSH_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_FAR_UP', 'TSH_VT02_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U4,TSH_FAR_UP', 'TSH_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12,TSH_U2', 'TSH_U12', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12,TSH_U2', 'TSH_U12', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12,TSH_U2', 'TSH_P12A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12,TSH_U2', 'TSH_P12B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12,TSH_U2', 'TSH_P13A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U12,TSH_U2', 'TSH_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSH_FAR_UP', 'TSH_U2', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSH_FAR_UP', 'TSH_U2', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSH_FAR_UP', 'TSH_VT02_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_U2,TSH_FAR_UP', 'TSH_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Entradas sentido impar
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D5', 'TSH_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D5', 'TSH_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D5', 'TSH_P13B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D5', 'TSH_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D5', 'TSH_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D5', 'TSH_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D5', 'TSH_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D5', 'TSH_P08A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D3', 'TSH_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D3', 'TSH_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D3', 'TSH_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D3', 'TSH_P13B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D3', 'TSH_P11A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D3', 'TSH_P10B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D3', 'TSH_P10A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D1,TSH_D3', 'TSH_P09B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D15', 'TSH_D3', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D15', 'TSH_D3', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D15', 'TSH_P13B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D15', 'TSH_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D15', 'TSH_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D15', 'TSH_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D15', 'TSH_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D15', 'TSH_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D15', 'TSH_VT15', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D11', 'TSH_D3', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D11', 'TSH_D3', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D11', 'TSH_P13B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D11', 'TSH_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D11', 'TSH_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D11', 'TSH_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D11', 'TSH_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D3,TSH_D11', 'TSH_VT11', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Salidas sentido impar
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D7', 'TSH_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D7', 'TSH_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D7', 'TSH_P08A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D7', 'TSH_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D7', 'TSH_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D7', 'TSH_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D13', 'TSH_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D13', 'TSH_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D13', 'TSH_P08A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D13', 'TSH_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D13', 'TSH_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D13', 'TSH_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D5,TSH_D13', 'TSH_VT13', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D7', 'TSH_D11', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D7', 'TSH_D11', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D7', 'TSH_P08B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D7', 'TSH_P08A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D7', 'TSH_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D7', 'TSH_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D7', 'TSH_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D13', 'TSH_D11', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D13', 'TSH_D11', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D13', 'TSH_P08B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D13', 'TSH_P08A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D13', 'TSH_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D11,TSH_D13', 'TSH_VT13', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_SHO_DOWN', 'TSH_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_SHO_DOWN', 'TSH_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_SHO_DOWN', 'TSH_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_SHO_DOWN', 'TSH_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_SHO_DOWN', 'TSH_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_SHO_DOWN', 'TSH_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_SHO_DOWN', 'TSH_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D7,TSH_SHO_DOWN', 'TSH_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_D9', 'TSH_D13', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_D9', 'TSH_D13', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_D9', 'TSH_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_D9', 'TSH_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_D9', 'TSH_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_D9', 'TSH_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_D9', 'TSH_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_D9', 'TSH_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D13,TSH_D9', 'TSH_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15,TSH_D9', 'TSH_D15', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15,TSH_D9', 'TSH_D15', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15,TSH_D9', 'TSH_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15,TSH_D9', 'TSH_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15,TSH_D9', 'TSH_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15,TSH_D9', 'TSH_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15,TSH_D9', 'TSH_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15,TSH_D9', 'TSH_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15,TSH_D9', 'TSH_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D15,TSH_D9', 'TSH_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9,TSH_SHO_DOWN', 'TSH_D9', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9,TSH_SHO_DOWN', 'TSH_D9', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TSH_D9,TSH_SHO_DOWN', 'TSH_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
