qlp-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- FARSHOUT
-- Enclavamiento: FAR
-- Puntos de control:
-- FARSHOUT: 		FAR T05C, T08, T14
-- FARSHOUT NORTH:	FAN T07,  T10, T13, T18
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


-- Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'FAN','FAR','Farshout-North',1,NULL,'A',NULL,NULL,NULL,'S',33);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'FAR','FAR','Farshout',1,NULL,'A',NULL,NULL,NULL,'S',34);

-- -----------------------
-- PUNTO DE CONTROL: FAR
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('FAR','FAR_VT05C','1',1); 
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('FAR','FAR_VT08','2',1); 
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('FAR','FAR_VT14','4',1); 


-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'FAR_VT05C','FAR',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'FAR_VT08','FAR',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'FAR_VT14','FAR',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');


-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAR_VT05C','FAR_VT05C',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAR_VT08','FAR_VT08',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAR_VT14','FAR_VT14',NULL);

-- -------------------------

-- -------------------------

-- Tramos de trayecto en sentido PAR:  NGH <-- FAR <-- FAN
-- ---------------------------------
--FAN --> FAR, no se hace porque va de P.C. a P.C.

--FAR --> NGH, (Se haría si formara parte del proyecto)

-- Tramos de RESET de salida

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada
-- INSERT INTO GRP_TRAMOS VALUES (1,'FAR_NGH_VT02A','FAR',NULL,NULL,NULL,NULL,'E',NULL,'NGH','2','PAR'); 

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
-- INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAR_NGH_VT02A','FAR_VT02A',NULL); 


-- Tramos de trayecto en sentido IMPAR:  NGH --> FAR --> FAN
-- ---------------------------------
--NGH --> FAR, NO se puede porque no forma parte del proyecto

--Se hacen las 2 primeras tablas porque es de ENTRADA
-- Tabla GRP_TRAMOS
-- INSERT INTO GRP_TRAMOS VALUES (1,'NGH_FAR_VC1','NGH',NULL,NULL,NULL,NULL,'E',NULL,'FAR','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA 
-- Este CV lo dice ENR 
-- INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'NGH_FAR_VTA889B','FAR_VTA889B',NULL); 

--FAR --> FAN, no se hace porque va de P.C. a P.C.

-- -----------------------
-- PUNTO DE CONTROL: FAN
-- -----------------------
-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('FAN','FAR_VT07','1',1); 
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('FAN','FAR_VT10','2',1); 
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('FAN','FAR_VT13','3',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('FAN','FAR_VT18','4',1); 

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'FAN_VT07','FAN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'FAN_VT10','FAN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'FAN_VT13','FAN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'FAN_VT18','FAN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAN_VT07','FAR_VT07',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAN_VT10','FAR_VT10',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAN_VT13','FAR_VT13',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAN_VT18','FAR_VT18',NULL);

-- -------------------------


-- Tramos de trayecto en sentido PAR:  FAR <-- FAN <-- TSS
-- ---------------------------------

-- TSS --> FAN

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'TSS_FAN_VC2','TSS',NULL,NULL,NULL,NULL,'E',NULL,'FAN','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--Este CV lo dice ENR (Es como ADIF de Egipto) 
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSS_FAN_VC2','FAR_VTA882B',NULL);

-- Tramos de RESET (Al ser de entrada NO es necesario)

-- FAN a FAR no se hace porque es de P.C. a P.C.


-- Tramos de trayecto en sentido IMPAR:  FAR --> FAN --> TSS
-- ---------------------------------

-- FAR a FAN no se hace porque es de P.C. a P.C.

-- FAN --> TSS

-- Tabla GRP_TRAMOS

--INSERT INTO GRP_TRAMOS VALUES (1,'FAN_TSS_VT07','FAN',NULL,NULL,NULL,NULL,'E',NULL,'TSS','1','IMPAR');

-- -- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
-- --Este CV lo dice ENR (Es como ADIF de Egipto)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAN_TSS_VT07','FAR_VT07',NULL); 

-- Tramos de RESET

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada)
--INSERT INTO GRP_TRAMOS VALUES (1,'FAN_TSS_VT11A','FAN',NULL,NULL,NULL,NULL,'E',NULL,'TSS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAN_TSS_VT11A','FAR_VT11A',NULL);

-- -----------------------------------------------------------------------------------------------------------------------------------------

-- -----------------------
-- PUNTO DE CONTROL: FAR
-- -----------------------

-- Parejas de tramos en sentido par:   NGH <-- FAR <-- FAN
-- --------------------------------
-- Entradas a FAR desde FAN (P.C a P.C)

-- Tabla GRP_PAREJAS_TRAMOS
--No se hacen las rutas a CF
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT10','FAR_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT10','FAR_VT14','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT18','FAR_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT18','FAR_VT14','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT10','FAR_VT08','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT10','FAR_VT14','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT18','FAR_VT08','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT18','FAR_VT14','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT10','FAR_VT08','C','I,FAR_U8,FAR_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT10','FAR_VT14','C','I,FAR_U8,FAR_U14',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT18','FAR_VT08','C','I,FAR_U18,FAR_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT18','FAR_VT14','C','I,FAR_U18,FAR_U14',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde FAR hacia NGH 
--(LA ESTACION NGH NO FORMA PARTE DEL PROYECTO)



-- Parejas de tramos en sentido impar:   NGH --> FAR --> FAN
-- --------------------------------
-- Entradas a FAR desde NGH 
--(LA ESTACION NGH NO FORMA PARTE DEL PROYECTO)


-- Salidas desde FAR hacia FAN (P.C a P.C)

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAR_VT05C','FAN_VT07','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAR_VT05C','FAN_VT13','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAR_VT05C','FAN_VT07','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAR_VT05C','FAN_VT13','C',NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAR_VT05C','FAN_VT07','C','I,FAR_D7,FAR_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAR_VT05C','FAN_VT13','C','I,FAR_D7,FAR_D13',80,NULL,NULL,'1',NULL,NULL,NULL); 



-- -----------------------
-- PUNTO DE CONTROL: FAN
-- -----------------------

-- Parejas de tramos en sentido par:   FAR <-- FAN <-- TSS
-- --------------------------------
-- Entradas a FAN desde TSS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_FAN_VC2','FAN_VT10','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_FAN_VC2','FAN_VT18','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_FAN_VC2','FAN_VT10','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_FAN_VC2','FAN_VT18','C',NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC2','FAN_VT10','C','I,FAR_U12,FAR_U8',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC2','FAN_VT18','C','I,FAR_U12,FAR_U10',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC2','FAN_VT18','C','I,FAR_U10,FAR_U18',80,NULL,NULL,'1',NULL,NULL,NULL); 


-- Salidas desde FAN hacia FAR -> Definidas en el sentido PAR de FAR

-- Tabla GRP_PAREJAS_TRAMOS
-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
-- Tabla GRP_PAREJAS_TRAMOS_MANDOS (U8-U6...U18-U14)





-- Parejas de tramos en sentido impar:   FAR --> FAN --> TSS
-- --------------------------------
-- Entradas a FAN desde FAR -> Definidas en el sentido IMPAR de FAR

-- Tabla GRP_PAREJAS_TRAMOS
-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
-- Tabla GRP_PAREJAS_TRAMOS_MANDOS (D7-D9 Y D7-D13)


-- Salidas desde FAN hacia TSS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT07','FAN_TSS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT13','FAN_TSS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT07','FAN_TSS_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT13','FAN_TSS_VC1','C',NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT07','FAN_TSS_VC1','C','I,FAR_D9,FAR_TSH_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT13','FAN_TSS_VC1','C','I,FAR_D13,FAR_D11',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT13','FAN_TSS_VC1','C','I,FAR_D11,FAR_TSH_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);



-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).


--FAR

-- Parejas de tramos en sentido par:   NGH <-- FAR <-- FAN
-- --------------------------------
-- Entradas a FAR desde FAN

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT10','FAR_VT08','C','I,FAR_U8,FAR_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U6', 'FAR_U8', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U6', 'FAR_U8', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U6', 'FAR_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U6', 'FAR_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U6', 'FAR_VT08_I','CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U6', 'FAR_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT10','FAR_VT14','C','I,FAR_U8,FAR_U14',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U14', 'FAR_U8', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U14', 'FAR_U8', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U14', 'FAR_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U14', 'FAR_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U14', 'FAR_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U14', 'FAR_VT14_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8,FAR_U14', 'FAR_VT14', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT18','FAR_VT08','C','I,FAR_U18,FAR_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U6', 'FAR_U18', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U6', 'FAR_U18', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U6', 'FAR_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U6', 'FAR_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U6', 'FAR_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U6', 'FAR_VT08_I','CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U6', 'FAR_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT18','FAR_VT14','C','I,FAR_U18,FAR_U14',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U14', 'FAR_U18', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U14', 'FAR_U18', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U14', 'FAR_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U14', 'FAR_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U14', 'FAR_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U14', 'FAR_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U14', 'FAR_VT14_I','CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18,FAR_U14', 'FAR_VT14', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- Salidas desde FAR hacia NGH (NO SE HACEN)



-- Parejas de tramos en sentido impar:   NGH --> FAR --> FAN
-- --------------------------------
-- Entradas a FAR desde NGH (NO SE HACEN)



-- Salidas desde FAR hacia FAN


--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAR_VT05C','FAN_VT07','C','I,FAR_D7,FAR_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D9', 'FAR_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D9', 'FAR_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D9', 'FAR_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D9', 'FAR_VT07_I','CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D9', 'FAR_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAR_VT05C','FAN_VT13','C','I,FAR_D7,FAR_D13',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D13', 'FAR_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D13', 'FAR_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D13', 'FAR_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D13', 'FAR_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D13', 'FAR_VT07_I','CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7,FAR_D13', 'FAR_VT13', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


--FAN

-- Parejas de tramos en sentido par:   FAR <-- FAN <-- TSS
-- --------------------------------
-- Entradas a FAN desde TSS

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC2','FAN_VT10','C','I,FAR_U12,FAR_U8',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U8', 'FAR_U12', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U8', 'FAR_U12', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U8', 'FAR_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U8', 'FAR_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U8', 'FAR_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U8', 'FAR_VT12B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U8', 'FAR_VT10', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U8', 'FAR_P05B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');


--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC2','FAN_VT18','C','I,FAR_U12,FAR_U10',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U10', 'FAR_U12', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U10', 'FAR_U12', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U10', 'FAR_VT12B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U10', 'FAR_P01B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 

--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U10', 'FAR_P02A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U10', 'FAR_P04B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U10', 'FAR_P04A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12,FAR_U10', 'FAR_VT18', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');	


--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC2','FAN_VT18','C','I,FAR_U10,FAR_U18',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_U18', 'FAR_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_U18', 'FAR_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_U18', 'FAR_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_U18', 'FAR_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_U18', 'FAR_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_U18', 'FAR_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_U18', 'FAR_VT18', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	

-- Salidas desde FAN hacia FAR (Declaradas como entradas en FAR)


-- Parejas de tramos en sentido impar:   FAR --> FAN --> TSS
-- --------------------------------
-- Entradas a FAN desde FAR (Declaradas como salidas en FAR)


-- Salidas desde FAN hacia TSS

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT07','FAN_TSS_VC1','C','I,FAR_D9,FAR_TSH_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_TSH_DOWN', 'FAR_D9', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_TSH_DOWN', 'FAR_D9', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_TSH_DOWN', 'FAR_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_TSH_DOWN', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_TSH_DOWN', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_TSH_DOWN', 'FAR_VT09', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_TSH_DOWN', 'FAR_VT11A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT13','FAN_TSS_VC1','C','I,FAR_D13,FAR_D11',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_D11', 'FAR_D13', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_D11', 'FAR_D13', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_D11', 'FAR_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_D11', 'FAR_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_D11', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_D11', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_D11', 'FAR_VT09', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT13','FAN_TSS_VC1','C','I,FAR_D11,FAR_TSH_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11,FAR_TSH_DOWN', 'FAR_D11', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11,FAR_TSH_DOWN', 'FAR_D11', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11,FAR_TSH_DOWN', 'FAR_VT11A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	

