--TRAMOS
-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'TSS_FAN_VC1','TSS',NULL,NULL,NULL,NULL,'E',NULL,'FAN','1','PAR');
-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TSS_FAN_VC1','TSH_VTA871A',NULL);

-- Tabla GRP_TRAMOS 
INSERT INTO GRP_TRAMOS VALUES (1,'FAN_TSS_VC2','FAN',NULL,NULL,NULL,NULL,'E',NULL,'TSS','2','IMPAR');
-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'FAN_TSS_VC2','TSH_VTA880B',NULL);


-- -----------------------
-- PUNTO DE CONTROL: FAN
-- -----------------------

-- Parejas de tramos en sentido par:   FAR <-- FAN <-- TSS
-- --------------------------------
-- Entradas a FAN desde TSS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_FAN_VC1','FAN_VT13','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_FAN_VC1','FAN_VT07','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_FAN_VC1','FAN_VT10','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_FAN_VC1','FAN_VT18','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 


INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_FAN_VC2','FAN_VT13','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TSS_FAN_VC2','FAN_VT07','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_FAN_VC1','FAN_VT13','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_FAN_VC1','FAN_VT07','C',NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_FAN_VC1','FAN_VT10','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_FAN_VC1','FAN_VT18','C',NULL,NULL,NULL,NULL,NULL); 


INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_FAN_VC2','FAN_VT13','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TSS_FAN_VC2','FAN_VT07','C',NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC1','FAN_VT13','C','I,FAR_D11CF,FAR_D9CF',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC1','FAN_VT13','C','I,FAR_D9CF,FAR_D13CF',80,NULL,NULL,'1',NULL,NULL,NULL); 

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC1','FAN_VT07','C','I,FAR_D11CF,FAR_D7CF',80,NULL,NULL,'1',NULL,NULL,NULL); 

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC1','FAN_VT10','C','I,FAR_D11CF,FAR_D9CF',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC1','FAN_VT10','C','I,FAR_D9CF,FAR_U8',80,NULL,NULL,'1',NULL,NULL,NULL); 

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC1','FAN_VT18','C','I,FAR_D11CF,FAR_D9CF',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC1','FAN_VT18','C','I,FAR_D9CF,FAR_U18',80,NULL,NULL,'1',NULL,NULL,NULL); 

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC2','FAN_VT13','C','I,FAR_U12,FAR_U10',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC2','FAN_VT13','C','I,FAR_U10,FAR_D13CF',80,NULL,NULL,'1',NULL,NULL,NULL); 

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC2','FAN_VT07','C','I,FAR_U12,FAR_U10',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TSS_FAN_VC2','FAN_VT07','C','I,FAR_U10,FAR_D7CF',80,NULL,NULL,'1',NULL,NULL,NULL); 



-- PUNTO DE CONTROL: FAR
-- -----------------------

-- Parejas de tramos en sentido par:   NGH <-- FAR <-- FAN
-- --------------------------------
-- Entradas a FAR desde FAN (P.C a P.C)

-- Tabla GRP_PAREJAS_TRAMOS
--No se hacen las rutas a CF
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT13','FAR_VT05C','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT07','FAR_VT05C','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT13','FAR_VT05C','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT07','FAR_VT05C','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT13','FAR_VT05C','C','I,FAR_D13CF,FAR_D5CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT07','FAR_VT05C','C','I,FAR_D7CF,FAR_D5CF',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar:   NGH --> FAR --> FAN
-- --------------------------------

-- Salidas desde FAR hacia FAN (P.C a P.C)

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAR_VT08','FAN_VT10','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAR_VT08','FAN_VT18','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAR_VT14','FAN_VT10','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAR_VT14','FAN_VT18','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAR_VT08','FAN_VT10','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAR_VT08','FAN_VT18','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAR_VT14','FAN_VT10','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAR_VT14','FAN_VT18','C',NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAR_VT08','FAN_VT10','C','I,FAR_U8CF,FAR_U10CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAR_VT08','FAN_VT18','C','I,FAR_U8CF,FAR_U18CF',80,NULL,NULL,'1',NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAR_VT14','FAN_VT10','C','I,FAR_U14CF,FAR_U10CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAR_VT14','FAN_VT18','C','I,FAR_U14CF,FAR_U18CF',80,NULL,NULL,'1',NULL,NULL,NULL); 



-- Parejas de tramos en sentido impar:   FAR --> FAN --> TSS
-- --------------------------------
-- Salidas desde FAN hacia TSS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT13','FAN_TSS_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT07','FAN_TSS_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT10','FAN_TSS_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT18','FAN_TSS_VC2','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT10','FAN_TSS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'FAN_VT18','FAN_TSS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT13','FAN_TSS_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT07','FAN_TSS_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT10','FAN_TSS_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT18','FAN_TSS_VC2','C',NULL,NULL,NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT10','FAN_TSS_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'FAN_VT18','FAN_TSS_VC1','C',NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT13','FAN_TSS_VC2','C','I,FAR_D13,FAR_U12CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT13','FAN_TSS_VC2','C','I,FAR_U12CF,FAR_TSH_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT07','FAN_TSS_VC2','C','I,FAR_D9,FAR_U12CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT07','FAN_TSS_VC2','C','I,FAR_U12CF,FAR_TSH_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT10','FAN_TSS_VC2','C','I,FAR_U10CF,FAR_TSH_UP',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT18','FAN_TSS_VC2','C','I,FAR_U18CF,FAR_U12CF',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT18','FAN_TSS_VC2','C','I,FAR_U12CF,FAR_TSH_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT10','FAN_TSS_VC1','C','I,FAR_U10CF,FAR_D11',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT10','FAN_TSS_VC1','C','I,FAR_D11,FAR_TSH_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT18','FAN_TSS_VC1','C','I,FAR_U18CF,FAR_D11',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'FAN_VT18','FAN_TSS_VC1','C','I,FAR_D11,FAR_TSH_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido par:   NGH <-- FAR <-- FAN
-- --------------------------------
-- Entradas a FAR desde FAN

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11CF,FAR_D9CF', 'FAR_D11CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11CF,FAR_D9CF', 'FAR_D11CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11CF,FAR_D9CF', 'FAR_VT11A','CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11CF,FAR_D9CF', 'FAR_VT09', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11CF,FAR_D7CF', 'FAR_D11CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11CF,FAR_D7CF', 'FAR_D11CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11CF,FAR_D7CF', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11CF,FAR_D7CF', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11CF,FAR_D7CF', 'FAR_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D11CF,FAR_D7CF', 'FAR_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_D13CF', 'FAR_D9CF', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_D13CF', 'FAR_D9CF', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_D13CF', 'FAR_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_D13CF', 'FAR_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_D13CF', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_D13CF', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_D13CF', 'FAR_VT13', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U8', 'FAR_D9CF', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U8', 'FAR_D9CF', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U8', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U8', 'FAR_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U8', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U8', 'FAR_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U8', 'FAR_VT10', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U18', 'FAR_D9CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U18', 'FAR_D9CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U18', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U18', 'FAR_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U18', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U18', 'FAR_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9CF,FAR_U18', 'FAR_VT10', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D13CF', 'FAR_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D13CF', 'FAR_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D13CF', 'FAR_P01B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D13CF', 'FAR_P01A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D13CF', 'FAR_P02B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D13CF', 'FAR_P03B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D13CF', 'FAR_P03A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D13CF', 'FAR_VT13', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D7CF', 'FAR_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D7CF', 'FAR_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D7CF', 'FAR_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D7CF', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D7CF', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D7CF', 'FAR_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10,FAR_D7CF', 'FAR_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13CF,FAR_D5CF', 'FAR_D13CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13CF,FAR_D5CF', 'FAR_D13CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13CF,FAR_D5CF', 'FAR_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13CF,FAR_D5CF', 'FAR_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13CF,FAR_D5CF', 'FAR_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13CF,FAR_D5CF', 'FAR_VT05C', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7CF,FAR_D5CF', 'FAR_D7CF', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7CF,FAR_D5CF', 'FAR_D7CF', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7CF,FAR_D5CF', 'FAR_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7CF,FAR_D5CF', 'FAR_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D7CF,FAR_D5CF', 'FAR_VT05C', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U18CF', 'FAR_U8CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U18CF', 'FAR_U8CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U18CF', 'FAR_VT08_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U18CF', 'FAR_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U18CF', 'FAR_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U18CF', 'FAR_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U18CF', 'FAR_VT18', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U10CF', 'FAR_U8CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U10CF', 'FAR_U8CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U10CF', 'FAR_VT08_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U10CF', 'FAR_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U10CF', 'FAR_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U8CF,FAR_U10CF', 'FAR_VT10', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U10CF', 'FAR_U14CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U10CF', 'FAR_U14CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U10CF', 'FAR_VT14_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U10CF', 'FAR_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U10CF', 'FAR_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U10CF', 'FAR_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U10CF', 'FAR_VT10', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U18CF', 'FAR_U14CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U18CF', 'FAR_U14CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U18CF', 'FAR_VT14_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U18CF', 'FAR_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U18CF', 'FAR_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U18CF', 'FAR_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U18CF', 'FAR_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U14CF,FAR_U18CF', 'FAR_VT18', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	



INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_U12CF', 'FAR_D13', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_U12CF', 'FAR_D13', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_U12CF', 'FAR_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_U12CF', 'FAR_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_U12CF', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_U12CF', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_U12CF', 'FAR_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D13,FAR_U12CF', 'FAR_VT12B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_U12CF', 'FAR_D9', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_U12CF', 'FAR_D9', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_U12CF', 'FAR_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_U12CF', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_U12CF', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_U12CF', 'FAR_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_D9,FAR_U12CF', 'FAR_VT12B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_TSH_UP', 'FAR_U10CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_TSH_UP', 'FAR_U10CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_TSH_UP', 'FAR_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_TSH_UP', 'FAR_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_TSH_UP', 'FAR_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_TSH_UP', 'FAR_VT12B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_TSH_UP', 'FAR_VT12A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_TSH_UP', 'FAR_VTA886B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_U12CF', 'FAR_U18CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_U12CF', 'FAR_U18CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_U12CF', 'FAR_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_U12CF', 'FAR_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_U12CF', 'FAR_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_U12CF', 'FAR_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_U12CF', 'FAR_VT12B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12CF,FAR_TSH_UP', 'FAR_U12CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12CF,FAR_TSH_UP', 'FAR_U12CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12CF,FAR_TSH_UP', 'FAR_VT12A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U12CF,FAR_TSH_UP', 'FAR_VTA886B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_D11', 'FAR_U10CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_D11', 'FAR_U10CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_D11', 'FAR_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_D11', 'FAR_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_D11', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_D11', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U10CF,FAR_D11', 'FAR_VT09', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	


INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_D11', 'FAR_U18CF', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_D11', 'FAR_U18CF', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_D11', 'FAR_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_D11', 'FAR_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_D11', 'FAR_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_D11', 'FAR_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_D11', 'FAR_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,FAR_U18CF,FAR_D11', 'FAR_VT09', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	



