-- Datos de la linea ASYUT NAGH HAMMADI
-- Enclavamiento: ABOU_TIG (TIG)

-- 1. Creamos una nueva version */
--INSERT INTO GRP_VERSIONES VALUES (1, 'TIG.1st', 'GRP de TIG', to_date('2025-02-28 11:00:00','yyyy-mm-dd hh24:mi:ss'), to_date('2025-02-28 11:00:00','yyyy-mm-dd hh24:mi:ss'));  

-- Puntos de control: 
-- TIN: Abou Tig-North		T05, T08B, T12 
-- TIG: Abou Tig			T03, T06, T11 (T13 pendiente)

-- Colaterales	
-- MUT: Mutea	
-- SDF: Sedfa	


-- Tabla GRP_PUNTOS_CONTROL
-- GRP_PUNTOS_CONTROL(ID_VERSION, ID_PUNTO_CONTROL, CODIGO_ENCLAVAMIENTO, PC_NOMBRE_MALLAS, PC_TIPO, MNEMONICO, AUTOMATICO, CAMBIO_TREN, COD_RENFE, FECHA_ULTIMO_CAMBIO_AUTOMATICO, PERMITE_CAMBIO_AUTOMATICO)
--INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'TIN','TIG','Abou Tig-North',1,NULL,'A',NULL,NULL,NULL,'S',2);
--INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'TIG','TIG','Abou Tig',1,NULL,'A',NULL,NULL,NULL,'S',3);


-- ELEMENTOS de los puntos de contol
-- GRP_ELEMENTOS_PUNTOS_CONTROL(PUNTO_CONTROL, CODIGO_ELEMENTO, VIA, ID_VERSION)
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TIN','TIG_VT05','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TIN','TIG_VT08B','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TIN','TIG_VT12','4',1);

INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TIG','TIG_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TIG','TIG_VT06','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TIG','TIG_VT11','3',1);


---------------------------------------------------------------------
-- Tablas GRP_TRAMOS y GRP_REL_TRAMOS_CIRCUITOS_VIA
---------------------------------------------------------------------
-- Tabla GRP_TRAMOS de estacionamiento
-- INSERT INTO GRP_TRAMOS VALUES (1,ID_TRAMO,ID_PUNTO_CONTROL,NULL,NULL,NULL,NULL,E_S,NULL,NULL,VIA,SENTIDO);
INSERT INTO GRP_TRAMOS VALUES (1,'TIN_VT05', 'TIN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TIN_VT08B','TIN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TIN_VT12', 'TIN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');

INSERT INTO GRP_TRAMOS VALUES (1,'TIG_VT03','TIG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TIG_VT06','TIG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TIG_VT11','TIG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');


-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
-- INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,ID_TRAMO,COD_CV,NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TIN_VT05', 'TIG_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TIN_VT08B','TIG_VT08B',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TIN_VT12', 'TIG_VT12',NULL);

INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TIG_VT03','TIG_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TIG_VT06','TIG_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TIG_VT11','TIG_VT11',NULL);


-- Tramos de trayecto en sentido PAR
-- GRP_TRAMOS de Bloqueo
--INSERT INTO GRP_TRAMOS VALUES (1,'MUT_TIN_VC2','MUT',NULL,NULL,NULL,NULL,'E',NULL,'TIN','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA (Bloqueo)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MUT_TIN_VC2','TIG_VTA644B',NULL);


---- Tramos de trayecto en sentido IMPAR
---- GRP_TRAMOS de Bloqueo
--INSERT INTO GRP_TRAMOS VALUES (1,'SDF_TIG_VC1','SDF',NULL,NULL,NULL,NULL,'E',NULL,'TIG','1','IMPAR');
--
---- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA de Bloqueo
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SDF_TIG_VC1','TIG_VTA651B',NULL);
--
--
-----------------------------------------------------------------------
---- Tramos de reset (rutas de salida)
-----------------------------------------------------------------------
---- Salidas sentido PAR
---- En estos casos es el CV de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'TIG_SDF_VT02_I','TIG',NULL,NULL,NULL,NULL,'E',NULL,'SDF','2','PAR');
--
---- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TIG_SDF_VT02_I','TIG_VT02_I',NULL);
--
--
---- Salidas sentido IMPAR
--INSERT INTO GRP_TRAMOS VALUES (1,'TIN_MUT_VT09_I','TIN',NULL,NULL,NULL,NULL,'E',NULL,'MUT','1','IMPAR');
--
-- -- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TIN_MUT_VT09_I','TIG_VT09_I',NULL);
-----------------------------------------------------------------------


-- Parejas de tramos en sentido PAR  Via 2
---------------------------------------
-- INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,SENTIDO,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
-----------------------------------------------------------------------
-- Entradas desde MUT a TIN 
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_TIN_VC2','TIN_VT08B','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MUT_TIN_VC2','TIN_VT12','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_TIN_VC2','TIN_VT08B','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MUT_TIN_VC2','TIN_VT12','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,'C',CODIGO_MANDO,80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','TIN_VT08B','C','I,TIG_U10,TIG_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','TIN_VT12', 'C','I,TIG_U8,TIG_U12',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MUT_TIN_VC2','TIN_VT12', 'C','I,TIG_U10,TIG_U8',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas desde TIN a TIG 
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TIN_VT08B','TIG_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TIN_VT12', 'TIG_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TIN_VT08B','TIG_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TIN_VT12', 'TIG_VT06','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIN_VT08B','TIG_VT06','C','I,TIG_U6, TIG_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIN_VT08B','TIG_VT06','C','I,TIG_U6,TIG_U4',80,NULL,NULL,'1',NULL,NULL,NULL);

INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIN_VT12', 'TIG_VT06','C','I,TIG_U12,TIG_U4',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salida de TIG a SDF  Via 2 
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TIG_VT06','TIG_SDF_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TIG_VT06','TIG_SDF_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIG_VT06','TIG_SDF_VC2','C','I,TIG_U4, TIG_SDF_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIG_VT06','TIG_SDF_VC2','C','I,TIG_U4,TIG_SDF_UP',80,NULL,NULL,'1',NULL,NULL,NULL);



------------------------------------------------------------------------------------------------------
-- Parejas de tramos en sentido IMPAR   Via 1 
------------------------------------------------------------------------------------------------------
-- Entrada desde SDF a TIG 
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDF_TIG_VC1','TIG_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDF_TIG_VC1','TIG_VT11','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDF_TIG_VC1','TIG_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDF_TIG_VC1','TIG_VT11','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_TIG_VC1','TIG_VT03','C','I,TIG_D1,TIG_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_TIG_VC1','TIG_VT11','C','I,TIG_D3,TIG_D11',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_TIG_VC1','TIG_VT11','C','I,TIG_D1,TIG_D3',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entrada desde TIG a TIN    via 1 
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TIG_VT03','TIN_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TIG_VT11','TIN_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TIG_VT03','TIN_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TIG_VT11','TIN_VT05','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIG_VT03','TIN_VT05','C','I,TIG_D5,TIG_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIG_VT11','TIN_VT05','C','I,TIG_D11,TIG_D7',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas de TIN hacia MUT   via 1
-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TIN_VT05','TIN_MUT_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TIN_VT05','TIN_MUT_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIN_VT05','TIN_MUT_VC1','C','I,TIG_D7,TIG_MUT_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);


-----------------------------------
-- Tabla GRP_COMPROBACIONES_MANDOS en sentido PAR  Via 2
-- Comprobaciones asociadas a los mandos (Condiciones de envio)
-- (ID_VERSION, CODIGO_MANDO, CODIGO_ELEMENTO, ASPECTO, CONDICION, OPERACION_LOGICA)
---------------------------------------
-- Entradas desde MUT a TIN por V2
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U6', 'TIG_U10', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U6', 'TIG_U10', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U6', 'TIG_P01A', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U6', 'TIG_P02B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U6', 'TIG_VT10_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U6', 'TIG_VT10B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U6', 'TIG_VT08B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U8,TIG_U12', 'TIG_U8', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U8,TIG_U12', 'TIG_U8', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U8,TIG_U12', 'TIG_P01A', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U8,TIG_U12', 'TIG_P02B', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U8,TIG_U12', 'TIG_P02A', 'AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U8,TIG_U12', 'TIG_VT08A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U8,TIG_U12', 'TIG_VT12', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U8', 'TIG_U10', 'SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U8', 'TIG_U10', 'SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U8', 'TIG_P01A', 'AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U8', 'TIG_P02B', 'AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U8', 'TIG_P02A', 'AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U8', 'TIG_VT10_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U8', 'TIG_VT10B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U10,TIG_U8', 'TIG_VT08A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

-- Entradas desde TIN a TIG 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U6,TIG_U4','TIG_U6','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U6,TIG_U4','TIG_U6','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U6,TIG_U4','TIG_P03B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U6,TIG_U4','TIG_P05A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U6,TIG_U4','TIG_VT06','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U12,TIG_U4','TIG_U12','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U12,TIG_U4','TIG_U12','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U12,TIG_U4','TIG_P05B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U12,TIG_U4','TIG_P05A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U12,TIG_U4','TIG_VT06','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

-- Salida de TIG a SDF  Via 2 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U4,TIG_SDF_UP','TIG_U4','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U4,TIG_SDF_UP','TIG_U4','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U4,TIG_SDF_UP','TIG_P08B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U4,TIG_SDF_UP','TIG_P09A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U4,TIG_SDF_UP','TIG_VT04','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_U4,TIG_SDF_UP','TIG_VT02_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-----------------------------------
-- Tabla GRP_COMPROBACIONES_MANDOS en sentido IMPAR  Via 1
-- (ID_VERSION, CODIGO_MANDO, CODIGO_ELEMENTO, ASPECTO, CONDICION, OPERACION_LOGICA)
---------------------------------------
-- Entrada desde SDF a TIG 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D5','TIG_D1','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D5','TIG_D1','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D5','TIG_P09B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D5','TIG_P08A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D5','TIG_P07B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D5','TIG_VT01_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D5','TIG_VT01B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D5','TIG_VT03','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D3,TIG_D11','TIG_D3','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D3,TIG_D11','TIG_D3','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D3,TIG_D11','TIG_P09B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D3,TIG_D11','TIG_P08A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D3,TIG_D11','TIG_P07B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D3,TIG_D11','TIG_P07A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D3,TIG_D11','TIG_P06','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D3,TIG_D11','TIG_VT11_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D3,TIG_D11','TIG_VT11','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D3','TIG_D1','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D3','TIG_D1','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D3','TIG_P09B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D3','TIG_P08A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D3','TIG_P07B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D3','TIG_P07A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D3','TIG_P06','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D3','TIG_VT01_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D1,TIG_D3','TIG_VT01B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


---------------------------------------
-- Entrada desde TIG a TIN    via 1 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D5,TIG_D7','TIG_D5','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D5,TIG_D7','TIG_D5','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D5,TIG_D7','TIG_P04B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D5,TIG_D7','TIG_P03A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D5,TIG_D7','TIG_VT05','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D11,TIG_D7','TIG_D11','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D11,TIG_D7','TIG_D11','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D11,TIG_D7','TIG_P04B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D11,TIG_D7','TIG_P03A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D11,TIG_D7','TIG_VT05','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


---------------------------------------
-- Salidas de TIN hacia MUT   via 1
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D7,TIG_MUT_DOWN','TIG_D7','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D7,TIG_MUT_DOWN','TIG_D7','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D7,TIG_MUT_DOWN','TIG_P01B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D7,TIG_MUT_DOWN','TIG_VT07A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D7,TIG_MUT_DOWN','TIG_VT07B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D7,TIG_MUT_DOWN','TIG_VT09A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,TIG_D7,TIG_MUT_DOWN','TIG_VT09_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

