-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Sedfa
-- Enclavamiento: SDF
-- Puntos de control:
-- Sedfa: 		SDF  T05, T08, T13
-- Sedfa South: SDS  T03, T06, T11
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


-- - Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'SDF','SDF','Sedfa',1,NULL,'A',NULL,NULL,NULL,'S', 4);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'SDS','SDF','Sedfa South',1,NULL,'A',NULL,NULL,NULL,'S', 5);


-- -----------------------
-- PUNTO DE CONTROL: SDS
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL:
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SDS','SDF_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SDS','SDF_VT06','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SDS','SDF_VT11','3',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'SDS_VT03','SDS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SDS_VT06','SDS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SDS_VT11','SDS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SDS_VT03','SDF_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SDS_VT06','SDF_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SDS_VT11','SDF_VT11',NULL);

-- -------------------------

-- Tramos de trayecto en sentido par  TMN <-- SDS <-- SDF
-- ---------------------------------

-- SDS --> TMN

-- Tramos de reset

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'SDS_TMN_VT02A','SDS',NULL,NULL,NULL,NULL,'E',NULL,'TMN','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SDS_TMN_VT02A','SDF_VT02A',NULL);


-- Tramos de trayecto en sentido impar   TMN -> SDS -> SDF
-- ---------------------------------

-- TMN --> SDS 

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'TMN_SDS_VC1','TMN',NULL,NULL,NULL,NULL,'E',NULL,'SDS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TMN_SDS_VC1','TMA_VTA675B',NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------


-- -----------------------
-- PUNTO DE CONTROL: SDF
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL:
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SDF','SDF_VT05','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SDF','SDF_VT08','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SDF','SDF_VT13','3',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'SDF_VT05','SDF',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SDF_VT08','SDF',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SDF_VT13','SDF',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SDF_VT05','SDF_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SDF_VT08','SDF_VT08',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SDF_VT13','SDF_VT13',NULL);

-- -------------------------

-- Tramos de trayecto en sentido par  SDS <-- SDF <-- TIG
-- ---------------------------------

-- TIG --> SDF

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'TIG_SDF_VC2','TIG',NULL,NULL,NULL,NULL,'E',NULL,'SDF','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TIG_SDF_VC2','SDF_VTA668B',NULL);


-- Tramos de trayecto en sentido impar  SDS -> SDF -> TIG
-- ---------------------------------

-- SDF --> TIG

-- Tramos de reset

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'SDF_TIG_VT09A','SDF',NULL,NULL,NULL,NULL,'E',NULL,'TIG','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SDF_TIG_VT09A','SDF_VT09A',NULL);


-- ----------------------------------------------------------------------------------------------------------------------------------------


-- -----------------------
-- PUNTO DE CONTROL: SDS
-- -----------------------

-- Parejas de tramos en sentido par  TMN <-- SDS <-- SDF
-- --------------------------------

-- Entradas a SDS desde SDF

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDF_VT08','SDS_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDF_VT08','SDS_VT06','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_VT08','SDS_VT06','C','I,SDF_U6,SDF_U4',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde SDS hacia TMN

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDS_VT06','SDS_TMN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDS_VT06','SDS_TMN_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_VT06','SDS_TMN_VC2','C','I,SDF_U4,SDF_TMA_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar  TMN --> SDS --> SDF
-- --------------------------------

-- Entradas a SDS desde TMN

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TMN_SDS_VC1','SDS_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TMN_SDS_VC1','SDS_VT11','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TMN_SDS_VC1','SDS_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TMN_SDS_VC1','SDS_VT11','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_SDS_VC1','SDS_VT03','C','I,SDF_D1,SDF_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_SDS_VC1','SDS_VT11','C','I,SDF_D1,SDF_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_SDS_VC1','SDS_VT11','C','I,SDF_D3,SDF_D11',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde SDS hacia SDF

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDS_VT03','SDF_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDS_VT03','SDF_VT13','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDS_VT11','SDF_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDS_VT11','SDF_VT13','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDS_VT03','SDF_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDS_VT03','SDF_VT13','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDS_VT11','SDF_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDS_VT11','SDF_VT13','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_VT03','SDF_VT05','C','I,SDF_D5,SDF_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_VT03','SDF_VT13','C','I,SDF_D5,SDF_D13',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_VT11','SDF_VT05','C','I,SDF_D11,SDF_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_VT11','SDF_VT13','C','I,SDF_D11,SDF_D13',80,NULL,NULL,'1',NULL,NULL,NULL);


-- ----------------------------------------------------------------------------------------------------------------------------------------


-- -----------------------
-- PUNTO DE CONTROL: SDF
-- -----------------------

-- Parejas de tramos en sentido par  SDS <-- SDF <-- TIG
-- --------------------------------

-- Entradas a SDF desde TIG

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TIG_SDF_VC2','SDF_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TIG_SDF_VC2','SDF_VT08','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIG_SDF_VC2','SDF_VT08','C','I,SDF_U10,SDF_U6',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde SDF hacia SDS

-- Tabla GRP_PAREJAS_TRAMOS
--DEFINIDAS EN SDS (U6-U4)


-- Parejas de tramos en sentido impar  SDS --> SDF --> TIG
-- --------------------------------

-- Entradas a SDF desde SDS

-- Tabla GRP_PAREJAS_TRAMOS
--DEFINIDAS EN SDS (D5-D7, D5-D13, D11-D7, D11-D13)


-- Salidas desde SDF hacia TIG

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDF_VT05','SDF_TIG_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDF_VT13','SDF_TIG_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDF_VT05','SDF_TIG_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDF_VT13','SDF_TIG_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_VT05','SDF_TIG_VC1','C','I,SDF_D7,SDF_TIG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_VT13','SDF_TIG_VC1','C','I,SDF_D13,SDF_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_VT13','SDF_TIG_VC1','C','I,SDF_D9,SDF_GRG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_VT13','SDF_TIG_VC1','C','I,SDF_D9,SDF_TIG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);




-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).

--SDS


-- Parejas de tramos en sentido par:   TMN <-- SDS <-- SDF
-- --------------------------------
-- Entradas a SDS desde SDF

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_VT08','SDS_VT06','C','I,SDF_U6,SDF_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U6,SDF_U4', 'SDF_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U6,SDF_U4', 'SDF_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U6,SDF_U4', 'SDF_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U6,SDF_U4', 'SDF_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U6,SDF_U4', 'SDF_VT08_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U6,SDF_U4', 'SDF_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- Salidas desde SDS hacia TMN 

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_VT06','SDS_TMN_VC2','C','I,SDF_U4,SDF_TMA_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U4,SDF_TMA_UP', 'SDF_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U4,SDF_TMA_UP', 'SDF_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U4,SDF_TMA_UP', 'SDF_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U4,SDF_TMA_UP', 'SDF_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U4,SDF_TMA_UP', 'SDF_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Parejas de tramos en sentido impar:   TMN --> SDS --> SDF
-- --------------------------------
-- Entradas a SDS desde TMN 

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_SDS_VC1','SDS_VT03','C','I,SDF_D1,SDF_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D5', 'SDF_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D5', 'SDF_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D5', 'SDF_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D5', 'SDF_P08B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D5', 'SDF_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D5', 'SDF_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D5', 'SDF_P07A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 


-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_SDS_VC1','SDS_VT11','C','I,SDF_D1,SDF_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D3', 'SDF_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D3', 'SDF_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D3', 'SDF_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D3', 'SDF_P09A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D3', 'SDF_P08B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D3', 'SDF_P08A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D1,SDF_D3', 'SDF_VT11', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_SDS_VC1','SDS_VT11','C','I,SDF_D3,SDF_D11',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D3,SDF_D11', 'SDF_D3', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D3,SDF_D11', 'SDF_D3', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D3,SDF_D11', 'SDF_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D3,SDF_D11', 'SDF_P08B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D3,SDF_D11', 'SDF_P08A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D3,SDF_D11', 'SDF_VT11', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Salidas desde SDS hacia SDF

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_VT03','SDF_VT05','C','I,SDF_D5,SDF_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D7', 'SDF_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D7', 'SDF_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D7', 'SDF_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D7', 'SDF_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D7', 'SDF_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D7', 'SDF_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D7', 'SDF_VT05_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D7', 'SDF_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_VT03','SDF_VT13','C','I,SDF_D5,SDF_D13',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D13', 'SDF_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D13', 'SDF_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D13', 'SDF_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D13', 'SDF_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D13', 'SDF_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D13', 'SDF_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D13', 'SDF_VT13_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D5,SDF_D13', 'SDF_VT13', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_VT11','SDF_VT05','C','I,SDF_D11,SDF_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D7', 'SDF_D11', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D7', 'SDF_D11', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D7', 'SDF_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D7', 'SDF_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D7', 'SDF_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D7', 'SDF_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D7', 'SDF_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D7', 'SDF_VT05_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D7', 'SDF_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_VT11','SDF_VT13','C','I,SDF_D11,SDF_D13',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D13', 'SDF_D11', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D13', 'SDF_D11', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D13', 'SDF_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D13', 'SDF_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D13', 'SDF_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D13', 'SDF_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D13', 'SDF_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D13', 'SDF_VT13_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D11,SDF_D13', 'SDF_VT13', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


--SDF

-- Parejas de tramos en sentido par:   SDS <-- SDF <-- TIG
-- --------------------------------
-- Entradas a SDF desde TIG

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TIG_SDF_VC2','SDF_VT08','C','I,SDF_U10,SDF_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U10,SDF_U6', 'SDF_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U10,SDF_U6', 'SDF_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U10,SDF_U6', 'SDF_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U10,SDF_U6', 'SDF_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U10,SDF_U6', 'SDF_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_U10,SDF_U6', 'SDF_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- Salidas desde SDF hacia SDS 

--DECLARADAS EN SDS


-- Parejas de tramos en sentido impar:   SDS --> SDF --> TIG
-- --------------------------------
-- Entradas a SDF desde SDS 

--DECLARADAS EN SDS

-- Salidas desde SDF hacia TIG

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_VT05','SDF_TIG_VC1','C','I,SDF_D7,SDF_TIG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D7,SDF_TIG_DOWN', 'SDF_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D7,SDF_TIG_DOWN', 'SDF_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D7,SDF_TIG_DOWN', 'SDF_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D7,SDF_TIG_DOWN', 'SDF_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D7,SDF_TIG_DOWN', 'SDF_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D7,SDF_TIG_DOWN', 'SDF_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D7,SDF_TIG_DOWN', 'SDF_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_VT13','SDF_TIG_VC1','C','I,SDF_D13,SDF_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D13,SDF_D9', 'SDF_D13', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D13,SDF_D9', 'SDF_D13', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D13,SDF_D9', 'SDF_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D13,SDF_D9', 'SDF_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D13,SDF_D9', 'SDF_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D13,SDF_D9', 'SDF_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D13,SDF_D9', 'SDF_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDF_VT13','SDF_TIG_VC1','C','I,SDF_D9,SDF_GRG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D9,SDF_TIG_DOWN', 'SDF_D9', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D9,SDF_TIG_DOWN', 'SDF_D9', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SDF_D9,SDF_TIG_DOWN', 'SDF_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


