-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Tima-Mishta
-- Enclavamiento: TMA
-- Puntos de control:
-- Tima-North:   TMN  T19, T20, T26
-- Tima:   		 TMA  T17, T18, T33
-- Mishta-North: MIS  T05, T08, T27
-- Mishta-South: MIN  T03, T06, T25
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

-- - Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'TMN','TMA','Tima-North',1,NULL,'A',NULL,NULL,NULL,'S', 6);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'TMA','TMA','Tima',1,NULL,'A',NULL,NULL,NULL,'S', 7);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'MIN','TMA','Mishta-North',1,NULL,'A',NULL,NULL,NULL,'S', 8);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'MIS','TMA','Mishta-South',1,NULL,'A',NULL,NULL,NULL,'S', 9);


-- -----------------------
-- PUNTO DE CONTROL: MIS
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL:
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MIS','TMA_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MIS','TMA_VT06','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MIS','TMA_VT25','3',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'MIS_VT03','MIS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MIS_VT06','MIS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MIS_VT25','MIS',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MIS_VT03','TMA_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MIS_VT06','TMA_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MIS_VT25','TMA_VT25',NULL);

-- -------------------------

-- Tramos de trayecto en sentido par  THT <-- MIS <-- MIN
-- ---------------------------------

-- MIS --> THT

-- Tramos de reset

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'MIS_THT_VT02A','MIS',NULL,NULL,NULL,NULL,'E',NULL,'THT','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MIS_THT_VT02A','TMA_VT02A',NULL);

-- Tramos de trayecto en sentido impar  THT -> MIS -> MIN
-- ---------------------------------

-- THT --> MIS

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'THT_MIS_VC1','THT',NULL,NULL,NULL,NULL,'E',NULL,'MIS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'THT_MIS_VC1','TMA_VTA687B',NULL);


-- -----------------------
-- PUNTO DE CONTROL: MIN
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL:
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MIN','TMA_VT05','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MIN','TMA_VT08','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MIN','TMA_VT27','3',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'MIN_VT05','MIN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MIN_VT08','MIN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MIN_VT27','MIN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MIN_VT05','TMA_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MIN_VT08','TMA_VT08',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MIN_VT27','TMA_VT27',NULL);

-- -------------------------

-- Tramos de trayecto en sentido par  MIS <-- MIN <-- TMA
-- ---------------------------------

-- TMA --> MIN, no porque es P.C a P.C

-- MIN --> MIS, no porque es P.C a P.C


-- Tramos de trayecto en sentido impar  MIS -> MIN -> TMA
-- ---------------------------------

-- MIS --> MIN, no porque es P.C a P.C

-- MIN --> TMA, no porque es P.C a P.C


-- -----------------------
-- PUNTO DE CONTROL: TMA
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL:
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TMA','TMA_VT17','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TMA','TMA_VT18','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TMA','TMA_VT33','3',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'TMA_VT17','TMA',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TMA_VT18','TMA',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TMA_VT33','TMA',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TMA_VT17','TMA_VT17',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TMA_VT18','TMA_VT18',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TMA_VT33','TMA_VT33',NULL);

-- -------------------------

-- Tramos de trayecto en sentido par  MIN <-- TMA <-- TMN
-- ---------------------------------
-- TMN --> TMA, no porque es P.C a P.C

-- TMA --> MIN, no porque es P.C a P.C


-- Tramos de trayecto en sentido impar  MIN -> TMA -> TMN
-- ---------------------------------
-- MIN --> TMA, no porque es P.C a P.C

-- TMA --> TMN, no porque es P.C a P.C


-- -----------------------
-- PUNTO DE CONTROL: TMN
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL:
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TMN','TMA_VT19','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TMN','TMA_VT20','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('TMN','TMA_VT26','4',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'TMN_VT19','TMN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TMN_VT20','TMN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'TMN_VT26','TMN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TMN_VT19','TMA_VT19',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TMN_VT20','TMA_VT20',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TMN_VT26','TMA_VT26',NULL);

-- -------------------------

-- Tramos de trayecto en sentido par  TMA <-- TMN <-- SDS
-- ---------------------------------

-- SDS --> TMN

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'SDS_TMN_VC2','SDS',NULL,NULL,NULL,NULL,'E',NULL,'TMN','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SDS_TMN_VC2','TMA_VTA682B',NULL);


-- Tramos de trayecto en sentido impar  TMA -> TMN -> SDS
-- ---------------------------------

-- TMN --> SDS

-- Tramos de reset

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'TMN_SDS_VT23A','TMN',NULL,NULL,NULL,NULL,'E',NULL,'SDS','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'TMN_SDS_VT23A','TMA_VT23A',NULL);


-- ----------------------------------------------------------------------------------------------------------------------------------------


-- -----------------------
-- PUNTO DE CONTROL: MIS
-- -----------------------

-- Parejas de tramos en sentido par  THT <-- MIS <-- MIN
-- --------------------------------

-- Entradas a MIS desde MIN

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MIN_VT08','MIS_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MIN_VT08','MIS_VT06','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIN_VT08','MIS_VT06','C','I,TMA_U6,TMA_U4',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde MIS hacia THT

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MIS_VT06','MIS_THT_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MIS_VT06','MIS_THT_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_VT06','MIS_THT_VC2','C','I,TMA_U4,TMA_THT_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar  THT --> MIS --> MIN
-- --------------------------------

-- Entradas a MIS desde THT

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'THT_MIS_VC1','MIS_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'THT_MIS_VC1','MIS_VT25','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'THT_MIS_VC1','MIS_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'THT_MIS_VC1','MIS_VT25','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_MIS_VC1','MIS_VT03','C','I,TMA_D1,TMA_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_MIS_VC1','MIS_VT25','C','I,TMA_D1,TMA_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_MIS_VC1','MIS_VT25','C','I,TMA_D3,TMA_D23',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde MIS hacia MIN

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MIS_VT03','MIN_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MIS_VT03','MIN_VT27','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MIS_VT25','MIN_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MIS_VT25','MIN_VT27','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MIS_VT03','MIN_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MIS_VT03','MIN_VT27','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MIS_VT25','MIN_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MIS_VT25','MIN_VT27','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_VT03','MIN_VT05','C','I,TMA_D5,TMA_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_VT03','MIN_VT27','C','I,TMA_D5,TMA_D25',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_VT25','MIN_VT05','C','I,TMA_D23,TMA_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_VT25','MIN_VT27','C','I,TMA_D23,TMA_D25',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------
-- PUNTO DE CONTROL: MIN
-- -----------------------

-- Parejas de tramos en sentido par  MIS <-- MIN <-- TMA
-- --------------------------------

-- Entradas a MIN desde TMA

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TMA_VT18','MIN_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TMA_VT18','MIN_VT08','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMA_VT18','MIN_VT08','C','I,TMA_U16,TMA_U6',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde MIN hacia MIS
-- Definidas en MIS (U6-U4)


-- Parejas de tramos en sentido impar  MIS --> MIN --> TMA
-- --------------------------------

-- Entradas a MIN desde MIS
-- Definidas en MIS (D5-D7, D5-D25, D23-D7, D23-D25)


-- Salidas desde MIN hacia TMA

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MIN_VT05','TMA_VT17','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MIN_VT27','TMA_VT17','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MIN_VT05','TMA_VT17','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MIN_VT27','TMA_VT17','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIN_VT05','TMA_VT17','C','I,TMA_D7,TMA_D17',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIN_VT27','TMA_VT17','C','I,TMA_D25,TMA_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIN_VT27','TMA_VT17','C','I,TMA_D9,TMA_D17',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------
-- PUNTO DE CONTROL: TMA
-- -----------------------

-- Parejas de tramos en sentido par  MIN <-- TMA <-- TMN
-- --------------------------------

-- Entradas a TMA desde TMN

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TMN_VT20','TMA_VT18','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TMN_VT26','TMA_VT18','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TMN_VT20','TMA_VT18','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TMN_VT26','TMA_VT18','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_VT20','TMA_VT18','C','I,TMA_U18,TMA_U16',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_VT26','TMA_VT18','C','I,TMA_U24,TMA_U16',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde TMA hacia MIN
-- Definidas en MIN (U16-U6)


-- Parejas de tramos en sentido impar  MIN --> TMA --> TMN
-- --------------------------------

-- Entradas a TMA desde MIN
-- Definidas en MIN (D7-D17, D25-D9, D9-D17)


-- Salidas desde TMA hacia TMN

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TMA_VT17','TMN_VT19','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TMA_VT33','TMN_VT19','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TMA_VT17','TMN_VT19','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TMA_VT33','TMN_VT19','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMA_VT17','TMN_VT19','C','I,TMA_D17,TMA_D19',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMA_VT33','TMN_VT19','C','I,TMA_D27,TMA_D19',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------
-- PUNTO DE CONTROL: TMN
-- -----------------------

-- Parejas de tramos en sentido par  TMA <-- TMN <-- SDS
-- --------------------------------

-- Entradas a TMN desde SDS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDS_TMN_VC2','TMN_VT20','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SDS_TMN_VC2','TMN_VT26','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDS_TMN_VC2','TMN_VT20','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SDS_TMN_VC2','TMN_VT26','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_TMN_VC2','TMN_VT20','C','I,TMA_U22,TMA_U18',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_TMN_VC2','TMN_VT26','C','I,TMA_U22,TMA_U20',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_TMN_VC2','TMN_VT26','C','I,TMA_U20,TMA_U24',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde TMN hacia TMA
-- Definidas en TMA (U18-U16, U24-U16)


-- Parejas de tramos en sentido impar  TMA --> TMN --> SDS
-- --------------------------------

-- Entradas a TMN desde TMA
-- Definidas en TMA (D17-D19, D27-D19)


-- Salidas desde TMN hacia SDS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'TMN_VT19','TMN_SDS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'TMN_VT19','TMN_SDS_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_VT19','TMN_SDS_VC1','C','I,TMA_D19,TMA_SDF_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);



-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).


-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIN_VT08','MIS_VT06','C','I,TMA_U6,TMA_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U6,TMA_U4', 'TMA_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U6,TMA_U4', 'TMA_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U6,TMA_U4', 'TMA_P16A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U6,TMA_U4', 'TMA_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_VT06','MIS_THT_VC2','C','I,TMA_U4,TMA_THT_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U4,TMA_THT_UP', 'TMA_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U4,TMA_THT_UP', 'TMA_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U4,TMA_THT_UP', 'TMA_P19B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U4,TMA_THT_UP', 'TMA_VT06_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U4,TMA_THT_UP', 'TMA_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U4,TMA_THT_UP', 'TMA_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_MIS_VC1','MIS_VT03','C','I,TMA_D1,TMA_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D5', 'TMA_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D5', 'TMA_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D5', 'TMA_P19A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D5', 'TMA_P18B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D5', 'TMA_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D5', 'TMA_VT03_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D5', 'TMA_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D5', 'TMA_P17B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');


-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_MIS_VC1','MIS_VT25','C','I,TMA_D1,TMA_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D3', 'TMA_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D3', 'TMA_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D3', 'TMA_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D3', 'TMA_P19A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D3', 'TMA_P18B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D3', 'TMA_P18A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D3', 'TMA_VT25_I', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D1,TMA_D3', 'TMA_VT25', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_MIS_VC1','MIS_VT25','C','I,TMA_D3,TMA_D23',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D3,TMA_D23', 'TMA_D3', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D3,TMA_D23', 'TMA_D3', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D3,TMA_D23', 'TMA_P19A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D3,TMA_D23', 'TMA_P18B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D3,TMA_D23', 'TMA_P18A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D3,TMA_D23', 'TMA_VT25_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D3,TMA_D23', 'TMA_VT25', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_VT03','MIN_VT05','C','I,TMA_D5,TMA_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D7', 'TMA_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D7', 'TMA_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D7', 'TMA_P17B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D7', 'TMA_P16B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D7', 'TMA_P15A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D7', 'TMA_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_VT03','MIN_VT27','C','I,TMA_D5,TMA_D25',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D25', 'TMA_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D25', 'TMA_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D25', 'TMA_P17B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D25', 'TMA_P16B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D25', 'TMA_P15A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D25', 'TMA_P15B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D5,TMA_D25', 'TMA_VT27', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_VT25','MIN_VT05','C','I,TMA_D23,TMA_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D7', 'TMA_D23', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D7', 'TMA_D23', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D7', 'TMA_P17A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D7', 'TMA_P17B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D7', 'TMA_P16B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D7', 'TMA_P15A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D7', 'TMA_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_VT25','MIN_VT27','C','I,TMA_D23,TMA_D25',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D25', 'TMA_D23', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D25', 'TMA_D23', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D25', 'TMA_P17A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D25', 'TMA_P17B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D25', 'TMA_P16B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D25', 'TMA_P15A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D25', 'TMA_P15B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D23,TMA_D25', 'TMA_VT27', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMA_VT18','MIN_VT08','C','I,TMA_U16,TMA_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_U16', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_U16', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_P11B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_P12A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_P13B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT18_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT16', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT14_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT14A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT14B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT12A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT12B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT10A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT10_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U16,TMA_U6', 'TMA_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIN_VT05','TMA_VT17','C','I,TMA_D7,TMA_D17',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_P14B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_P13A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_P12B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_P09', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT09B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT11A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT11B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT13A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT13_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT13B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT15_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D7,TMA_D17', 'TMA_VT17', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIN_VT27','TMA_VT17','C','I,TMA_D25,TMA_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_D25', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_D25', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_P14A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_P14B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_P13A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT07_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_P12B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_P11A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_P10B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_P09', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT09A', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT09B', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT11A', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT11B', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT13A', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT13_I', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT13B', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT15_I', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D25,TMA_D9', 'TMA_VT17', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIN_VT27','TMA_VT17','C','I,TMA_D9,TMA_D17',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_D9', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_D9', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_P12B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_P09', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_VT09B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_VT11A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_VT11B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_VT13A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_VT13_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_VT13B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_VT15_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D9,TMA_D17', 'TMA_VT17', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_VT20','TMA_VT18','C','I,TMA_U18,TMA_U16',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U18,TMA_U16', 'TMA_U18', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U18,TMA_U16', 'TMA_U18', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U18,TMA_U16', 'TMA_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U18,TMA_U16', 'TMA_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U18,TMA_U16', 'TMA_VT18', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_VT26','TMA_VT18','C','I,TMA_U24,TMA_U16',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U24,TMA_U16', 'TMA_U24', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U24,TMA_U16', 'TMA_U24', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U24,TMA_U16', 'TMA_P05B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U24,TMA_U16', 'TMA_P05A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U24,TMA_U16', 'TMA_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U24,TMA_U16', 'TMA_VT18', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMA_VT17','TMN_VT19','C','I,TMA_D17,TMA_D19',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D17,TMA_D19', 'TMA_D17', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D17,TMA_D19', 'TMA_D17', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D17,TMA_D19', 'TMA_P06A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D17,TMA_D19', 'TMA_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D17,TMA_D19', 'TMA_VT19', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMA_VT33','TMN_VT19','C','I,TMA_D27,TMA_D19',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D27,TMA_D19', 'TMA_D27', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D27,TMA_D19', 'TMA_D27', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D27,TMA_D19', 'TMA_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D27,TMA_D19', 'TMA_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D27,TMA_D19', 'TMA_VT19', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_TMN_VC2','TMN_VT20','C','I,TMA_U22,TMA_U18',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U18', 'TMA_U22', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U18', 'TMA_U22', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U18', 'TMA_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U18', 'TMA_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U18', 'TMA_VT24B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U18', 'TMA_VT22_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U18', 'TMA_VT20', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_TMN_VC2','TMN_VT26','C','I,TMA_U22,TMA_U20',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U20', 'TMA_U22', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U20', 'TMA_U22', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U20', 'TMA_VT24B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U20', 'TMA_P01A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U20', 'TMA_P02B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U20', 'TMA_P02A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U20', 'TMA_VT22_I', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U22,TMA_U20', 'TMA_VT26', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SDS_TMN_VC2','TMN_VT26','C','I,TMA_U20,TMA_U24',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U20,TMA_U24', 'TMA_U20', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U20,TMA_U24', 'TMA_U20', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U20,TMA_U24', 'TMA_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U20,TMA_U24', 'TMA_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U20,TMA_U24', 'TMA_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U20,TMA_U24', 'TMA_VT22_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_U20,TMA_U24', 'TMA_VT26', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'TMN_VT19','TMN_SDS_VC1','C','I,TMA_D19,TMA_SDF_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D19,TMA_SDF_DOWN', 'TMA_D19', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D19,TMA_SDF_DOWN', 'TMA_D19', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D19,TMA_SDF_DOWN', 'TMA_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D19,TMA_SDF_DOWN', 'TMA_VT19_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D19,TMA_SDF_DOWN', 'TMA_VT21', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,TMA_D19,TMA_SDF_DOWN', 'TMA_VT23A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


