-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Tahta
-- Enclavamiento: THT
-- Puntos de control:
-- Tahta: THT T03, T06, T10, T12
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


-- - Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'THT','THT','Tahta',1,NULL,'A',NULL,NULL,NULL,'S',10);

-- -----------------------
-- PUNTO DE CONTROL: THT
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('THT','THT_VT03','1',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('THT','THT_VT06','2',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('THT','THT_VT10','4',1);	

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'THT_VT03','THT',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'THT_VT06','THT',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'THT_VT10','THT',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'THT_VT03','THT_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'THT_VT06','THT_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'THT_VT10','THT_VT10',NULL);

-- -------------------------------------------------------
-- Tramos de trayecto en sentido PAR:  MRN <-- THT <-- MIS
-- -------------------------------------------------------

--MIS --> THT

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'MIS_THT_VC2','MIS',NULL,NULL,NULL,NULL,'E',NULL,'THT','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA 
-- Este CV lo dice ENR 
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MIS_THT_VC2','THT_VTA704B',NULL); 

--THT --> MRN

-- Tramos de RESET de salida

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'THT_MRN_VT02A','THT',NULL,NULL,NULL,NULL,'E',NULL,'MRN','2','PAR'); 

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'THT_MRN_VT02A','THT_VT02A',NULL); 


-- Tramos de trayecto en sentido IMPAR:  MRN --> THT --> MIS
-- ---------------------------------

--MRN --> THT de entrada

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'MRN_THT_VC1','MRN',NULL,NULL,NULL,NULL,'E',NULL,'THT','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA 
-- Este CV lo dice ENR 
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MRN_THT_VC1','THT_VTA709B',NULL); 


--THT --> MIS

-- Tramos de RESET de salida

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'THT_MIS_VT07A','THT',NULL,NULL,NULL,NULL,'E',NULL,'MIS','2','IMPAR'); 

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'THT_MIS_VT07A','THT_VT07A',NULL);


-- -- -----------------------------------------------------------------------------------------------------------------------------------------


-- Parejas de tramos en sentido par:   MRN <-- THT <-- MIS
-- --------------------------------
-- Entradas a THT desde MIS

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MIS_THT_VC2','THT_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MIS_THT_VC2','THT_VT10','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MIS_THT_VC2','THT_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MIS_THT_VC2','THT_VT10','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_THT_VC2','THT_VT06','C','I,THT_U8,THT_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_THT_VC2','THT_VT10','C','I,THT_U8,THT_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_THT_VC2','THT_VT10','C','I,THT_U6,THT_U10',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde THT hacia MRN 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'THT_VT06','THT_MRN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'THT_VT10','THT_MRN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'THT_VT06','THT_MRN_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'THT_VT10','THT_MRN_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_VT06','THT_MRN_VC2','C','I,THT_U4,THT_MRG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_VT10','THT_MRN_VC2','C','I,THT_U10,THT_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_VT10','THT_MRN_VC2','C','I,THT_U2,THT_MRG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar:   MRN --> THT --> MIS
-- --------------------------------
-- Entradas a THT desde MRN 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MRN_THT_VC1','THT_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MRN_THT_VC1','THT_VT03','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MRN_THT_VC1','THT_VT03','C','I,THT_D1,THT_D5',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde THT hacia MIS 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'THT_VT03','THT_MIS_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'THT_VT03','THT_MIS_VC1','C',NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_VT03','THT_MIS_VC1','C','I,THT_D5,THT_TMA_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------


-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).


--THT

-- Parejas de tramos en sentido par:   MRN <-- THT <-- MIS
-- --------------------------------
-- Entradas a THT desde MIS


-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_THT_VC2','THT_VT06','C','I,THT_U8,THT_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U4', 'THT_U8', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U4', 'THT_U8', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U4', 'THT_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U4', 'THT_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U4', 'THT_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U4', 'THT_VT08B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U4', 'THT_VT06_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U4', 'THT_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_THT_VC2','THT_VT10','C','I,THT_U8,THT_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U6', 'THT_U8', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U6', 'THT_U8', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U6', 'THT_VT08B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U6', 'THT_P01B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U6', 'THT_P02A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U6', 'THT_P03B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U6', 'THT_P03A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U6', 'THT_P04', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U6', 'THT_VT10_I', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U8,THT_U6', 'THT_VT10', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MIS_THT_VC2','THT_VT10','C','I,THT_U6,THT_U10',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U6,THT_U10', 'THT_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U6,THT_U10', 'THT_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U6,THT_U10', 'THT_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U6,THT_U10', 'THT_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U6,THT_U10', 'THT_P03B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U6,THT_U10', 'THT_P03A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U6,THT_U10', 'THT_P04', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U6,THT_U10', 'THT_VT10_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U6,THT_U10', 'THT_VT10', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Salidas desde THT hacia MRN 

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_VT06','THT_MRN_VC2','C','I,THT_U4,THT_MRG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U4,THT_MRG_UP', 'THT_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U4,THT_MRG_UP', 'THT_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U4,THT_MRG_UP', 'THT_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U4,THT_MRG_UP', 'THT_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U4,THT_MRG_UP', 'THT_P12A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U4,THT_MRG_UP', 'THT_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U4,THT_MRG_UP', 'THT_VT02_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U4,THT_MRG_UP', 'THT_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_VT10','THT_MRN_VC2','C','I,THT_U10,THT_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U10,THT_U2', 'THT_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U10,THT_U2', 'THT_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U10,THT_U2', 'THT_P08B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U10,THT_U2', 'THT_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U10,THT_U2', 'THT_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U10,THT_U2', 'THT_P12A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U10,THT_U2', 'THT_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_VT10','THT_MRN_VC2','C','I,THT_U2,THT_MRG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U2,THT_BSL_UP', 'THT_U2', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U2,THT_BSL_UP', 'THT_U2', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U2,THT_BSL_UP', 'THT_VT02_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_U2,THT_BSL_UP', 'THT_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Parejas de tramos en sentido impar:   MRN --> THT --> MIS
-- --------------------------------
-- Entradas a THT desde MRN 

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MRN_THT_VC1','THT_VT03','C','I,THT_D1,THT_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D1,THT_D5', 'THT_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D1,THT_D5', 'THT_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D1,THT_D5', 'THT_P12B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D1,THT_D5', 'THT_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D1,THT_D5', 'THT_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D1,THT_D5', 'THT_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Salidas desde THT hacia MIS

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_VT03','THT_MIS_VC1','C','I,THT_D5,THT_TMA_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D5,THT_TMA_DOWN', 'THT_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D5,THT_TMA_DOWN', 'THT_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D5,THT_TMA_DOWN', 'THT_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D5,THT_TMA_DOWN', 'THT_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D5,THT_TMA_DOWN', 'THT_VT03_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D5,THT_TMA_DOWN', 'THT_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,THT_D5,THT_TMA_DOWN', 'THT_VT07A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');






