-- Datos de la linea ASYUT NAGH HAMMADI
-- Enclavamiento: El Maragha (MRG)

-- 1. Creamos una nueva version */
--INSERT INTO GRP_VERSIONES VALUES (1, 'MRG.1st', 'GRP de MRG', to_date('2025-02-28 11:00:00','yyyy-mm-dd hh24:mi:ss'), to_date('2025-02-28 11:00:00','yyyy-mm-dd hh24:mi:ss'));  

-- Puntos de control: 
-- MRN: Maragha-North		T05, T08, T12 
-- MRG: Maragha				T03, T06 

-- Colaterales
-- THT: Tahta
-- GEZ: Geziret

-- Tabla GRP_PUNTOS_CONTROL:
-- GRP_PUNTOS_CONTROL(ID_VERSION, ID_PUNTO_CONTROL, CODIGO_ENCLAVAMIENTO, PC_NOMBRE_MALLAS, PC_TIPO, MNEMONICO, AUTOMATICO, CAMBIO_TREN, COD_RENFE, FECHA_ULTIMO_CAMBIO_AUTOMATICO, PERMITE_CAMBIO_AUTOMATICO)
--INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'MRN','MRG','Maragha-North',1,NULL,'A',NULL,NULL,NULL,'S',11);
--INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'MRG','MRG','Maragha',1,NULL,'A',NULL,NULL,NULL,'S',12);


-- ELEMENTOS de los puntos de contol
-- GRP_ELEMENTOS_PUNTOS_CONTROL(PUNTO_CONTROL, CODIGO_ELEMENTO, VIA, ID_VERSION)
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MRN','MRG_VT05','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MRN','MRG_VT08','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MRN','MRG_VT12','4',1);

INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MRG','MRG_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('MRG','MRG_VT06','2',1);


---------------------------------------------------------------------
-- Tablas GRP_TRAMOS y GRP_REL_TRAMOS_CIRCUITOS_VIA
---------------------------------------------------------------------
-- Tabla GRP_TRAMOS de estacionamiento
-- INSERT INTO GRP_TRAMOS VALUES (1,ID_TRAMO,ID_PUNTO_CONTROL,NULL,NULL,NULL,NULL,E_S,NULL,NULL,VIA,SENTIDO);
INSERT INTO GRP_TRAMOS VALUES (1,'MRN_VT05','MRN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MRN_VT08','MRN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MRN_VT12','MRN',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');

INSERT INTO GRP_TRAMOS VALUES (1,'MRG_VT03','MRG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'MRG_VT06','MRG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');


-- INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,ID_TRAMO,COD_CV,NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MRN_VT05','MRG_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MRN_VT08','MRG_VT08',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MRN_VT12','MRG_VT12',NULL);
                                                               
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MRG_VT03','MRG_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MRG_VT06','MRG_VT06',NULL);


---------------------------------------------------------------------
-- Tramos de Trayecto 
-- INSERT INTO GRP_TRAMOS VALUES (1,ID_TRAMO,ID_PUNTO_CONTROL,NULL,NULL,NULL,NULL,E_S,NULL,PC_SIGUIENTE,VIA,SENTIDO);
---------------------------------------------------------------------
-- Entrada desde THT a MRN en sentido PAR
--INSERT INTO GRP_TRAMOS VALUES (1,'THT_MRN_VC2','THT',NULL,NULL,NULL,NULL,'E',NULL,'MRN','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA (Bloqueo)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'THT_MRN_VC2','MRG_VTA726B',NULL);


-- Entrada desde GEZ a MRG en sentido IMPAR
--INSERT INTO GRP_TRAMOS VALUES (1,'GEZ_MRG_VC1','GEZ',NULL,NULL,NULL,NULL,'E',NULL,'MRG','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA (Bloqueo)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GEZ_MRG_VC1','MRG_VTA731B',NULL);


---------------------------------------------------------------------
-- Tramos de reset
-- INSERT INTO GRP_TRAMOS VALUES (1,ID_TRAMO,ID_PUNTO_CONTROL,NULL,NULL,NULL,NULL,E_S,NULL,PC_SIGUIENTE,VIA,SENTIDO);
---------------------------------------------------------------------
-- Salida de MRG a GEZ en sentido PAR  Via 2
--INSERT INTO GRP_TRAMOS VALUES (1,'MRG_GEZ_VT02A','MRG',NULL,NULL,NULL,NULL,'E',NULL,'GEZ','2','PAR');

--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MRG_GEZ_VT02A','MRG_VT02A',NULL);

-- Salida de MRN a THT en sentido IMPAR  Via 1
--INSERT INTO GRP_TRAMOS VALUES (1,'MRN_THT_VT09A','MRN',NULL,NULL,NULL,NULL,'E',NULL,'THT','1','IMPAR');

--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MRN_THT_VT09A','MRG_VT09A',NULL);


--------------------------------------------------------------
-- Parejas de tramos e Itinerarios en sentido PAR	- VIA 2
-- INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,SENTIDO,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--------------------------------------------------------------
-- Entradas de THT a MRN  via 2
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'THT_MRN_VC2','MRN_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'THT_MRN_VC2','MRN_VT12','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'THT_MRN_VC2','MRN_VT08','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'THT_MRN_VC2','MRN_VT12','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,'C',CODIGO_MANDO,80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_MRN_VC2','MRN_VT08','C','I,MRG_U10,MRG_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_MRN_VC2','MRN_VT12','C','I,MRG_U8,MRG_U12',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'THT_MRN_VC2','MRN_VT12','C','I,MRG_U10,MRG_U8',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas de MRN a MRG   via 2 
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MRN_VT08','MRG_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MRN_VT12','MRG_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MRN_VT08','MRG_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MRN_VT12','MRG_VT06','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,ID_TR_ORIGEN,ID_TR_DESTINO,'C',CODIGO_MANDO,80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MRN_VT08','MRG_VT06','C','I,MRG_U6,MRG_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MRN_VT12','MRG_VT06','C','I,MRG_U12,MRG_U4',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salida de MRG a GEZ   via 2
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MRG_VT06','MRG_GEZ_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MRG_VT06','MRG_GEZ_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MRG_VT06','MRG_GEZ_VC2','C','I,MRG_U4,MRG_GEZ_UP',80,NULL,NULL,'1',NULL,NULL,NULL);



------------------------------------------------------------
-- Parejas de tramos e Itinerarios en sentido IMPAR	- VIA 1 
------------------------------------------------------------
-- Entradas de GEZ a MRG
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GEZ_MRG_VC1','MRG_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GEZ_MRG_VC1','MRG_VT03','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GEZ_MRG_VC1','MRG_VT03','C','I,MRG_D1,MRG_D5',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Entradas de MRG a MRN  via 1
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MRG_VT03','MRN_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MRG_VT03','MRN_VT05','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MRG_VT03','MRN_VT05','C','I,MRG_D5,MRG_D7',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salida de MRN a THT   via 1
--------------------------
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MRN_VT05','MRN_THT_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MRN_VT05','MRN_THT_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MRN_VT05','MRN_THT_VC1','C','I,MRG_D7,MRG_THT_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);



------------------------------------------------------------------------------------
-- Tabla GRP_COMPROBACIONES_MANDOS en sentido PAR  Via 2
------------------------------------------------------------------------------------
-- GRP_COMPROBACIONES_MANDOS
-- (ID_VERSION, CODIGO_MANDO, CODIGO_ELEMENTO, ASPECTO, CONDICION, OPERACION_LOGICA)
------------------------------------------------------------------------------------
-- Entradas de THT a MRN   
--------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U6','MRG_U10','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U6','MRG_U10','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U6','MRG_P01A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U6','MRG_P02B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U6','MRG_VT10A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U6','MRG_VT10B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U6','MRG_VT08', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U8,MRG_U12','MRG_U8','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U8,MRG_U12','MRG_U8','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U8,MRG_U12','MRG_P01A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U8,MRG_U12','MRG_P02B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U8,MRG_U12','MRG_P02A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U8,MRG_U12','MRG_VT08', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U8','MRG_U10','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U8','MRG_U10','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U8','MRG_P01A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U8','MRG_P02B','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U8','MRG_P02A','AGU.NOR.ITG.ITI','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U8','MRG_VT10A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U8','MRG_VT10B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U10,MRG_U8','MRG_VT12', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Entradas de MRN a MRG   via 2 
--------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U6,MRG_U4','MRG_U6','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U6,MRG_U4','MRG_U6','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U6,MRG_U4','MRG_P03A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U6,MRG_U4','MRG_P04B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U6,MRG_U4','MRG_VT06_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U6,MRG_U4','MRG_VT06', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U12,MRG_U4','MRG_U12','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U12,MRG_U4','MRG_U12','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U12,MRG_U4','MRG_P03B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U12,MRG_U4','MRG_P03A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U12,MRG_U4','MRG_P04B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U12,MRG_U4','MRG_VT06_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U12,MRG_U4','MRG_VT06', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Salida de MRG a GEZ   via 2
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U4,MRG_GEZ_UP','MRG_U4','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U4,MRG_GEZ_UP','MRG_U4','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U4,MRG_GEZ_UP','MRG_P13B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U4,MRG_GEZ_UP','MRG_P14A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U4,MRG_GEZ_UP','MRG_VT04','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_U4,MRG_GEZ_UP','MRG_VT02A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


------------------------------------------------------------------------------------
-- Tabla GRP_COMPROBACIONES_MANDOS en sentido IMPAR  Via 1
------------------------------------------------------------------------------------
-- GRP_COMPROBACIONES_MANDOS
-- (ID_VERSION, CODIGO_MANDO, CODIGO_ELEMENTO, ASPECTO, CONDICION, OPERACION_LOGICA)
------------------------------------------------------------------------------------
-- Entradas de GEZ a MRG
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D1,MRG_D5','MRG_D1','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D1,MRG_D5','MRG_D1','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D1,MRG_D5','MRG_P14B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D1,MRG_D5','MRG_P13A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D1,MRG_D5','MRG_VT01A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D1,MRG_D5','MRG_VT01B','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D1,MRG_D5','MRG_VT03', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Entradas de MRG a MRN    via 1 
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D5,MRG_D7','MRG_D5','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D5,MRG_D7','MRG_D5','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D5,MRG_D7','MRG_P06B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D5,MRG_D7','MRG_P04A','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D5,MRG_D7','MRG_VT03_I','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRG_D5,MRG_D7','MRG_VT05', 'CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');


-- Salida de MRN a THT   via 1
---------------------------------
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRN_D7,MRG_THT_DOWN','MRG_D7','SEN.SE.ITG.CERRADA','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRN_D7,MRG_THT_DOWN','MRG_D7','SEN.SE.ITG.FAI_ACTIVADO','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRN_D7,MRG_THT_DOWN','MRG_P01B','AGU.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRN_D7,MRG_THT_DOWN','MRG_VT07','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1,'I,MRN_D7,MRG_THT_DOWN','MRG_VT09A','CV.NOR.ITG.LIBRE','E','LIBRERIA_AND');

