-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Geziret
-- Enclavamiento: GEZ
-- Puntos de control:
-- Geziret: 	  GEZ T05, T08 y T13
-- Geziret-South: GES T03, T06 y T11
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


-- - Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'GEZ','GEZ','Geziret',1,NULL,'A',NULL,NULL,NULL,'S',13);
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'GES','GEZ','Geziret-South',1,NULL,'A',NULL,NULL,NULL,'S',14);

-- -----------------------
-- PUNTO DE CONTROL: GES
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GES','GEZ_VT03','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GES','GEZ_VT06','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GES','GEZ_VT11','3',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'GES_VT03','GES',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GES_VT06','GES',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GES_VT11','GES',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GES_VT03','GEZ_VT03',NULL); 
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GES_VT06','GEZ_VT06',NULL); 
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GES_VT11','GEZ_VT11',NULL);

-- -------------------------

-- Tramos de trayecto en sentido PAR	SHG <-- GES <-- GEZ
-- ---------------------------------

-- GES --> SHG

-- Tramos de reset
-- CV de reset para la salida
--INSERT INTO GRP_TRAMOS VALUES (1,'GES_SHG_VT02A','GES',NULL,NULL,NULL,NULL,'E',NULL,'SHG','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GES_SHG_VT02A','GEZ_VT02A',NULL);


-- Tramos de trayecto en sentido impar    SHG --> GES --> GEZ
-- ---------------------------------
--SHG --> GES 

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'SHG_GES_VC1','SHG',NULL,NULL,NULL,NULL,'E',NULL,'GES','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA (CV de disparo) (En este caso se encuentra en Sohag)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHG_GES_VC1','SHG_VT13B',NULL);


-- -----------------------
-- PUNTO DE CONTROL: GEZ
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GEZ','GEZ_VT05','1',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GEZ','GEZ_VT08','2',1);
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('GEZ','GEZ_VT17','3',1);

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'GEZ_VT05','GEZ',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GEZ_VT08','GEZ',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'GEZ_VT17','GEZ',NULL,NULL,NULL,NULL,'S',NULL,NULL,'3','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GEZ_VT05','GEZ_VT05',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GEZ_VT08','GEZ_VT08',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GEZ_VT17','GEZ_VT17',NULL);

-- -------------------------

-- Tramos de trayecto en sentido par   GES <-- GEZ <-- MRG
-- ---------------------------------

-- MRG --> GEZ

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'MRG_GEZ_VC2','MRG',NULL,NULL,NULL,NULL,'E',NULL,'GEZ','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA (CV de disparo)
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'MRG_GEZ_VC2','GEZ_VTA744B',NULL);


-- Tramos de trayecto en sentido impar    GES --> GEZ --> MRG
-- ---------------------------------

-- GEZ --> MRG

-- Tramos de reset 
-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'GEZ_MRG_VT09A','GEZ',NULL,NULL,NULL,NULL,'E',NULL,'MRG','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GEZ_MRG_VT09A','GEZ_VT09A',NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------


-- -----------------------
-- PUNTO DE CONTROL: GES
-- -----------------------


-- Parejas de Tramos en sentido par   SHG <-- GES <-- GEZ
-- --------------------------------

-- Entradas a GES desde GEZ (P.C.)

-- Tabla GRP_PAREJAS_Tramos
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GEZ_VT08','GES_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GEZ_VT08','GES_VT06','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GEZ_VT08','GES_VT06','C','I,GEZ_U6,GEZ_U4',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde GES hacia SHG

-- Tabla GRP_PAREJAS_Tramos
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GES_VT06','GES_SHG_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GES_VT06','GES_SHG_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_VT06','GES_SHG_VC2','C','I,GEZ_U4,GEZ_SHG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);



-- Parejas de Tramos en sentido impar  SHG --> GES --> GEZ
-- --------------------------------
-- Entradas a GES desde SHG

-- Tabla GRP_PAREJAS_Tramos
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHG_GES_VC1','GES_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHG_GES_VC1','GES_VT11','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_Tramos_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHG_GES_VC1','GES_VT03','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHG_GES_VC1','GES_VT11','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_GES_VC1','GES_VT03','C','I,GEZ_D1,GEZ_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_GES_VC1','GES_VT11','C','I,GEZ_D1,GEZ_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_GES_VC1','GES_VT11','C','I,GEZ_D3,GEZ_D11',80,NULL,NULL,'1',NULL,NULL,NULL);

-- Salidas desde GES hacia GEZ

-- Tabla GRP_PAREJAS_Tramos
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GES_VT03','GEZ_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GES_VT11','GEZ_VT05','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GES_VT03','GEZ_VT05','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GES_VT11','GEZ_VT05','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_VT03','GEZ_VT05','C','I,GEZ_D5,GEZ_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_VT11','GEZ_VT05','C','I,GEZ_D11,GEZ_D7',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------
-- PUNTO DE CONTROL: GEZ
-- -----------------------

-- Parejas de Tramos en sentido par GES <-- GEZ <-- MRG
-- --------------------------------

-- Entradas a GEZ desde MRG 

-- Tabla GRP_PAREJAS_Tramos
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'MRG_GEZ_VC2','GEZ_VT08','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'MRG_GEZ_VC2','GEZ_VT08','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MRG_GEZ_VC2','GEZ_VT08','C','I,GEZ_U10,GEZ_U6',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde GEZ hacia GES
--Definidas EN GES (U6-U4)

-- Parejas de Tramos en sentido impar  GES --> GEZ --> MRG
-- --------------------------------

-- Entradas a GEZ desde GES 
-- Definidas en GES (D5-D7, D11-D7)

-- Salidas desde GEZ hacia MRG 

-- Tabla GRP_PAREJAS_Tramos
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GEZ_VT05','GEZ_MRG_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GEZ_VT17','GEZ_MRG_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GEZ_VT05','GEZ_MRG_VC1','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GEZ_VT17','GEZ_MRG_VC1','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_Tramos_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GEZ_VT05','GEZ_MRG_VC1','C','I,GEZ_D7,GEZ_MRG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GEZ_VT17','GEZ_MRG_VC1','C','I,GEZ_D13,GEZ_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GEZ_VT17','GEZ_MRG_VC1','C','I,GEZ_D9,GEZ_MRG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------

-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GEZ_VT08','GES_VT06','C','I,GEZ_U6,GEZ_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U6,GEZ_U4', 'GEZ_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U6,GEZ_U4', 'GEZ_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
--INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U6,GEZ_U4', 'GEZ_P04A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U6,GEZ_U4', 'GEZ_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U6,GEZ_U4', 'GEZ_VT06_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U6,GEZ_U4', 'GEZ_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_VT06','GES_SHG_VC2','C','I,GEZ_U4,GEZ_SHG_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U4,GEZ_SHG_UP', 'GEZ_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U4,GEZ_SHG_UP', 'GEZ_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U4,GEZ_SHG_UP', 'GEZ_P10B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U4,GEZ_SHG_UP', 'GEZ_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U4,GEZ_SHG_UP', 'GEZ_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_GES_VC1','GES_VT03','C','I,GEZ_D1,GEZ_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D5', 'GEZ_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D5', 'GEZ_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D5', 'GEZ_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D5', 'GEZ_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D5', 'GEZ_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D5', 'GEZ_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_GES_VC1','GES_VT11','C','I,GEZ_D1,GEZ_D3',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D3', 'GEZ_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D3', 'GEZ_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D3', 'GEZ_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D3', 'GEZ_P10A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D3', 'GEZ_P09B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D3', 'GEZ_P09A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D1,GEZ_D3', 'GEZ_VT11', 'CV.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_GES_VC1','GES_VT11','C','I,GEZ_D3,GEZ_D11',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D3,GEZ_D11', 'GEZ_D3', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D3,GEZ_D11', 'GEZ_D3', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D3,GEZ_D11', 'GEZ_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D3,GEZ_D11', 'GEZ_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D3,GEZ_D11', 'GEZ_P09A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D3,GEZ_D11', 'GEZ_VT11', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_VT03','GEZ_VT05','C','I,GEZ_D5,GEZ_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D5,GEZ_D7', 'GEZ_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D5,GEZ_D7', 'GEZ_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D5,GEZ_D7', 'GEZ_P08A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D5,GEZ_D7', 'GEZ_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D5,GEZ_D7', 'GEZ_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D5,GEZ_D7', 'GEZ_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D5,GEZ_D7', 'GEZ_VT03_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D5,GEZ_D7', 'GEZ_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_VT11','GEZ_VT05','C','I,GEZ_D11,GEZ_D7',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D11,GEZ_D7', 'GEZ_D11', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D11,GEZ_D7', 'GEZ_D11', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D11,GEZ_D7', 'GEZ_P08B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D11,GEZ_D7', 'GEZ_P08A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D11,GEZ_D7', 'GEZ_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D11,GEZ_D7', 'GEZ_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D11,GEZ_D7', 'GEZ_P04B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D11,GEZ_D7', 'GEZ_VT03_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D11,GEZ_D7', 'GEZ_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'MRG_GEZ_VC2','GEZ_VT08','C','I,GEZ_U10,GEZ_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U10,GEZ_U6', 'GEZ_U10', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U10,GEZ_U6', 'GEZ_U10', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U10,GEZ_U6', 'GEZ_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U10,GEZ_U6', 'GEZ_VT12B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U10,GEZ_U6', 'GEZ_VT10', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_U10,GEZ_U6', 'GEZ_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GEZ_VT05','GEZ_MRG_VC1','C','I,GEZ_D7,GEZ_MRG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D7,GEZ_MRG_DOWN', 'GEZ_D7', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D7,GEZ_MRG_DOWN', 'GEZ_D7', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D7,GEZ_MRG_DOWN', 'GEZ_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D7,GEZ_MRG_DOWN', 'GEZ_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D7,GEZ_MRG_DOWN', 'GEZ_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D7,GEZ_MRG_DOWN', 'GEZ_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GEZ_VT17','GEZ_MRG_VC1','C','I,GEZ_D13,GEZ_D9',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D13,GEZ_D9', 'GEZ_D13', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D13,GEZ_D9', 'GEZ_D13', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D13,GEZ_D9', 'GEZ_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D13,GEZ_D9', 'GEZ_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D13,GEZ_D9', 'GEZ_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D13,GEZ_D9', 'GEZ_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GEZ_VT17','GEZ_MRG_VC1','C','I,GEZ_D9,GEZ_MRG_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D9,GEZ_MRG_DOWN', 'GEZ_D9', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D9,GEZ_MRG_DOWN', 'GEZ_D9', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,GEZ_D9,GEZ_MRG_DOWN', 'GEZ_VT09A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

