-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
-- Sohag
-- Enclavamiento: SHG
-- Puntos de control:
-- Sohag: SHG T03, T06, T16, T18
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 


-- - Tabla GRP_PUNTOS_CONTROL:
-- INSERT INTO GRP_PUNTOS_CONTROL VALUES (1,'SHG','SHG','Sohag',1,NULL,'A',NULL,NULL,NULL,'S',15);

-- -----------------------
-- PUNTO DE CONTROL: SHG
-- -----------------------

-- Tramos de estacionamiento
-- -------------------------

-- Tabla GRP_ELEMENTOS_PUNTOS_CONTROL
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SHG','SHG_VT03','1',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SHG','SHG_VT06','2',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SHG','SHG_VT16','4',1);	
INSERT INTO GRP_ELEMENTOS_PUNTOS_CONTROL VALUES('SHG','SHG_VT18','6',1);	

-- Tabla GRP_TRAMOS
INSERT INTO GRP_TRAMOS VALUES (1,'SHG_VT03','SHG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'1','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SHG_VT06','SHG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'2','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SHG_VT16','SHG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'4','P.C.');
INSERT INTO GRP_TRAMOS VALUES (1,'SHG_VT18','SHG',NULL,NULL,NULL,NULL,'S',NULL,NULL,'6','P.C.');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHG_VT03','SHG_VT03',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHG_VT06','SHG_VT06',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHG_VT16','SHG_VT16',NULL);
INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHG_VT18','SHG_VT18',NULL);


-- -------------------------------------------------------
-- Tramos de trayecto en sentido PAR:  BSN <-- SHG <-- GES
-- -------------------------------------------------------

--GES --> SHG

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'GES_SHG_VC2','GES',NULL,NULL,NULL,NULL,'E',NULL,'SHG','2','PAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA 
-- Este CV lo dice ENR 
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'GES_SHG_VC2','GEZ_VT02B',NULL); 

--SHG --> BSN

-- Tramos de RESET de salida

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'SHG_BSN_VT02A','SHG',NULL,NULL,NULL,NULL,'E',NULL,'BSN','2','PAR'); 

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHG_BSN_VT02A','SHG_VT02A',NULL); 


-- Tramos de trayecto en sentido IMPAR:  BSN --> SHG --> GES
-- ---------------------------------

--BSN --> SHG de entrada

-- Tabla GRP_TRAMOS
--INSERT INTO GRP_TRAMOS VALUES (1,'BSN_SHG_VC1','BSN',NULL,NULL,NULL,NULL,'E',NULL,'SHG','1','IMPAR');

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA 
-- Este CV lo dice ENR 
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'BSN_SHG_VC1','BLS_VTA765B',NULL); 

--SHG --> GES

-- Tramos de RESET de salida

-- Tabla GRP_TRAMOS 
-- En estos casos es el cdv siguiente a la señal de entrada
--INSERT INTO GRP_TRAMOS VALUES (1,'SHG_GES_VT07','SHG',NULL,NULL,NULL,NULL,'E',NULL,'GES','2','IMPAR'); 

-- Tabla GRP_REL_TRAMOS_CIRCUITOS_VIA
--INSERT INTO GRP_REL_TRAMOS_CIRCUITOS_VIA VALUES (1,'SHG_GES_VT07','SHG_VT07',NULL); 


-- -- -----------------------------------------------------------------------------------------------------------------------------------------


-- Parejas de tramos en sentido par:   BSN <-- SHG <-- GES
-- --------------------------------
-- Entradas a SHG desde GES

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GES_SHG_VC2','SHG_VT06','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GES_SHG_VC2','SHG_VT16','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'GES_SHG_VC2','SHG_VT18','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GES_SHG_VC2','SHG_VT06','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GES_SHG_VC2','SHG_VT16','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'GES_SHG_VC2','SHG_VT18','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_SHG_VC2','SHG_VT06','C','I,SHG_U14,SHG_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_SHG_VC2','SHG_VT16','C','I,SHG_U14,SHG_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_SHG_VC2','SHG_VT16','C','I,SHG_U6,SHG_U16',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_SHG_VC2','SHG_VT18','C','I,SHG_U14,SHG_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_SHG_VC2','SHG_VT18','C','I,SHG_U6,SHG_U18',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde SHG hacia BSN 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHG_VT06','SHG_BSN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHG_VT16','SHG_BSN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHG_VT18','SHG_BSN_VC2','PAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHG_VT06','SHG_BSN_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHG_VT16','SHG_BSN_VC2','C',NULL,NULL,NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHG_VT18','SHG_BSN_VC2','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT06','SHG_BSN_VC2','C','I,SHG_U4,SHG_BLS_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT16','SHG_BSN_VC2','C','I,SHG_U16,SHG_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT16','SHG_BSN_VC2','C','I,SHG_U2,SHG_BLS_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT18','SHG_BSN_VC2','C','I,SHG_U18,SHG_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT18','SHG_BSN_VC2','C','I,SHG_U2,SHG_BLS_UP',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Parejas de tramos en sentido impar:   BSN --> SHG --> GES
-- --------------------------------

-- Entradas a SHG desde BSN 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'BSN_SHG_VC1','SHG_VT03','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL); 

-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'BSN_SHG_VC1','SHG_VT03','C',NULL,NULL,NULL,NULL,NULL);

-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BSN_SHG_VC1','SHG_VT03','C','I,SHG_D1,SHG_D5',80,NULL,NULL,'1',NULL,NULL,NULL);


-- Salidas desde SHG hacia GES 

-- Tabla GRP_PAREJAS_TRAMOS
INSERT INTO GRP_PAREJAS_TRAMOS VALUES (1,'SHG_VT03','SHG_GES_VC1','IMPAR',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_OPERADOR
INSERT INTO GRP_PAREJAS_TRAMOS_OPERADOR VALUES (1,'SHG_VT03','SHG_GES_VC1','C',NULL,NULL,NULL,NULL,NULL);


-- Tabla GRP_PAREJAS_TRAMOS_MANDOS
INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT03','SHG_GES_VC1','C','I,SHG_D5,SHG_GEZ_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);


-- -----------------------------------------------------------------------------------------------------------------------------------------


-- Tabla GRP_COMPROBACIONES_MANDOS

-- Señal de principio de itinerario cerrada y con ARS activado.
-- Agujas pertenecientes a ruta libres (puede que no todas se comprueben, hay que ver las condiciones particulares de cada ruta).
-- Circuitos de vía pertenecientes a ruta libres (puede que no todos se comprueben, hay que ver las condiciones particulares de cada ruta).


--SHG

-- Parejas de tramos en sentido par:   BSN <-- SHG <-- GES
-- --------------------------------
-- Entradas a SHG desde GES

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_SHG_VC2','SHG_VT06','C','I,SHG_U14,SHG_U4',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_U14', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_U14', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_P08B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_P11B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_P13A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_VT14B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_VT12', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_VT10A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U4', 'SHG_VT06', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_SHG_VC2','SHG_VT16','C','I,SHG_U14,SHG_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_U14', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_U14', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_P01A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_P02B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_P07B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_P08B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_VT14B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_VT12', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_VT10A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_VT10B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_VT08', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_P11B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_P13A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_P13B', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U14,SHG_U6', 'SHG_P14A', 'AGU.NOR.ITG.ITI', 'E', 'LIBRERIA_AND');
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_SHG_VC2','SHG_VT16','C','I,SHG_U6,SHG_U16',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U16', 'SHG_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U16', 'SHG_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U16', 'SHG_P11B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U16', 'SHG_P13A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U16', 'SHG_P13B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U16', 'SHG_P14A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U16', 'SHG_P15B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U16', 'SHG_VT16', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

--(ARRIBA) INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_SHG_VC2','SHG_VT18','C','I,SHG_U14,SHG_U6',80,NULL,NULL,'1',NULL,NULL,NULL);
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'GES_SHG_VC2','SHG_VT18','C','I,SHG_U6,SHG_U18',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U18', 'SHG_U6', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U18', 'SHG_U6', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U18', 'SHG_P11B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U18', 'SHG_P13A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U18', 'SHG_P13B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U18', 'SHG_P14A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U18', 'SHG_P14B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U18', 'SHG_P15A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U6,SHG_U18', 'SHG_VT18', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Salidas desde SHG hacia BSN 

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT06','SHG_BSN_VC2','C','I,SHG_U4,SHG_BLS_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U4,SHG_BSL_UP', 'SHG_U4', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U4,SHG_BSL_UP', 'SHG_U4', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U4,SHG_BSL_UP', 'SHG_P18B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U4,SHG_BSL_UP', 'SHG_P19A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U4,SHG_BSL_UP', 'SHG_P20B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U4,SHG_BSL_UP', 'SHG_VT04A_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U4,SHG_BSL_UP', 'SHG_VT04B_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U4,SHG_BSL_UP', 'SHG_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U4,SHG_BSL_UP', 'SHG_VT02_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U4,SHG_BSL_UP', 'SHG_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT16','SHG_BSN_VC2','C','I,SHG_U16,SHG_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U16,SHG_U2', 'SHG_U16', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U16,SHG_U2', 'SHG_U16', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U16,SHG_U2', 'SHG_P17B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U16,SHG_U2', 'SHG_P18A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U16,SHG_U2', 'SHG_P18B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U16,SHG_U2', 'SHG_P19A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U16,SHG_U2', 'SHG_P20B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U16,SHG_U2', 'SHG_VT04A_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U16,SHG_U2', 'SHG_VT04B_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U16,SHG_U2', 'SHG_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT16','SHG_BSN_VC2','C','I,SHG_U2,SHG_BLS_UP',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U2,SHG_BSL_UP', 'SHG_U2', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U2,SHG_BSL_UP', 'SHG_U2', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U2,SHG_BSL_UP', 'SHG_VT02_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U2,SHG_BSL_UP', 'SHG_VT02A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT18','SHG_BSN_VC2','C','I,SHG_U18,SHG_U2',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_U18', 'SEN.SS.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_U18', 'SEN.SS.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_P17A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_P17B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_P18A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_P18B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_P19A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_P20B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_VT04A_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_VT04B_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_U18,SHG_U2', 'SHG_VT04', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
--(ARRIBA) INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT18','SHG_BSN_VC2','C','I,SHG_U2,SHG_BLS_UP',80,NULL,NULL,'1',NULL,NULL,NULL);




-- Parejas de tramos en sentido impar:   BSN --> SHG --> GES
-- --------------------------------
-- Entradas a SHG desde BSN 

-- INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'BSN_SHG_VC1','SHG_VT03','C','I,SHG_D1,SHG_D5',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D1,SHG_D5', 'SHG_D1', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D1,SHG_D5', 'SHG_D1', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D1,SHG_D5', 'SHG_P20A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D1,SHG_D5', 'SHG_P19B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D1,SHG_D5', 'SHG_VT01B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D1,SHG_D5', 'SHG_VT03A_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D1,SHG_D5', 'SHG_VT03B_I', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D1,SHG_D5', 'SHG_VT03', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');


-- Salidas desde SHG hacia GES

--INSERT INTO GRP_PAREJAS_TRAMOS_MANDOS VALUES (1,'SHG_VT03','SHG_GES_VC1','C','I,SHG_D5,SHG_GEZ_DOWN',80,NULL,NULL,'1',NULL,NULL,NULL);
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_D5', 'SEN.SE.ITG.CERRADA', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_D5', 'SEN.SE.ITG.FAI_ACTIVADO', 'E', 'LIBRERIA_AND');	
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_P16B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_P11A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_P10A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_P09B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_P07A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_P06B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_P03', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_P02A', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_P01B', 'AGU.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND'); 
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_VT05', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_VT07', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_VT09', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_VT11B', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');
INSERT INTO GRP_COMPROBACIONES_MANDOS VALUES (1, 'I,SHG_D5,SHG_GEZ_DOWN', 'SHG_VT13A', 'CV.NOR.ITG.LIBRE', 'E', 'LIBRERIA_AND');






